### ISSUE TITLE
field in one pod has the same name as another pod

### ISSUE THREAD

**Issue by kpstraus** [pods-framework/pods#5093] opened 2018-08-08 17:44 UTC
## Issue Overview

confusing error message when field in one pod has the same name as another pod

## Expected Behavior

 

Either prevent the field with a duplicate name from being created, or give a more helpful message about the name conflict when detected.

## Current Behavior

 

I was trying to update a Pod, but I couldn't save it.  Error message was: “Error: grade-new is reserved for internal WordPress or Pods usage, please try a different name.”  But I was not changing the existing "grade-new" field, just adding some new ones. “grade-new” is a relationship field to a taxonomy.  But, my mistake (long story) "grade-new" is also the name of the taxonomy that the field relates to.

## Steps to Reproduce (for bugs)

1.  Create a (pod) taxonomy with the name "grade-new"
2. Add to another pod (post type), a relationship field named "grade-new" and relate it to the taxonomy. Save. (I got no error.)
3. Now, try to add another field to the pod (post type), and save.
4. I got error message “Error: grade-new is reserved for internal WordPress or Pods usage, please try a different name.”

## Possible Solution

Either prevent the field with a duplicate name from being created, or give a more helpful message about the name conflict when detected.

I resolved this by simply renaming the existing field.  But, of course, the two new fields that I configured were lost. Once the error message is generated, it's impossible to go back, fix, and save.

## WordPress Environment

<details>
```Wordpress 5.9.8 / Php 5.6 / Pods 2.7.8. (But, I may have on a previous version of Pods when I created the field with the duplicate name)

Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by quasel** [comment] 2018-08-31 10:26
couldn't reproduce it :/ did you have any luck @jimtrue ? 

Side Note:
- We don't recommend using relationships to taxonomies unless you know exactly what you are doing, most of the time the better way is to assign it via -> Advance Options, bottom of page -> Built in Taxonomies .
- Name your relationship fields always like. `rel_<related_cpt>`makes for easier distinction!

**Comment by jimtrue** [comment] 2019-03-29 16:43
If `grade-new` the taxonomy was also associated to the primary post type where you were adding a field name `grade-new`, this would not allow the creation of the new field.

These need to be caught at the field name creation. Somewhat related to #4122

**Closed by jimtrue** 2019-03-29 16:43 UTC
Labels: Status: Could not reproduce, Status: Need Reproduction
