### ISSUE TITLE
Widgets broken in 2.7.2

### ISSUE THREAD

**Issue by ChrisWiegman** [pods-framework/pods#4901] opened 2018-05-05 01:18 UTC
## Issue Overview
Widget title and other markup is broken in Pods 2.7.2

## Expected Behavior
When adding a widget the title, before and after text should appear in standard widget markup.

## Current Behavior
Widget wrappers are removed. Title and before text run together as does after text

## Possible Solution
Downgrade to Pods 2.7.1

## Steps to Reproduce (for bugs)
1. Upgrade to pods 2.7.2
2. View a page with a widget on it.

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Debug Information
WordPress Version: 4.9.5

PHP Version: 7.2.4-1+ubuntu16.04.1+deb.sury.org+1

MySQL Version: 5.5.5

Server Software: nginx/1.13.12

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: Yes
WPDB Prefix: c7io2b_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/chriswiegmanadmin/htdocs/content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: ChrisWiegman

Currently Active Plugins:

Admin Columns Pro: 4.2.9
Admin Columns Pro - Pods: 1.1
Akismet Anti-Spam: 4.0.3
Better YOURLS: 2.2.4
Cookie Notice: 1.2.42
Enlighter - Customizable Syntax Highlighter: 3.5
EWWW Image Optimizer: 4.2.0
FeedPress: 1.7.2
Google Analytics for WordPress by MonsterInsights: 7.0.5
Gravity Forms: 2.3.1
Gravity Forms MailChimp Add-On: 4.3
Gutenberg: 2.8.0
Jetpack by WordPress.com: 6.1
Nginx Helper: 1.9.11
Pods - Custom Content Types and Fields: 2.7.1
Postmatic Social Commenting: 1.1.1
Replyable - Subscribe to Comments & Reply by email: 2.2.3
SearchWP: 2.9.12
SearchWP Fuzzy Matches: 1.4.3
SearchWP LIKE Terms: 2.4.6
SearchWP Live Ajax Search: 1.3.1
SearchWP Term Highlight: 2.1.13
WP fail2ban: 3.5.3
Yoast SEO: 7.4.2
```
</details>

**Comment by jimtrue** [comment] 2018-05-05 14:06
This is a duplicate of #4891 I just tested locally and the correction for Widgets fixed this issue from (#4894 )

**Closed by jimtrue** 2018-05-05 14:06 UTC
Labels: Duplicate, Fixed / Needs Testing
