### ISSUE TITLE
WordPress Import error

### ISSUE THREAD

**Issue by szepeviktor** [pods-framework/pods#1974] opened 2014-01-15 01:22 UTC
1.  migrate Pods' data
2.  export WP data `/wp-admin/export.php` including Pods-created post types' data
3.  import WP data on the other empty WP installation

The error is: if you have required fields - its content cannot be imported.

**Comment by quasel** [comment] 2018-09-02 11:26
Duplicate of #1985

**Closed by quasel** 2018-09-02 11:26 UTC
Labels: Keyword: Puntable, Status: Help Wanted, Type: Bug
