### ISSUE TITLE
Template shortcodes

### ISSUE THREAD

**Issue by winnersmedia** [pods-framework/pods#3438] opened 2016-03-05 08:42 UTC
When using templates with shortcodes it would be good if that when a pod isn't defined the template allows you to put the loop within the template. For example if you want to include a surrounding table around a comparison table and don't want it modified per page.

e.g
[pods template="Comparison Table"]

Instead of:
[pods name="site" template="Comparison Table"]

**Comment by jimtrue** [comment] 2016-03-07 20:41
That really wouldn't be a job for our Pods Templates because the above assumes you just want to output some html with no fields or magic tags in them, right? Without a Pods name, you're not opening a loop or window into a Pod. Or am I mistaken as to what you're trying to accomplish?

**Comment by winnersmedia** [comment] 2016-03-08 19:43
no. In my template I want to do a loop so

```
<table>
<thead>
<tr class="row-1 odd">
<th class="column-1">
<div>Site</div></th>
<th class="column-2">
<div>Offer</div></th>
<th class="column-3">
<div>Free</div></th>
<th class="column-4">
<div>Visit</div></th>

</tr>
</thead>
<tbody class="row-hover">
[pods name="site" where="placement.slug = 'new-sites'"]
<tr>
<td class="column-1"><a href="{@permalink}">{@post_title}</a></td>
<td class="column-2">{@offer}</td>
<td class="column-3">&pound;{@free}</td>
<td class="column-4"><a href="{@default_tracking_url}" target="_blank">View &raquo;</a></td>
</tr>
[/pods]
</tbody>
</table>
```
so it just keeps the table heading inside the template and can't be messed around by users in the editor.

**Comment by jimtrue** [comment] 2016-03-10 22:50
Okay, that would be the capability of pulling template code from within an existing template (ie like an include) and yes, we've got that as an item in #3395. Closing this one as duplicate to that issue, but you're welcome to add comments to that one.

**Comment by jimtrue** [comment] 2016-03-10 22:50
Closing as a duplicate of #3395

**Closed by jimtrue** 2016-03-10 22:50 UTC
Labels: Duplicate
