### ISSUE TITLE
Varnish Caching Issues

### ISSUE THREAD

**Issue by zackeryfretty** [pods-framework/pods#4443] opened 2017-09-04 13:59 UTC
We're having issues with Varnish Cache + Pods (specifically using DreamPress - similar to https://github.com/pods-framework/pods/issues/4325) that's causing strange issues in the backend of WordPress such as:

1. Dashboard Widgets failing to pull fresh data.
2. Media Library not pulling images. 

I've confirmed with DreamPress the issue seems related to Pods + Varnish. When manually clearing the Varnish cache everything works (temporarily) and when Pods is deactivated everything works correctly. 

The only solution they're willing to offer is to whitelist directories/urls from their Varnish configuration. 

Does anyone have a list / idea of the paths we'd need to exclude from Varnish to insure that Pods is completely excluded? All of the dashboard is already excluded.

**Comment by jordonbaade** [comment] 2018-01-18 07:27
https://github.com/pods-framework/pods/issues/2542#issue-52656638

Comment here suggests:
```define('PODS_SESSION_AUTO_START', false); in the functions.php```

Using it myself just now, worked for me.

Also, Hi friend! 😄

**Comment by quasel** [comment] 2018-08-31 22:17
Sorry for the late reply, feel free to comment if you still have questions!
Duplicate of #4636

**Closed by quasel** 2018-08-31 22:17 UTC
Labels: Closed: Duplicate, Type: Bug, Type: Support
