### ISSUE TITLE
Getting “\” while updating existing pod field

### ISSUE THREAD

**Issue by swabhav** [pods-framework/pods#5950] opened 2021-02-18 12:30 UTC
I’m getting problems while updating the existing pods field, getting (slash \ ) automatically if I put ( semicolon " ) in default values.
check the screenshot – https://prnt.sc/zywy98

**Comment by JoryHogeveen** [comment] 2021-02-18 14:42
Duplicate of #5909 
Patch can be found here: #5910

**Closed by JoryHogeveen** 2021-02-18 14:42 UTC

**Comment by swabhav** [comment] 2021-02-19 11:53
I have done that, but now getting a new issue default value coming to the post field but when I publish the post it automatically gone.

**Comment by swabhav** [comment] 2021-02-19 12:09
I have done that, but now getting a new issue default value coming in the post field correctly but when I publish the post it automatically gone.

**Comment by swabhav** [comment] 2021-02-19 12:09
> Duplicate of #5909
> Patch can be found here: #5910

I have done that, but now getting a new issue default value coming in the post field correctly but when I publish the post it automatically gone.

**Comment by quasel** [comment] 2021-02-19 14:10
@swabhav pleas add your report to the original issue #5909 !
