### ISSUE TITLE
pods_is_admin check improvement

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#3625] opened 2016-07-04 16:48 UTC
Currently the admin capabilities check for the `delete_users` capability in `pods_is_admin()` (includes / general.php).
I've would like to see this changed into `manage_options` or `administrator` since Pods is a options page...

An other idea is to just use the is_super_admin() function since this function also works for non-multisite installations.

**Comment by quasel** [comment] 2018-09-01 14:09
Duplicate of #2311

**Closed by quasel** 2018-09-01 14:09 UTC
Labels: Status: Need Dev Feedback, Status: Need User Feedback
