### ISSUE TITLE
Pods::Duplicate() doesn't work

### ISSUE THREAD

**Issue by lougreenwood** [pods-framework/pods#4025] opened 2017-03-04 14:39 UTC
When attempting to duplicate an item using `Pods::duplicate` method(), no item is duplicated and the original Pod item is returned.

http://pods.io/docs/code/pods/duplicate/

To reproduce, do:

```
$new_pod = Pods( $someID );
$dupe_id = $new_pod->duplicate();
if( $dupe_id == someID ){
echo('not duplicated');
}
```

**Comment by lougreenwood** [comment] 2017-03-04 14:56
Looks like #3238 may be related...?

**Comment by sc0ttkclark** [comment] 2017-03-20 13:32
@lougreenwood is this an issue only with WP objects? This doesn't happen on ACT's right?

**Comment by sc0ttkclark** [comment] 2017-03-20 13:36
Looks like a duplicate of #3238 unless this doesn't work for ACTs too.

**Comment by pglewis** [comment] 2017-03-20 16:53
Yeah, looks like a duplicate.  I left the other one open as I was going to copy over the extra information there and didn't get to it yet.

**Closed** 2017-03-22 01:36 UTC
Labels: Duplicate, in progress
