### ISSUE TITLE
Related Fields on Extended Media not showing

### ISSUE THREAD

**Issue by andreas2249** [pods-framework/pods#4729] opened 2018-01-24 20:23 UTC
Jim True asked me to report this:

I extended my Media Library by adding a label (Camera Used) as a relationship related to Simple Custom Defined List. I added three Custom Defined Options and saved the Pod (see screeenshots below). The "Camera Used" label does show up but there's no drop-down with the corresponding three Custom Defined Options. Developer Console showed ERR_BLOCKED_BY_CLIENT. (Turning off AdBlocker didn't resolve this...) 

![related lilst 1](https://user-images.githubusercontent.com/3160243/35355111-24e785f0-0101-11e8-83b5-3e884a750e51.png)

![related list 2](https://user-images.githubusercontent.com/3160243/35355127-31d707ea-0101-11e8-9198-168c1487982b.png)

**Comment by jimtrue** [comment] 2018-01-24 20:24
@andreas2249 Was there any more to the error than just 'ERR_BLOCKED_BY_CLIENT. '? It usually tells the source, etc. where those might be coming from. A Screenshot of the error in the console might help ;)

**Comment by andreas2249** [comment] 2018-01-24 20:56
Here you go, Jim. Disabling AdBlock does remove these errors. But doing so does not restore / display the dropdown functionality.

Thanks, Jim. :)

![related list error from console](https://user-images.githubusercontent.com/3160243/35356573-ac0d872e-0105-11e8-8419-dfa11aa74d02.png)

**Comment by jimtrue** [comment] 2018-01-25 15:49
*Confirmed* On the Media Modal for adding new images, our relationship fields are not displaying.  They are visible if you just edit the Media in the Library, however.

@andreas2249 Can you confirm if your selection field is showing in the Media Library if you edit the posts there directly?

**Comment by andreas2249** [comment] 2018-01-25 18:20
Jim, I get the same result whether adding a new image or editing an existing one. The label shows but the drop-down does not. Here's what it looks like:
![related list error from console 2](https://user-images.githubusercontent.com/3160243/35404891-516ad862-01b9-11e8-960e-6369bf0a811c.png)

**Comment by jimtrue** [comment] 2018-01-25 19:09
@andreas2249 That's the Media Modal for the Media Library. Head into the WordPress Admin, under Media, and edit a library item from there and see if your fields are visible.

**Comment by andreas2249** [comment] 2018-01-25 19:22
Sorry, Jim: Wordpress 'noob' here. Not sure what mean "WordPress Admin under Media"... From my dashboard the only options I have under Media are 'Library' and 'Add new.' Please clarify.

I did switch to tabular view and edited a photo. Same as before: A label without the options. Here's what I see:
![related list error 4](https://user-images.githubusercontent.com/3160243/35407829-f141b998-01c1-11e8-9978-151a030c68f6.png)

**Comment by jimtrue** [comment] 2018-01-25 19:24
That's what I mean, in Your Library, edit a media field and see if your additional fields are avaiable. That's the 'editor' view for Media. I just want to rule out that the only area the fields _arent'_ showing is in the Add/Edit Media Modal which is a pop-up over your editor.

**Comment by andreas2249** [comment] 2018-01-25 19:35
Got it. Whether I'm adding or editing -- and whether I'm in the modal or editor, the results are the same: The field label 'Camera Used' is visible and the "Custom Defined Options" (iPhone, Canon, Nikon) are not visible. I believe it's set up correctly (see below). (Advanced options is blank.)
![related list 5](https://user-images.githubusercontent.co
![related list 6](https://user-images.githubusercontent.com/3160243/35408391-bc971222-01c3-11e8-97fd-7b49bd2dc369.png)
m/3160243/35408324-8a6ed2e4-01c3-11e8-8403-31312050ba91.png)
are not visible.

**Comment by jimtrue** [comment] 2018-01-25 19:36
Never doubted your field was setup correctly at all. This is more UI stopping something from working properly. On my local, the Modal does not show the select-drop down fields, but the Media, Library 'Edit' option does.

**Comment by GitHubGreg** [comment] 2018-02-21 00:49
I’m having a similar issue. I use Pods to extend Media items in WordPress. Recently, when I open a media item in a modal window (by clicking a media item from grid view) the modal window doesn’t correctly show the Pods fields. The description text for the fields show, but not the radio buttons and checkboxes themselves. I’ve disabled all plugins and custom functions so the issue seems to be with the Pods/WordPress relationship.

**Comment by GitHubGreg** [comment] 2018-02-21 20:23
In case it helps, here is more detail on my issue. We use Pods to extend the WordPress Media post type with extra fields (checkboxes, radio buttons and relationship fields to Users and other Custom Post Types). My client sometimes uploads hundreds of PDFs at a time, and uses the grid view in the media library to load a PDF in a modal window and assign the fields. These auto-save and he simply clicks the right arrow (>) to repeat for the next media item. The workflow is as fast as it can be for such a job. However, now that the media modal window no longer shows the Pods fields, none of this is possible. The only possibility is to open a media file in the full post editor view, make the changes, and publish. Then go back to the All Media page and click the next one.

Here is a screenshot of how it worked in Pods 2.6.11 and how it works now in Pods 2.7.1, in case it helps illustrate.

Pods 2.6.11
![screen shot 2018-02-21 at 3 09 24 pm](https://user-images.githubusercontent.com/7059106/36503315-b8310c08-171a-11e8-88da-aacc4b9fbf3f.jpg)

Pods 2.7.1
![screen shot 2018-02-21 at 2 55 27 pm](https://user-images.githubusercontent.com/7059106/36503314-b81ccbda-171a-11e8-9a79-c37d3cd13855.jpg)

**Comment by pglewis** [comment] 2018-03-07 02:58
I believe this is a duplicate of #4462, which is a known issue but a sticky one.  

This is only a problem in the Media Library's "Grid Mode", "List Mode" does work properly as a potential workaround (there are icons to switch between grid mode and list mode near the top left of the main Media Library page).

**Comment by GitHubGreg** [comment] 2018-03-07 12:18
Yes, as per my original post, "The only possibility is to open a media file in the full post editor view, make the changes, and publish."

That unfortunately makes the job of my client much longer. They regularly tag hundreds of PDFs with various pods fields, this was the best approach since in Grid Mode, clicking a media item opens a modal window where, as fields are edited, it auto-saves, then you just click the next button. All javascript. All very fast.

The List Mode workaround (open full post, change, publish) takes about 4 times longer per file, which adds up.

**Comment by pglewis** [comment] 2018-03-07 19:10
Yeah, the workaround is far from ideal.  

WordPress saves dynamically in grid mode and the main sticking point is they've assumed dynamic fields will be basic enough that they can simply save on the change event for any input, select, or textarea.  This doesn't play well with more complex dynamic field views like autocomplete or list view since it uses a temporary select box for the autocomplete portion.

**Comment by pglewis** [comment] 2018-03-07 19:25
I'm going to close this as a duplicate of #4462.  

I'm also putting together a PR that might allow the other pick field views to work (autocomplete and list view might be the only problem children).  #4785

**Closed by pglewis** 2018-03-07 19:25 UTC
Labels: Bug, Duplicate, Verified/Reproduced
