### ISSUE TITLE
Bug with date format

### ISSUE THREAD

**Issue by tristanleboss** [pods-framework/pods#5421] opened 2019-07-13 10:45 UTC
I use a French WordPress installation with latest Pods and latest WordPress.
This is NOT a regression due to the date fix present in 2.7.14: the bug is here since a long time.

I have a "Date/Time" field set to use format "d/m/Y" ("dmy" is the select option value).

Capture done on July, 13th:
![image](https://user-images.githubusercontent.com/1431508/61170582-93b97780-a56b-11e9-8231-21713c0ce254.png)

If I create a new content, it seems to work (I choose July, 8th):

![image](https://user-images.githubusercontent.com/1431508/61170589-b3e93680-a56b-11e9-9f3d-91fe9373c0c4.png)

If I save, I get this in the database (still July, 8th):

![image](https://user-images.githubusercontent.com/1431508/61170601-e2ffa800-a56b-11e9-9aa4-15d6d40d037a.png)

But, if I come back to the content, the date is wrong (July, 8th became August, 7th):

![image](https://user-images.githubusercontent.com/1431508/61170619-10e4ec80-a56c-11e9-804b-1094348841da.png)

My WP Settings > General:

![image](https://user-images.githubusercontent.com/1431508/61170658-bc8e3c80-a56c-11e9-9df3-4a46203a6a6d.png)

**Comment by tristanleboss** [comment] 2019-07-13 10:55
The issue is from the code that render fields on a content page:

![image](https://user-images.githubusercontent.com/1431508/61170687-58b84380-a56d-11e9-9301-f838bb45b62a.png)

As seen on this screenshot, the `value` of the input field is wrong. We can see, the jQuery date picker is configured correctly.

**Comment by tristanleboss** [comment] 2019-07-13 11:26
**To trigger the problem, you need to use an ambiguous date like (with both day and month <= 12).**

Indeed, if you use August, 21th, the input `value` will be set correctly to `21/08/2019`. It's only wrong when you use ambiguous date.

**Comment by JoryHogeveen** [comment] 2019-08-07 11:31
@tristanleboss 

I've been unable to reproduce your issue on my local installation.
Could you please test with WP Site Health enabled (under Tools). Please only enable Pods and test again.
If the problem still occurs please share some more info about your installation:
- WP version
- Other plugins
- Browser
- PHP version
- etc.

Thanks in advance!

**Comment by tristanleboss** [comment] 2019-09-04 07:53
Hello, I will retest this next week on a fresh WP install ;)

**Comment by JoryHogeveen** [comment] 2019-09-04 08:25
Hello @tristanleboss 

Forgot this issue.
This is probably be related to a "larger" issue with date fields and has been fixed in PR #5451 
If you could also test this that would be great!

Thanks, Jory

**Closed** 2019-09-04 13:38 UTC
Labels: Status: Could not reproduce, Status: Need User Feedback, Type: Bug
