### ISSUE TITLE
the pop up does not work in wordpress 4.9.2

### ISSUE THREAD

**Issue by ronaldwu** [pods-framework/pods#4740] opened 2018-02-02 11:16 UTC
Hi Friends,

I found the advanced filter pop up failed in wordpress 4.9.2. and I know the reason is,

when we open the pods entity list page, it cannot load all css files, I don't know why it cannot load them correctly. could you help to fixing this?

Ronald

**Comment by ronaldwu** [comment] 2018-02-02 11:19
URL is : https://localhost:8080/wp-admin/admin.php?page=pods-manage-sales_order
my pods entity is sales_order,
this page have Advanced Filter anchor, but when I click it, pop up did not show up.

**Comment by ronaldwu** [comment] 2018-02-02 11:21
I only setup wordpress 4.9.2 and only installed Pods 2.7.1 plugins and components Advanced Post Type and Roles and Capabilities.

**Comment by jimtrue** [comment] 2018-02-04 04:05
Related to #4693 and #4704

**Comment by jimtrue** [comment] 2018-02-04 04:07
Closing as Duplicate of #4693 Please see that issue for resolution.

**Closed by jimtrue** 2018-02-04 04:07 UTC
Labels: Duplicate
