### ISSUE TITLE
Date Field Not Showing

### ISSUE THREAD

**Issue by swabhav** [pods-framework/pods#6300] opened 2021-11-13 10:19 UTC
I'm getting a problem with the date field showing a blank box.
getting error on pods Version 2.8.3
check the screenshot - https://prnt.sc/1xlklvf

**Comment by sc0ttkclark** [comment] 2021-11-14 04:39
Where do you see this happening? In your editor or on the front of your site?

Can you provide a package of your configuration (Pods Admin > Migrate Packages) using the Migrate Packages component (Pods Admin > Components)? That might help us to see if we can reproduce the issue.

Also helpful would be access to your Site Health information (Tools > Site Health > Info Tab > Copy site info to clipboard) would also help us determine if there are any potential conflicts from other plugins or your theme.

**Comment by JoryHogeveen** [comment] 2021-11-17 16:20
https://wordpress.org/support/topic/pods-image-field-not-working/#post-15077602

**Comment by cschoenfeld** [comment] 2021-11-17 16:36
Hi, I'm "akchas" from the wordpress.org thread. I'm attaching my Pods configuration and site health info, in the hope that it will help to diagnose the issue. Thanks! 

[Pods-issue.zip](https://github.com/pods-framework/pods/files/7556341/Pods-issue.zip)

**Comment by JoryHogeveen** [comment] 2021-11-19 11:00
@sc0ttkclark @zrothauser 
https://wordpress.org/support/topic/date-fields-not-displaying-since-upgrade/

I see a mention of only reproducible on Mac, not Windows, maybe that is why I cannot reproduce.

I do see a different error with the Time field. When the value is 00:00 it's simply not shown. This is default in HTML5 but the same thing happens with non-HTML5 fields.

**Comment by cschoenfeld** [comment] 2021-11-19 14:32
That's a useful detail! Upon further testing, Pods 2.8.5 _does_ render the date field in Chrome and Firefox. It's specifically Safari that's having the problem.

The console in Safari shows this error: "SyntaxError: Invalid regular expression: invalid group specifier name"

**Comment by JoryHogeveen** [comment] 2021-11-26 14:11
@swabhav

Could you report back on this issue. I'd like to know if 2.8.5 has the same error in your installation.

**Comment by sc0ttkclark** [comment] 2021-11-29 23:43
@zrothauser Looks like it's the same exact issue here as https://github.com/pods-framework/pods/issues/6318

**Comment by sc0ttkclark** [comment] 2022-01-22 00:31
Duplicate of https://github.com/pods-framework/pods/issues/6318

**Closed by sc0ttkclark** 2022-01-22 00:31 UTC
Labels: Type: Bug, Status: Need Research, Component: UI, Component: DFV
