### ISSUE TITLE
custom shortcodes getting broken when using {@post_content} within a pod template

### ISSUE THREAD

**Issue by code-K** [pods-framework/pods#3249] opened 2015-12-02 14:25 UTC
Hi there, anyone aware of the following problem? I'm running pods 2.5.5:

if i call anywhere within a pod-template the magic tag for "{@post_content}"
all my used "custom shortcodes" won't work anymore and just displaying as plain text...

when i remove the call to "{@post_content}", everything is just back working fine again... 
That's really strange in my eyes... Anyone has seen/heard that before and knows a solution?

Thanks so ,such for feedback and best regards,
Christian

**Comment by code-K** [comment] 2015-12-02 14:33
workaround:

for now i created my own field for the pod for the content description... and calling that within the template don't breaks my shortcodes...

**Comment by code-K** [comment] 2015-12-02 22:59
also for me it isn't working to use the special magic tags for example: {@site-url}
even that i set "PODS_SHORTCODE_ALLOW_EVALUATE_TAGS" to true.

**Comment by jimtrue** [comment] 2015-12-02 23:07
Several of the Special & dynamic Magic Tags (ie {@site-url} etc, don't work in Pods Templates. They only work in Shortcodes and Widgets.

You don't need to use {@post-content} if you're using the Auto Templates option and either before/after choices, because the Post Content is handled by default in your theme. Trying to call it again, if you are using Auto Templates will result in recursion because it's trying to re-call post-content over itself, since by default Pods Templates with Auto Templates is replacing the_content.

**Comment by pglewis** [comment] 2015-12-19 09:46
Anything to extract and an issue here?

**Comment by jimtrue** [comment] 2015-12-19 23:00
I can verify the primary issue this was referenced under. Using Special Dynamic Tags isn't allowed in Pods Templates and this is referenced directly in this article: http://pods.io/docs/build/special-magic-tags/ about where you *can* use them. We're opening a separate issue to 'whitelist' which of these can be used to display in special situations #3296.

On the issue of whether any Shortcodes stops working in a Pods Template when you also put `{@post_content}` in the template, that is correct, it outputs it as the 'code'. This doesn't work whether or not you define the constant `PODS_SHORTCODE_ALLOW_SUB_SHORTCODES` in wp_config.php to true (which you should if you want shortcodes to work **at all** in Pods Templates), so it's something else happening here.

I believe this is one of those 'bad practice' areas, calling shortcodes from within shortcodes and that could be why it doesn't work because Pods Templates will only be called in situations where:

* Called from a Shortcode on a Page in the Visual Editor
* Called within a Widget
* Called within *any* Content Editor Box on any post type (ie even a Custom Post Type), that allows shortcodes to be processed
* Called with the Auto Templates setting which replaces `the_content()` or modifies its behavior by outputting the template along with the `the_content()`, depending on the setting of *Before*, *After*, or *Replace*

We'd need @sc0ttkclark to weigh in on if this is a Best Practice rule and if we should break it or not. I also think you can call the Pods Template using the `template` function call in PHP (http://pods.io/docs/code/pods/template/) which could open up other concerns.

**Comment by Shelob9** [comment] 2015-12-19 23:06
Throwing it out there that I designed auto_templates to work with `{post_content}` magic tags. Early versions had the recursion error, but we unhooked `the_content` to make that work. If `{post_content}` doesn't work  now, this is a regression error that needs fixed.

**Comment by Shelob9** [comment] 2015-12-19 23:07
https://github.com/pods-framework/pods/blob/master/components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php#L274-L289

**Comment by jimtrue** [comment] 2015-12-19 23:14
@Shelob9  it only doesn't display the shortcode IF someone attempts to call a shortcode within the Template along with` {@post_content}` You can get the `{@post_content}` just fine, it just doesn't extrapolate any shortcodes within the Pods Template.

**Comment by Shelob9** [comment] 2015-12-19 23:27
@jimtrue Ok. I was worried that was re-broken. Recommend closing this issue as "don't do that".

**Comment by jimtrue** [comment] 2015-12-21 00:59
The concern would be why it processes the shortcode EXCEPT when you include post_content in the template.

**Comment by Kpudlo** [comment] 2016-11-06 01:42
Has there been any updates or solutions to this? I'm attempting to use a tab setup that displays only if the user is the author or if they are an editor or administrator.

**Comment by jimtrue** [comment] 2017-10-11 18:07
Also corrected, shortcodes are properly working when `{@post_content}` is included in the template. #4408 and Pods 2.7RC1

**Closed by jimtrue** 2017-10-11 18:07 UTC
Labels: Bug, Compatibility/Deprecation, Focus, Needs Research, ready, Verified/Reproduced
