### ISSUE TITLE
[BUG] deleting a field is not possible for some advanced content type pods

### ISSUE THREAD

**Issue by eeboo** [pods-framework/pods#6112] opened 2021-09-01 13:17 UTC
## Description
deleting a field from an advanced content type pods is not possible

## Testing instructions

1. Go to edit an advanced content type pods
2. delete a field and save pods (not relation field)
3. add try to add a new entry with the modified pods
4. See SQL error message indicating that the previously deleted field does not exist when trying to insert

Have you ever seen this error message? 

## Other super helpful information
the field always seems to be defined in the _transient_pods_pods_wp__pod_tableinfo entry in wordpress options table

<details>
<summary>WordPress 5.8 php 7.2</summary>
</details>

**Comment by sc0ttkclark** [comment] 2021-09-11 03:51
Do you see any difference after you go to Pods Admin > Settings > and click "Clear Pods Cache"?

**Comment by eeboo** [comment] 2021-09-11 04:59
already tested the clear pods cache with no effect

**Comment by sc0ttkclark** [comment] 2021-09-16 04:42
We'll want to retest this for Pods 2.8 as it should no longer be a problem. If you have a staging site to test on, that would be helpful for you to confirm on your side.

Follow the testing instructions at: pods.io/2021/02/11/pods-2-8-beta-1-released-and-the-field-guide-to-pods-2-8

Here's where the code is located: https://github.com/pods-framework/pods/tree/release/2.8

**Comment by sc0ttkclark** [comment] 2021-09-23 01:26
@pdclark For QA when you are able

**Comment by JoryHogeveen** [comment] 2021-09-23 12:08
@sc0ttkclark 
I cannot reproduce this error on the latest 2.8 version. However, not sure if this is intended but the field still exists in the database table after removal.

**Comment by sc0ttkclark** [comment] 2021-09-23 12:27
@JoryHogeveen where does it exist? The table column is still there?

**Comment by JoryHogeveen** [comment] 2021-09-23 12:53
Yep, table column!

**Comment by sc0ttkclark** [comment] 2021-09-23 13:57
OK then that's a bug we need to address in 2.8, I'll look into it.

**Comment by sc0ttkclark** [comment] 2021-09-27 02:39
Fixed via 209dc7bccf20f97fd0572433ff261de640a6891f

**Closed by sc0ttkclark** 2021-09-27 02:39 UTC
Labels: Type: Bug
