### ISSUE TITLE
Shortcode does not work in custom settings page and does not display after 2.7.2 update

### ISSUE THREAD

**Issue by peterluit** [pods-framework/pods#4912] opened 2018-05-06 06:21 UTC
I created the follwoing in funcyions.php in childtheme:

// Shortcode for the copyright year in footer.
function currentyear_shortcode() { $year = date('Y'); return $year; } 
add_shortcode('currentyear', 'currentyear_shortcode');

I created a custom settings Pod with a filed for diaply content in the footr (simple text field)

I inserted the code [currentyear] in the textfield. However, after updating the custom settings content the shortcodes was removed from the the textfield and (ofcourse) does not display in the frontend. In 2.7.1. this worked fine.

**Comment by pglewis** [comment] 2018-05-06 17:15
It's unclear why it may have become unset, but double-check that 'Allow Shortcodes' is still checked in "Additional Field Options" for your text field.  

It works for me with that checked but it will strip out registered shortcodes if it's unchecked.

**Comment by peterluit** [comment] 2018-05-07 05:28
Well, that did it, very strange that this option 'Allow Shortcodes' seemed off after the update.

**Closed** 2018-05-07 08:43 UTC
Labels: Needs User Feedback, Needs Verification/Reproduction

**Comment by budley** [comment] 2018-06-13 07:27
I can confirm a second instance of this happening. This caused us to lose shortcode capability when updating the PODs plugin from an old version. Not stupidly old, but maybe March this year?

Rolling back to 2.7.1 fixes the problem (although the allow shortcodes box is still unticked). 2.7.2 breaks it. Maybe 2.7.1 ignored this field and the tick box was always unset??? Our implementation using PODs has been around for a few years so the **original Custom Post Types were created years ago**.

If I can provide any more information then let me know: if accessing the site as it is (still at 2.7.1 - I'll fix next week) helps then let me know.

G

**Comment by pglewis** [comment] 2018-06-13 15:40
New issue: #5035
