### ISSUE TITLE
Client side form validation messages cannot be translated

### ISSUE THREAD

**Issue by mottolini** [pods-framework/pods#2788] opened 2015-03-09 07:21 UTC
Line 51 of pods/ui/js/jquery.pods.js is:
`$el.closest( '.pods-field-input' ).append( '<div class="pods-validate-error-message">' + label.replace( /( <([^>]+ )> )/ig, '' ) + ' is required.</div>' );`
Te only way to translate "is required" is to change this file, which is obviously not a good practice.
It would be better if there was a jquery.pods.strings-en.js file loaded client side with all the strings and a way to specify which language file should be loaded.

**Comment by Shelob9** [comment] 2015-03-09 23:10
This is a duplicate of #2645 an issue we really should fix.

**Closed by Shelob9** 2015-03-09 23:10 UTC
Labels: Duplicate

**Comment by StaggerLeee** [comment] 2015-03-13 22:04
Can you make validate error message bit more visible, stick to the eyes. I am experienced and i kept clicking "Update" button many times without noticing message. Tought first it was some JS conflict.

Wrap whole field block (with label) with error class, to give us chance to style it manually.
Or maybe use standard backend message as many other plugins do, this visible message above title field.:

- add_action( 'admin_notices'

**Comment by MilenFrom** [comment] 2017-08-17 17:00
If you want this translated without modifying the core files of pods you can do it with jQuery / JavaScript.

On the page where you want the translation include the following code and make sure you have jQuery before this code.
```

(function($){
    $(document).ready(function(){    
       $('body').on('keyup change keydown load keypress',function(){

            // Let's translate the required string
            let dstrng = $('.pods-validate-error-message').text();

            if(dstrng.includes('required')){
                $('.pods-validate-error-message').text('YOUR TRANSLATION HERE');
            }

        });
        
    });
})(window.jQuery);
```
