### ISSUE TITLE
REST API endpoint Extended Users

### ISSUE THREAD

**Issue by saulopaiva** [pods-framework/pods#3418] opened 2016-02-23 23:54 UTC
Hi, 

Using **Pods 2.6.1** and **WP REST API 2.0 beta 12**.

When enabling REST API to _**Extended User** Pods_, the pods fields of user are not shown and can not be modified using the API, even marking to show/update individually or as a whole.

**Comment by quasel** [comment] 2016-02-24 09:22
Thx for reporting and providing a solution we will take look into

**Comment by manikmagar** [comment] 2016-03-19 22:29
Is this fix available in current pods plugin?

**Comment by lougreenwood** [comment] 2016-05-19 17:42
@sc0ttkclark I'm planning on hiring a freelance developer to work on this and some other issue's we've come across which limits our use of the Pods API. We hope to create PRs for all of our fixes.

I see that this issue has a submitted fix with PR and I wondered why this fix is on hold and is not being included in any planned, upcoming releases (and has missed 3 point releases).

My concern is that any PRs my developer creates will not be merged any time soon, making it difficult to keep our patches in sync with future updates.

So my question is... is there a reason this fix was skipped for multiple releases and is currently in holding? Perhaps there's a problem with the PR that my developer can avoid repeating in our fixes?

Thanks

**Comment by sc0ttkclark** [comment] 2016-05-19 17:58
I'm ready to merge when it's tested and works as intended, that PR was assigned to @quasel though, who just needs to sign off on it from his end.

**Comment by lougreenwood** [comment] 2016-05-20 19:06
We've just added the patch that @saulopaiva submitted and it works for us too... 👍

@sc0ttkclark or @quasel - can you point me to any recent tests for the API, the API tests in /tests are 2 years old, so I'm not sure whether they're still relevant... maybe we can add a test case for this...

Thanks

**Comment by quasel** [comment] 2016-05-22 20:04
Sorry realy busy in the last time - will take a look tomrrow - and most of the code in the current version is from josh ...

**Comment by sc0ttkclark** [comment] 2016-07-29 15:59
Closed via #3516

**Closed by sc0ttkclark** 2016-07-29 15:59 UTC
Labels: Bug, ready
