### ISSUE TITLE
Backslashes removed on save

### ISSUE THREAD

**Issue by ericnormand** [pods-framework/pods#4424] opened 2017-08-17 00:29 UTC
Hello!

I'm using a Code (Syntax highlighting) field. I enter in backslashes but they are removed from the saved value. That is, if I save the field with just a \ and update the post, when the post editor loads again the field is empty. Other characters save just fine.

I'm using Wordpress 4.8.1 with Pods 2.6.10.

Thanks!
Eric

**Comment by quasel** [comment] 2018-08-31 19:34
Duplicate of #5040

**Closed by quasel** 2018-08-31 19:34 UTC
Labels: Closed: Duplicate
