### ISSUE TITLE
Role Issue

### ISSUE THREAD

**Issue by adleviton** [pods-framework/pods#2396] opened 2014-10-11 21:01 UTC
I'm having an issue where the role in question only has two capabilities - "read" and "pods_edit_offices". Offices is an advanced content type.

For this role, deleting offices is disabled, but in the admin area, delete is still appearing, see the attached image. 

Any ideas?

![role-issue](https://cloud.githubusercontent.com/assets/2176348/4604141/715c9ab8-5189-11e4-96db-0a2f23d4002e.jpg)

**Comment by sanderaido** [comment] 2015-04-22 12:33
Similar issue here. Advanced content type (called 'group') capabilities are not being applied to user roles properly. I'm actually using Pods through pods-json-api, so to give access to a user to list/view the ACT I had to give that user role a capability `pods_content` (is there a better one?), but that gives full access to the user in the admin panel to that ACT. Although there are separate capabilities like `pods_add_group` and `pods_edit_group`, no matter what I select, it either gives full access or none.

**Comment by quasel** [comment] 2015-04-22 14:56
The issue is that per default unauthorized read access isn't granted - to be honest i dont think this will be changed for pods-json-api because we started work on https://github.com/pods-framework/pods-rest-api wich will be based on wp-rest-api v2.0 any feedback/help is apreciated. 

You did it the expected way - thats what the filter is for :D

**Comment by sanderaido** [comment] 2015-04-22 15:08
When interfacing through the pods-json-api the filter is a fine solution, but this issue was about role capabilities for custom post types in general. In the admin panel this is still an issue if one wants to grant editing, but not deleting for custom post types or just viewing and not editing for ACT's etc. 

Thank for that pods-rest-api link, I will definitely look into it and give my feedback if I start another WP-JSON-like project in the future!

**Comment by quasel** [comment] 2018-09-01 08:46
Still an issue with ACT! Just tested with the great plugin from @JoryHogeveen - View Admin As! 
noticed only pods_add is funny :D and leads to an error msg after submit as you can't see any existing item ^^

**Comment by JoryHogeveen** [comment] 2020-07-14 16:27
This was fixed in #5504

> Just tested with the great plugin from @JoryHogeveen - View Admin As!

Thanks @quasel ^^

**Closed by JoryHogeveen** 2020-07-14 16:27 UTC
Labels: Status: Help Wanted, Status: Reproduced, Type: Bug
