### ISSUE TITLE
[once] tag not rendring any output

### ISSUE THREAD

**Issue by tubaad** [pods-framework/pods#3385] opened 2016-02-08 21:24 UTC
I'm asked by Jim True to report this bug.
The below html code in a Pod Template should output the text: **The first guy** for the first row of composers.
It does not.

`

<div>       
    <h4>Composer:
    [each composer]
        [once]The first guy:[/once]
        <a href="{@permalink}">{@post_title}</a>
    [/each]
    </h4>
    <p><strong>Durata:</strong> {@durata}</p>
    <p><strong>Instrumentation:</strong> {@instrumentation}</p>
<p>{@post_content}</p>
</div>

`
[once-bug data structure.txt](https://github.com/pods-framework/pods/files/122236/once-bug.data.structure.txt)

**Comment by tubaad** [comment] 2016-02-08 21:25
`<div>		
	<h4>Composer:
	[each composer]
		[once]The first guy:[/once]
		<a href="{@permalink}">{@post_title}</a>
	[/each]
	</h4>
	<p><strong>Durata:</strong> {@durata}</p>
	<p><strong>Instrumentation:</strong> {@instrumentation}</p>
<p>{@post_content}</p>
</div>`

**Comment by thermofunk** [comment] 2016-10-26 14:13
Hi tubaad, I'm having this problem too. Did you find a solution? Saludos, Martín.

**Comment by jimtrue** [comment] 2016-10-26 14:26
`[once][before][after] and [if]` do not work _within_ an `[each]` block. This is a limitation of the 'shortcode' style Template tags that prevent shortcodes from also working within an `[each]` block. This will require the overhaul of the Template system (and Template Tags) to be addressed.

If you need a workaround, pass your magic tag to your own function, ie `{@my_field,my_display_function}` and handle this within that function.  In most cases, identifying the first record is better handled with CSS anyway, using nth selectors.

**Comment by thermofunk** [comment] 2016-10-26 14:43
Hi jimtrue. I'm trying to integrate bootstrap carousel with Pods and that .active class rotate thorugh the items but needs to be there in first place to display correctly. I've tried using CSS to fix it but could not find a solution. Here is my example:

`[if tile-image]
<div id="cover-carousel" class="carousel slide" data-ride="carousel" data-interval="6000">
<div class="carousel-inner">
[each tile-image]
<div class="[once]active [/once]item">
<img src="{@tile-image._src.sml_size}"/>
</div>
[/each]
</div>
</div>
[/if]`

I'm not sure how to use a function in this case and could not find an example in the forum, maybe you can guide me?

Thanks, Martín.

**Comment by jimtrue** [comment] 2016-10-26 20:41
Unfortunately, most of that content didn't make it through. You need to wrap your code with 3 single tickets if you're going to do multiple line code blocks.

**Comment by jimtrue** [comment] 2016-10-26 20:43
Basically, the idea is that you don't need an initiating 'first' class. You can use an nth selector, ie `.carousel-list li:first` to emulate the exact same thing as adding a specific class to the first selector.

**Comment by thermofunk** [comment] 2016-10-26 20:57
Thanks for your help Jim! Cheers!

**Comment by quasel** [comment] 2018-09-01 21:57
Duplicate of #3788 collecting everything there!

**Closed by quasel** 2018-09-01 21:57 UTC
Labels: Status: Reproduced, Type: Bug
