### ISSUE TITLE
Custom taxonomy required field check happens too late

### ISSUE THREAD

**Issue by jamesgol** [pods-framework/pods#3835] opened 2016-10-27 18:09 UTC
I don't have time to investigate this right now (will later), but I just ran into it and wanted to document while still fresh.

I have a custom taxonomy created with Pods that has a required field (Relationship, simple list).  I forgot to select one when adding an entry and it properly notified me that it is a required field.  After selecting something in the field after I hit submit it said that an entry already exists with that name.

It looks like the required field validation happened after the taxonomy was created.

**Comment by quasel** [comment] 2018-09-01 22:08
Duplicate of #5031

**Closed by quasel** 2018-09-01 22:08 UTC
Labels: Status: Need Reproduction
