### ISSUE TITLE
Date Picker not in website language

### ISSUE THREAD

**Issue by Thamias** [pods-framework/pods#4966] opened 2018-05-29 13:26 UTC
## Issue Overview

Hi, I have a date picker issue that I hope you can help me with :slightly_smiling_face: I will like to display a date in Danish but when I post a date created with Pods I receive an error stating that the field named 'date'  "..was not provided in a recognizable format: 29. maj 2018".      It only work in the English version "29. May 2018"
I asked the question on slack for pods and Jim True answered the following: 
"@Mathias That sounds like a .bug report to me. But I’m fairly sure the jQuery for the Date/Timepicker should be translated."

## Expected Behavior

 

I have set wordpress up to Danish, so when I use pods I would expect the date to be shown in Danish when I use the date picker. 
![skaermbillede 2018-05-29 kl 15 18 35](https://user-images.githubusercontent.com/39734296/40660836-d9bdbd62-635a-11e8-832b-79065e8043d8.png)

I would expect to get the date as eg. "29. maj" not "29. May"

## Current Behavior

 

But when I choose a date using Danish I get this error ("dato" is Danish for date)
![skaermbillede 2018-05-29 kl 15 19 20](https://user-images.githubusercontent.com/39734296/40660945-2c219628-635b-11e8-9a31-b2521e772aec.png)

The error first goes away when I write the date in English, and of course then pods display the date in English.

## Steps to Reproduce (for bugs)

1. Have wordpress in Danish
2. Create CPT through Pods and add a date picker
3.a Create a CPT post and use date picker in Danish
4.a Get an error
3.b Create a CPT post and use date picker in English
4.b Get date in English (not Danish)

## Possible Solution

Either it is something wrong with pods or it is something that is with my wordpress, though it seem not to be a problem with wordpress as the post metadate give the posting date in Danish.

## WordPress Environment

<details>
```
Debug Information
WordPress Version: 4.9.6

PHP Version: 7.2.1

MySQL Version: 5.6.38

Server Software: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.1 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

Session Save Path: /Applications/MAMP/tmp/php

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /Applications/MAMP/htdocs/prinsensmusikkorps.dk/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Divi Child Theme

Currently Active Plugins:

CPT Layout Injector: 4.3
Divi Builder: 2.4.1
DIVI Pods Module: 1.2
Pods - Custom Content Types and Fields: 2.7.3
```
</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.3","build":1527600157},"pods":{"204919":{"id":204919,"name":"koncert","label":"koncerter","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"dato":{"id":204920,"name":"dato","label":"dato","description":"Væg dato for koncert","help":"","class":"","type":"date","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","date_type":"wp","date_format":"mdy","date_allow_empty":"1","date_html5":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_wistiacom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","date_repeatable":"0","date_format_custom":"","date_format_custom_js":""},"begynder":{"id":204921,"name":"begynder","label":"Begynder","description":"eks. kl 20:30","help":"","class":"","type":"time","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","time_type":"24","time_format":"h_mma","time_format_24":"hh_mm","time_allow_empty":"1","time_html5":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_wistiacom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","time_repeatable":"0","time_format_custom":"","time_format_custom_js":""},"sluttid":{"id":204922,"name":"sluttid","label":"Slutter","description":"eks. 23:30","help":"","class":"","type":"time","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"1","time_type":"24","time_format":"h_mma","time_format_24":"hh_mm","time_allow_empty":"1","time_html5":"0","oembed_enabled_providers_gfycatcom":"0","oembed_enabled_providers_icloudcom":"0","oembed_enabled_providers_mesh":"0","oembed_enabled_providers_sketchfabcom":"0","oembed_enabled_providers_wistiacom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","time_repeatable":"0","time_format_custom":"","time_format_custom_js":""}},"show_in_menu":"1","label_singular":"koncert","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"koncert","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_project_category":"1","built_in_taxonomies_project_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"}}}
```

**Comment by quasel** [comment] 2018-08-31 10:51
Sorry for the late reply - yes could reproduce that! (applies to all non English settings I tested)

**Comment by quasel** [comment] 2018-08-31 11:30
Duplicate of #5038 - just found another issue for it!

**Closed by quasel** 2018-08-31 11:30 UTC
Labels: Closed: Duplicate, Component: UI, Status: Reproduced, Type: Bug
