### ISSUE TITLE
Narrow Modal

### ISSUE THREAD

**Issue by pd-cm** [pods-framework/pods#6996] opened 2023-01-23 19:52 UTC
### Description

See https://wordpress.org/support/topic/dialog-for-new-pod-in-relationship-is-very-narrow/ for issue and suggested CSS.

@sc0ttkclark 

### Version

2.9.11

### Testing Instructions

1. Have a big monitor.
2. Open a relationship modal.
3. Profit?

### Possible Workaround

See CSS in the linked .org posting.

**Comment by JoryHogeveen** [comment] 2023-01-26 15:43
@pd-cm 

As mentioned on wp.org:

Could you verify that this also happens with all other plugins disabled on a default theme?
I cannot reproduce this behavior locally.

Cheers, Jory

**Comment by sc0ttkclark** [comment] 2023-02-20 00:41
Fixed via https://github.com/pods-framework/pods/commit/0ba8c42f9380a2eebff30d232e1267f9407fa779

**Closed by sc0ttkclark** 2023-02-20 00:41 UTC
Labels: Status: Need User Feedback, Status: Need Reproduction, Component: CSS, Component: DFV

**Comment by sc0ttkclark** [comment] 2023-02-20 00:44
I was able to reproduce this with the Pages add new button for the kitchen sink CPT pod. I don't remember seeing that issue before but perhaps it's an issue on Classic Editor only.

**Comment by JoryHogeveen** [comment] 2023-03-09 07:31
@sc0ttkclark I'm able to reproduce this behavior with the Gutenberg plugin enabled. It seems that this plugin is adding more general CSS than WP core does.

**Comment by JoryHogeveen** [comment] 2023-03-09 20:31
@sc0ttkclark I've checked the patch and this would fix the issue. It was more a comment for additional context :)
