### ISSUE TITLE
Un-abandon the Packagist entry

### ISSUE THREAD

**Issue by GaryJones** [pods-framework/pods#5030] opened 2018-06-10 21:39 UTC
**Describe the bug**
https://packagist.org/packages/pods-framework/pods is marked as Abandoned, which doesn't appear to be the case.

**Expected behavior**
The package not to be marked as abandoned, so that folks can use it as a dependency to their site, and not have it be flagged in Composer:

![screenshot 2018-06-10 22 37 47](https://user-images.githubusercontent.com/88371/41206640-fb5b074c-6cfe-11e8-81f2-79b624cd3c80.png)

**Comment by quasel** [comment] 2018-08-31 18:50
Confirmed ;)

**Comment by quasel** [comment] 2018-08-31 21:28
workaround #4774

**Comment by pglewis** [comment] 2018-08-31 21:40
I'm not really a composer users so I'm wondering if there is an advantage to doing this rather than just cloning the Pods repo.  Maintaining the composer package is One More Thing(TM), so looking to understand the value doing so provides.

**Comment by GaryJones** [comment] 2018-09-01 06:42
There are many advantages to using Composer but version resolution is the biggest, since it's a dependency manager.

There's really nothing to maintain - just tell Packagist the package is not abandoned, and ensure that it's hooked up to auto-update when a new release is made here.

For me, I have a site repo, which is basically a `composer.json`, and a few other basic files (`.editorconfig`, `favicon.ico`, `.gitignore` etc.). In that, I list my dependencies, such as [WPStarter](https://wecodemore.github.io/wpstarter/) (others prefer the more popular [Bedrock](https://roots.io/bedrock/), and then my plugins such as Yoast SEO, Pods, and a theme like Genesis.

Upon `composer install`, these dependencies are pulled from Packagist (for package that already support Composer), [WPackagist](https://wpackagist.org/) (for free plugins that don't support Composer), and a private [SatisPress](https://github.com/cedaro/satispress) install (for premium plugins and themes). The install process puts everything into the correct directory, and sets up `.env` files for all of the environment variables.

I'd _super_ **strongly** urge that Composer support be maintained. You may not use it, but it's powerful and well used within the community.

**Comment by pglewis** [comment] 2018-09-03 01:57
> I'd super strongly urge that Composer support be maintained. You may not use it, but it's powerful and well used within the community.

It ain't _that_ tough a sell, I was just looking to understand because I was completely ignorant.

**Comment by pglewis** [comment] 2018-09-06 20:48
I believe only @sc0ttkclark has the power.  I think this is managed via packagist.org and I never even had an account there until today.

**Comment by sc0ttkclark** [comment] 2018-09-06 20:51
I thought this was already set up for composer so that’s our bad there. We’ve been using the package.json for years now and thought it just worked.

Will get the status updated.

**Comment by GaryJones** [comment] 2018-09-07 08:13
Once you've hooked the accounts, up, there's a grey "Un-abandon" button that needs to be selected:

![screenshot 2018-09-07 09 12 41](https://user-images.githubusercontent.com/88371/45206908-3cc58080-b27e-11e8-9dc9-93e831412cf3.png)

**Comment by sc0ttkclark** [comment] 2018-09-09 17:48
They transferred the package to my sc0ttkclark account, I added pglewis as another maintainer too. After review, I can confirm that the versions that pull in are only the tags without `2.x/` and `1.x/` prefixes. As a result, only versions going forward from 2.7.9+ will be available in Packagist, but I doubt that's going to be a problem.

I looked into doing mass renaming of the tags, but it meant that every single 'release' would have to be created for those new tags (it adds the new tag, then removes the old tag) and we'd lose all the changelogs we archived into GitHub there. I think the 2.7.9+ solution will be fine.

I had to archive the `release/3.0-pre-cmb2` branch because of a composer package definition error, it's now tagged at https://github.com/pods-framework/pods/releases/tag/archive%2F3.0-pre-cmb2 (for my reference, since I'll be referencing some of this 3.0 stuff for Groups in 2.8)

**Closed** 2018-09-09 17:48 UTC
Labels: Status: Need Dev Feedback, Status: Reproduced, Type: Bug
