### ISSUE TITLE
Could not install pods 2.7.1 using composer

### ISSUE THREAD

**Issue by distributev** [pods-framework/pods#4774] opened 2018-03-01 11:39 UTC
I tried to install pods 2.7.1 using composer and it failed with

![image](https://user-images.githubusercontent.com/19224635/36842848-43c09116-1d4d-11e8-9188-91974e940f0e.png)

Further more if I go to composer pods page it says 

This package is abandoned and no longer maintained. No replacement package was suggested.

https://packagist.org/packages/pods-framework/pods

This is what I have in composer.json file

 "require": {
    "php": ">=5.6",
    "composer/installers": "^1.4",
    "pods-framework/pods": "2.7.1"
  }

**Comment by distributev** [comment] 2018-03-01 11:49
If other people are interested just after I raised this issue I actually managed to install pods 2.7.1 using composer from https://wpackagist.org

I have this in composer.json

 "repositories":[
        {
            "type":"composer",
            "url":"https://wpackagist.org"
        }
    ],
    "require": {
        "wpackagist-plugin/pods": "2.7.1"
    }

**Comment by quasel** [comment] 2018-08-31 21:28
Duplicate of #5030

**Closed by quasel** 2018-08-31 21:28 UTC
Labels: Closed: Duplicate
