### ISSUE TITLE
Pods Form Shortcode Errors on POST 2.7 Update

### ISSUE THREAD

**Issue by squeezeboxhuf** [pods-framework/pods#4618] opened 2017-12-07 09:19 UTC
I have a few pages that use the Pods Form shortcode to enable adding content via my front-end, however since the update to 2.7 they no longer submit successfully. I just get a modal dialog window stating: "Error: Unable to process request, please try again."

**Comment by quasel** [comment] 2017-12-07 10:24
Sound similar to http://www.siedepunkt.de/level-up/&action=pods_admin  where it leads to a 404 we need a bit more information - e.g the link, your setup,

For the time being do you have an staging environment to test the stuff and can rollback your live site to 2.6.x? Maybe you could provide a login for @pglewis to investigate? 

You could try:
- resave WP Permalinks
- clear pods cache
- enable WP_DEBUG and look for errors popping up

**Comment by squeezeboxhuf** [comment] 2017-12-07 11:07
I've rolled back to 2.6.10 and it's back OK for now. I have another site where I am running 2.7 (no forms), and have set up a test page that will create a basic pod item. Have a look at http://www.chainoffools.co.uk/test-pods-form/

The page just has the shortcode [pods-form name="throwaway" fields="post_title, field1"] on it. When you submit the form the plain dialogue pops up Error: Unable to process request, please try again.". No pod is created.

I get no errors added to the debug.log. I've cleared PODS cache, and saved the permalinks settings.

The javascript console shows an error accessing http://www.chainoffools.co.uk/test-pods-form/&action=pods_admin

**Comment by sc0ttkclark** [comment] 2017-12-07 14:25
Sounds like the same issue, duplicate of that other one?

**Comment by jimtrue** [comment] 2017-12-07 15:46
Verified, easy test. Just add a form shortcode with `fields="post_title"`. It will error on submit. with the same 404 not found error against `&action=pods_admin`

Here's the full details from the Javascript console
<img width="1220" alt="screenshot 2017-12-07 10 45 45" src="https://user-images.githubusercontent.com/3052875/33723914-ed8d5f2a-db3b-11e7-96ef-907748c28f7f.png">

**Comment by pglewis** [comment] 2017-12-07 17:42
This was introduced here: https://github.com/pods-framework/pods/pull/4574

**Comment by pglewis** [comment] 2017-12-07 18:38
#4623 should resolve this

**Closed** 2017-12-08 04:55 UTC
Labels: BLOCKER, Bug, Fixed / Needs Testing, Verified/Reproduced
