### ISSUE TITLE
Date Modified filter not working as expected

### ISSUE THREAD

**Issue by andymakesglasses** [pods-framework/pods#2941] opened 2015-05-15 13:41 UTC
Since upgrading to 2.5.2 the Date Modified filter in the back end doesn't seem to be doing it's job properly. Clicking it seems to list the oldest items first (rather than the most recently modified) and clicking it again doesn't reverse the order.

**Comment by sc0ttkclark** [comment] 2015-05-15 15:24
Duplicate of #2843

**Closed by sc0ttkclark** 2015-05-15 15:24 UTC
