### ISSUE TITLE
Saving pods Doesn't apply changes.

### ISSUE THREAD

**Issue by NiketMalviya** [pods-framework/pods#5272] opened 2019-01-16 18:15 UTC
## Issue Overview
I try to change a setting in Pods but it doesn't appear after saving it.

## Expected Behavior
When changing any settings, say add a field to a pod in the Edit Pods setting and clicking Save Pod, The page should refresh and show the newly made changes. 

## Current Behavior
After adding field and clicking save pod, the page refreshes without the changes.
When trying to repeat the changes, it shows an error that the field with this slug already exists, however, there is no such field appearing in the list of fields in the pod

## Steps to Reproduce (for bugs)

1. .In WordPress dashboard, go to the Pods Admin> Edit Pods
2. Clicking on the pod I wish to edit(or clicking the 'Edit' option under the pod)
3. Adding a field to the Pod. Saving field and Saving Pod. 
4.*Changes Don't Appear*
5. Re-add the same field with same settings. Save Field and click on Save Pod
6. Error appears showing that field already exists
![1 adding field](https://user-images.githubusercontent.com/46757891/51269264-0ea03c00-19e8-11e9-8aff-521e2e234f6f.jpg)
![2 saving field](https://user-images.githubusercontent.com/46757891/51269265-0f38d280-19e8-11e9-9401-9457e1ff4e40.jpg)
![3 saving pod](https://user-images.githubusercontent.com/46757891/51269266-0f38d280-19e8-11e9-8d40-e6e65d48437d.jpg)
![4 pod saved page refresh no visible changes](https://user-images.githubusercontent.com/46757891/51269267-0fd16900-19e8-11e9-9282-aa7b5e500650.jpg)
![5 re-adding field](https://user-images.githubusercontent.com/46757891/51269269-0fd16900-19e8-11e9-9788-8a24affdcddd.jpg)
![6 error message](https://user-images.githubusercontent.com/46757891/51269270-0fd16900-19e8-11e9-90eb-cb17e818a11c.jpg)

## Pods Package Export (helpful!)
Uploading the export as Pods json.txt
[pods json.txt](https://github.com/pods-framework/pods/files/2765503/pods.json.txt)

## Related Issues and/or PRs
On a previous occasion, I tried to enable the Archive templates for my pods from the Edit Pods> Pod name(Edit)> Advanced Options > Clicking the 'Enable Archive Page, but it yeilded similar resuls. I tried for several days, tried asking for help from Slack community, Jim adviced to post a bug report on Github. I did not know how, but next day, it automatically showed the settings. I think these issues are totally related.

## WordPress Environment

<details>
```
Debug Information
WordPress Version: 5.0.3

PHP Version: 7.1.26

MySQL Version: 5.6.40

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: No
WPDB Prefix: klec_11_

WP Multisite Mode: Yes

WP Memory Limit: 128M

Current Memory Usage: 21.493M

Current Memory Usage (real): 24.000M

Pods Network-Wide Activated: No

Pods Install Location: /home/swudzasa/public_html/kalaeco.com/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Astra

Currently Active Plugins:

Accelerated Mobile Pages: 0.9.97.24
Advanced Ads: 1.10.12
Antispam Bee: 2.9.0
Anywhere Elementor: 1.1
Astra Pro: 1.6.11
Bulk Move: 1.3.0
Caldera Forms: 1.7.6
Ele Custom Skin: 1.0.9
Elementor: 2.4.1
Elementor Addons & Templates - Sizzify Lite: 1.2.9
Elementor Pro: 2.3.1
Give - Donation Plugin: 2.3.1
Google Tag Manager for Wordpress: 1.9
Inline Related Posts: 2.2.1
iThemes Security: 7.2.0
ManageWP - Worker: 4.6.3
OneSignal Push Notifications: 1.16.9
Pods - Custom Content Types and Fields: 2.7.12
Pretty Links: 2.1.7
Regenerate Thumbnails: 3.1.0
SEOPress: 3.3.6
SG Optimizer: 5.0.13
Sidebar Manager: 1.0.2
Super Socializer: 7.12.6
Swudzy Custom Code Plugin:
WP Migrate DB: 1.0.8
WP YouTube Lyte: 1.7.5
Yoast SEO: 9.4
```
</details>

**Comment by quasel** [comment] 2019-03-25 20:57
sounds like a caching issue or maybe something else weird is going on - couldn't reproduce it on my end - Maybe use https://wordpress.org/plugins/health-check/ deactivate all other plugins and use a default theme - sorry for the late reply!  Going to close the issue - feel free to comment again!

**Closed by quasel** 2019-03-25 20:57 UTC
