### ISSUE TITLE
"Required Field" error messages returned when they should NOT be

### ISSUE THREAD

**Issue by jawhalen8463** [pods-framework/pods#5851] opened 2020-10-10 18:26 UTC
## Issue Overview
Errors about required fields are being returned by form submit (even if the field is NOT on the form and IS present.) Also affects the pods->save function. This is a MAJOR bug in the current release!

**Comment by JoryHogeveen** [comment] 2020-10-13 08:22
Hello @jawhalen8463 

Since this bug report isn't complete I'm closing it as invalid.
Please open a new bug report and provide is with all the information on how to reproduce this issue.

Also, please explain exactly where you get these errors. For example, PHP, Rest API, WP Admin, somewhere else?
And third, please also make sure that this also happens with only Pods enabled.

We'd gladly want to help and fix this but we need the information asked when adding a bug report!
https://github.com/pods-framework/pods/issues/new?template=bug_report.md

Thanks! Jory

**Closed by JoryHogeveen** 2020-10-13 08:22 UTC
Labels: Type: Bug

**Comment by jawhalen8463** [comment] 2020-10-13 21:14
Seriously? What else do you need. This happens everywhere! If you are attempting to update ANY post, and there is a required field in it that already has data in it BUT your updating different fields, you get an error... STILL!! This is affecting ALL of your clients. THis is YOUR software - you should want to fix this!!! Don't give us too much red tape to jump through or we wont report anymore!

**Comment by jimtrue** [comment] 2020-10-13 22:49
@jawhalen8463 We are not asking you to jump through hoops. We're asking you to provide a bare minimum of details so we can replicate the issue you're experiencing. We are not experiencing this in a widespread way across our Pods ecosystem, so that leads us to the conclusion it may have something to do with your particular configuration.

We want to help you get this corrected and if you are also willing to work with us to help get the issue corrected, you will please provide us what we've asked for so we can properly work your bug report. There is a reason we request what we request on bug reports, so we can work efficiently and quickly to help get to the root of your issue.
