### ISSUE TITLE
pods() returning wrong Pod when using where parameter

### ISSUE THREAD

**Issue by paddelboot** [pods-framework/pods#5148] opened 2018-09-06 21:05 UTC
**Describe the bug**

        $where = ' t.projekt_id = 25';

        $params = array(
            'where' => $where,
            'limit' => 1
        );
        $PodObject = \pods( $Pod, $params );

Returns the Pod where the projekt_id is `25abc`.

**To Reproduce**
See above

**Expected behavior**
Treat where clause like the MySQL equivalent, ie. `=` operator, seems to be used similar to a  MySQL `LIKE` ?

**Screenshots**

## Pods Version
Please provide the version of Pods you are running: 

## WordPress Environment

<details>
```
WordPress Version: 4.9.8

PHP Version: 7.2.9-1+ubuntu16.04.1+deb.sury.org+1

MySQL Version: 5.7.23

Server Software: Apache/2.4.34 (Ubuntu)

Your User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: Yes
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: No
    Memcached: No
    Redis: No

WPDB Prefix: nx24_2_

WP Multisite Mode: Yes

WP Memory Limit: 64M

Pods Network-Wide Activated: Yes

Pods Install Location: /media/Entwicklung/Entwicklung.xxx/www/v2/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: xxx Interface Theme

Currently Active Plugins:

    xxx Interface: 0.8.3Beta
    Pods - Custom Content Types and Fields: 2.7.9
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Additional context**

**Possible Workaround**
If you have discovered a workaround, please include it below.

**Comment by quasel** [comment] 2018-09-06 21:41
Hi we don't change the comparison it's stay `=`  

`projekt_id` is what type of field? depending on the type I think you need a different where clause -> https://pods.io/docs/code/pods/find/ at the bottom is full comparison table 

it always helps to give some context
in weird cases like that a look at -> $wpdb->last_query can help too or if you output pods stuff on a page just add ?pods_debug_sql=1 to see the query

**Comment by paddelboot** [comment] 2018-09-07 11:49
> projekt_id is what type of field? 

A simple text field at the moment.

> in weird cases like that a look at -> $wpdb->last_query can help too or if you output pods stuff on a page just add ?pods_debug_sql=1 to see the query

I will do that and see if I can get some more insight into what the query is doing.

**Comment by quasel** [comment] 2018-09-10 12:13
Any update? as in a quick test I didn't seem to be able to reproduce your issue?

**Comment by JoryHogeveen** [comment] 2020-09-01 14:05
Closing this issue due to no reply.

**Closed by JoryHogeveen** 2020-09-01 14:05 UTC
Labels: Status: Need User Feedback, Type: Support
