### ISSUE TITLE
Pods Plugin not allow Creating a new Content Type  from WordPress admin panel.

### ISSUE THREAD

**Issue by asadpk** [pods-framework/pods#4936] opened 2018-05-16 13:20 UTC
Debug Information
WordPress Version: 4.9.5

PHP Version: 7.1.16

MySQL Version: 5.5.5

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: www_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /customers/d/d/8/kagetilbud.com/httpd.www/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Freelanceengine Child

Currently Active Plugins:

AE PayuMoney: 1.2.1
JE PayuMoney: 1.0
Pods - Custom Content Types and Fields: 2.7.3
Slider Revolution: 5.4.7.2
Visual Composer Website Builder: 2.3
WP Mail SMTP: 1.2.5

![screenshot_10](https://user-images.githubusercontent.com/8647171/40119298-ba67eff2-5935-11e8-9bd8-6aeec932f7f9.jpg)

I am not able to create new post types. when I check I see these errors in the browser console.

JQMIGRATE: Migrate is installed, version 1.4.1
pods-file-uploader.js:22 Uncaught TypeError: Cannot read property 'extend' of undefined
    at pods-file-uploader.js:22
    at pods-dfv.js:81

**Comment by jimtrue** [comment] 2018-05-18 16:38
@asadpk It looks like you've got a conflict of some kind with another plugin using Select2. To troubleshoot, disable other plugins except for Pods and see if you're able to work, and then re-enable each plugin until you find the guilty party. Then we can help you with a workaround there.

**Comment by pglewis** [comment] 2018-05-21 22:18
I see this is a FreelanceEngine theme, closing as a duplicate of #4717

**Closed by pglewis** 2018-05-21 22:18 UTC
Labels: Needs User Feedback
