### ISSUE TITLE
If block doesn't properly test and process shortcodes and captions

### ISSUE THREAD

**Issue by Sheriziya** [pods-framework/pods#2853] opened 2015-04-19 21:29 UTC
Hi,

I've posted this in the forum already (http://pods.io/forums/topic/deprecated-pod-template-with-auto-frontier/), but I thought I'd mention it here too to have it listed in the bugs as I understand from Scott's response this might be a bug.

In my portfolio I need to test if certain fields have something in it and only when something is in it, the data needs to be displayed. So I do this with the if block. This works good if the field is empty. But, when the field is NOT empty, the if block doesn't properly handle the shortcode nor the caption code (which I assume is also in a way a shortcode). When the field is NOT empty it prints the shortcode instead of processing it.
Maybe it's something specific to how I build it. I've used a WYSIWYG field in the POD and in the Advanced options of that field, I've checked all options, including "allow shortcodes".

The code for shortcode I use, is:
![templatecodeshortcode](https://cloud.githubusercontent.com/assets/3530524/7230067/b6942ec6-e76a-11e4-8a00-048cefba1724.png)
(I couldn't find a way to properly add the code here, so I made a screenshot of it instead).

The result:
![shortcodeprintedinsteadofprocessed](https://cloud.githubusercontent.com/assets/3530524/7230080/d8b688b4-e76a-11e4-8da1-f3b682886f81.png)

As you can see there is a shortcode. It should be processed, but instead it's being printed.

Also, I have noticed the If block doesn't process the caption for images. Again, I've used a WYSIWYG field (other field than the field for the shortcode I was using), checked all the options (including "allow shortcodes") in the advanced tab.
The code I used for this particular field:
![codewithwysiwyg-captionproblem](https://cloud.githubusercontent.com/assets/3530524/7230169/97618e30-e76b-11e4-8477-7a08c65019b9.png)

Here's the result with the if block test:
![ifblockcanthandlecaptioncode](https://cloud.githubusercontent.com/assets/3530524/7221448/b514f1cc-e6eb-11e4-8a7f-c0261761bf10.png)

Here's what it should look like if the if block would test and process it correctly:
![ifblockresultasitshouldbewithcaption](https://cloud.githubusercontent.com/assets/3530524/7221455/d8e1db92-e6eb-11e4-810e-96fddbde3162.png)

Oh, I was first aware of this particular problem with Pods Version 2.5.1.2 and Pods Frontier Auto Template Version 1.1.2 If I interpret Scotts response in my above linked forum topic correctly, this bug is related to PODS itself and not the Frontier Auto Template. I thought I'd mention I use both just to be complete.

I hope a solution to this problem/bug can be found.

Thanks for looking into it!

**Comment by sc0ttkclark** [comment] 2015-04-23 07:11
@Desertsnowman related to what we were discussing the other day.

**Comment by Sheriziya** [comment] 2015-04-23 16:06
Heya,

A few questions, hope you don't mind :) : 
* What does "Bug: Regression" mean? I'm trying to get familiar with the Github, hence my question :)
* Is there anything I need to / can do to help?

I've been looking into the source files, but unfortunately I don't know enough about them to have any idea where to start looking for this particular issue and see if I can find a solution.

Thanks for the help!

**Comment by jimtrue** [comment] 2015-04-27 12:43
Bug: Regression means that a later patch 'regressed' (or broke) a patch/fix/feature that was working earlier.

**Comment by Sheriziya** [comment] 2015-04-27 12:47
Thanks @jimtrue !

**Comment by Sheriziya** [comment] 2015-06-13 16:01
Awww too bad. I had hoped this would be fixed in Pods 2.5.3 :(
Looking forward to the solution in Pods 2.5.4 now.

**Comment by saulolago** [comment] 2016-10-27 23:22
Hello @Sheriziya 
I know it's been a long time, but recently had the same problem and managed to solve the following:

`

	$slug = pods_v( 'last', 'url' );

	$params = array( 'where' => 'permalink = "'.$slug.'"' );
	
	$pods = pods( 'noticias', $params );
	if ( $pods->total() > 0 ) {

		while ( $pods->fetch() ) {
		
			$title = $pods->display('name');
			$texto = $pods->display('texto');
			
			function get_the_content_with_captions ($texto) {
				$texto = apply_filters('the_content', $texto);
				$texto = str_replace(']]>', ']]>', $texto);
				return $texto;
			}
			
			$html .= "<div class='title'>".$title."</div>";
			$html .= "<div class='text'>".get_the_content_with_captions($texto)."</div>";
			
			echo $html;
			
		}
		
	}`

The code that I used to solve the problem was this:

`function get_the_content_with_captions ($texto) {
$texto = apply_filters('the_content', $texto);
$texto = str_replace(']]>', ']]>', $texto);
return $texto;
}`

from that code you can have a base to go and solve your problem.

**Comment by jimtrue** [comment] 2017-10-11 18:04
Validated both of these conditions are fixed by #4408 and Pods 2.7 RC1

**Closed by jimtrue** 2017-10-11 18:04 UTC
Labels: Backward Compatibility, Bug, Focus, Needs Contributor, Verified/Reproduced
