### ISSUE TITLE
form() with just post_title, saves, but the data on subsequent refresh is the same

### ISSUE THREAD

**Issue by benfavre** [pods-framework/pods#1691] opened 2013-09-08 20:10 UTC
form() with just post_title, saves, but the data on subsequent refresh is the same, unless you pass post_name empty hidden field so it generates a new post_name

**Comment by GaryJones** [comment] 2018-06-10 21:41
@benfavre A little late in replying...

Is this still an issue? If so, can you please be more specific in what the problem is? What `form()`? Do you have an export of a setup where this issue is happening? Can you add screenshots / screencast of the problem?

If not, please close the Issue.

**Comment by benfavre** [comment] 2018-06-10 23:27
Looking at this it seems i was facing issues clearing the form class cache or maybe a metabox transient.
Pretty sure there are still issues with using this class directly as there is no easy interface to clear transients for forms or metaboxes.

**Comment by GaryJones** [comment] 2018-06-11 07:27
There appears to be 7 methods called `form()` throughout Pods.

_Please_ be specific about what the issue _is_, rather than where you think the solution lies. What are you actually trying to do? Provide screenshots. Treat me as though I've never used Pods before and give a _detailed_ explanation so that anyone can try and reproduce the bug :-)

**Closed as completed** 2018-09-01 11:21 UTC
Labels: Type: Bug, Status: Need User Feedback
