### ISSUE TITLE
2.7 RC1: Search (in a Settings pod) doesn't work with a list greater than 30

### ISSUE THREAD

**Issue by corypina** [pods-framework/pods#4505] opened 2017-10-10 21:14 UTC
Possibly connected to #1259 and #4504.

I'm testing a few custom settings, both multiple-select. When using the *Autocomplete* or *List view* formats, the autocomplete doesn't show any possibilities when the total number of possibilities is greater than 30.

## Example
I have a setting to select multiple users from the user base on the site. Here is what it looks like when I have 30 or less registered users:

![30-users](https://user-images.githubusercontent.com/1993354/31410405-5b8e850e-adc3-11e7-9651-b09fe2c49b2f.jpg)

When I add the 31st user, I get this:

![more-than-30](https://user-images.githubusercontent.com/1993354/31410427-6975657a-adc3-11e7-8888-318c1e92fa13.jpg)

... And no matter what I type in there, I get no results.

If I happen to know the exact result I'm looking for, type it in, and hit Enter, I'll get the addition, but with a blank entry:

<img src="https://user-images.githubusercontent.com/1993354/31410601-f073e056-adc3-11e7-8bf2-ea75e3f9eb4c.jpg" width="400">

If I refresh the page, the name will be there:

<img src="https://user-images.githubusercontent.com/1993354/31410758-31e608d4-adc4-11e7-8ccf-11cc0c9e3494.jpg" width="400">

## Other Notes
- I've tested this both with Users and ~~Posts~~. Same result for both. **(UPDATE: Posts are fine. Users seem to be the only problem.)**
- 30 seems to be the magic number. Results are ok below thirty, and I've gone as high as almost 9,000 users

**Comment by pglewis** [comment] 2017-10-10 22:01
30 is the limit that currently kicks-in "ajax mode" for autocomplete and list view.  Lists could be arbitrarily large so we can't always load them all, for performance reasons.  

We should have worked out the kinks in #4388, a lot of testing of the ajax mode was done to resolve that one.  I would check your dev tools/firebug console and see if there are any clues there, if there are more than 30 records you should see an ajax request after a few keystrokes.

**Comment by corypina** [comment] 2017-10-10 22:28
@pglewis The limit makes sense.

With 31 possible users to be searched, I'm not seeing anything in the autocomplete list, or in the console, when I type a known user.

![screen shot 2017-10-10 at 3 22 08 pm](https://user-images.githubusercontent.com/1993354/31413630-0fc025cc-adcf-11e7-89ac-29ca68a9583a.jpg)

Same search, with only 30 users in the system:

![screen shot 2017-10-10 at 3 27 26 pm](https://user-images.githubusercontent.com/1993354/31413723-a18ef8a2-adcf-11e7-96d6-b3f52fdf6add.jpg)

**Comment by pglewis** [comment] 2017-10-10 22:29
Check the "Network" tab, you can filter by XHR to see just ajax requests.

**Comment by corypina** [comment] 2017-10-10 22:50
Results under Network (filtered XHR):
I typed a few letters, waited a second, then finished typing.

![screen shot 2017-10-10 at 3 48 11 pm](https://user-images.githubusercontent.com/1993354/31414419-a71e95ae-add2-11e7-8999-2439dcf8c688.jpg)

**Comment by pglewis** [comment] 2017-10-10 23:04
I can't reproduce it with a relationship to Post, I'll test with users to see if that turns anything up.  

![ajax-autocomplete](https://user-images.githubusercontent.com/1973916/31414850-d97e4a9c-aded-11e7-896c-3f8a4b9bde7d.png)

**Comment by corypina** [comment] 2017-10-10 23:21
Same here. It's working on posts for me. Just not users.
I initially indicated the issue with both Posts and Users, but probably lumped in Posts because of the way the autocomplete list was behaving. Will update the initial issue.

**Comment by pglewis** [comment] 2017-10-11 01:10
PR: #4506

Should work for users at the least

**Comment by pglewis** [comment] 2017-10-11 15:21
Merged into the 2.7 branch and should be good now.  Re-open or start a new issue as appropriate if there is anything lingering.

**Closed by pglewis** 2017-10-11 15:21 UTC
Labels: Bug, Fixed / Needs Testing
