### ISSUE TITLE
WP with PODS and WPML

### ISSUE THREAD

**Issue by aleix10kst** [pods-framework/pods#3870] opened 2016-12-01 13:03 UTC
Hello, We've recently upgraded a  WP to 4.6.1 and we are using PODS (2.6.7) and WPML(2.8.2).
What we've discovered is that all multilingual content is displayed in all languages. 
Before the upgrade to 4.6.1, it worked. 

What we've also noticied is that it has happened to more sites that have been upgraded to 4.6.1. 
WPML support asked me to post a log file so they could see if there were any problems.
http://pastebin.com/tfW3h1dy
You can see there is a problem with WPML but not sure if this is the problem why this has stopped working. 

Thank you.

**Comment by jimtrue** [comment] 2016-12-01 13:15
@JoryHogeveen Can you look into this one? Maybe pull in @srdjan-jcc to see if there's something solely with WPML or if there's something with WPML and Pods.

**Comment by srdjan-jcc** [comment] 2016-12-02 14:19
@aleix10kst Can you please check if following is enabled?
WPML > Languages > Adjust IDs for multilingual functionality

![pods-issue-1](https://cloud.githubusercontent.com/assets/3109112/20837024/74f318c8-b8a2-11e6-98aa-224844594173.png)

**Comment by aleix10kst** [comment] 2016-12-05 08:12
@srdjan-jcc It was disabled, but I've enabled it and now it "works". All translated content appears as it has to do it while untranslated content doesn't.

**Comment by srdjan-jcc** [comment] 2016-12-06 13:49
@aleix10kst By untranslated content you mean posts in original language, right?
If posts are not translated - it's expected they appear only on page in language assigned to them.
Is that the case?

**Comment by jlami** [comment] 2016-12-09 12:10
We actually have the same problem, but we had Adjust IDs for multilingual functionality disabled by design. Our theme does all the necessary id adjustments itself, so enabling that option would only increase the db usage. We now have a problem with getting the terms via `pods('taxonomyname')` as this will return all the terms and not filter by language. While the WP counter part `get_terms('taxonomyname')` does the correct WPML filtering.

I think your condition to enable/disable WPML is too strict. The `apply_filters( 'wpml_setting', true, 'auto_adjust_ids' )` is not always the correct way. WPML itself also hooks into `terms_clauses` filter to alter the normal WP query. For pods to do the same you need to get the current language and add the sql filter for taxonomy queries. (But maybe not for single entry lookups, as that would require auto_adjust_ids)

**Comment by dangson** [comment] 2016-12-13 05:40
I'm experiencing the same problem. The basic code snippet below should return 3 for just the current language, but instead it's returning 6 since I have two languages.

```
$productTypes = pods('Product Types', array('limit' => -1));
echo $productTypes->total_found();
```

The results are the same with Adjust IDs on or off.

**Comment by srdjan-jcc** [comment] 2016-12-16 15:00
Sorry for late reply and thank you for feedback :)

@jlami I understand. Do you think Pods should not check for auto_adjust_ids and always filter query?

@dangson I tested your query and worked as expected.
Please see following test results and suggest testing scenario if I missed something.

I tested Pods tags/2.x/2.6.7 (git) and WPML 3.6.2 (latest official release)
with scenarios I assumed (Product Types are custom taxonomies). Tested with custom post type 'product' and taxonomy 'product_type', 3 original pods and 2 translations (for both post types and taxonomies).

In all cases query is filtered correctly
- auto_adjust_ids
-- on - Filtered
-- off - Not filtered
- WPML language preference for pods
-- Translatable - Filtered
-- Not translatable - Not filtered (expected)

Setup

1. Create pods, add posts and taxonomies
2. Set pods to be translatable on WPML >Translation Management > Multilingual Content Setup screen
3. Create translations for pods posts and taxonomies

Please see screenshots.

<img width="581" alt="screenshot at dec 16 15-22-02" src="https://cloud.githubusercontent.com/assets/3109112/21266962/951e7cc6-c3a8-11e6-9801-0bff640bf355.png">
<img width="578" alt="screenshot at dec 16 15-22-20" src="https://cloud.githubusercontent.com/assets/3109112/21266969/956051aa-c3a8-11e6-8ec2-d329dcd02cdd.png">
<img width="307" alt="screenshot at dec 16 15-22-57" src="https://cloud.githubusercontent.com/assets/3109112/21266966/9555f854-c3a8-11e6-878e-b9cdeb3b9a37.png">
<img width="307" alt="screenshot at dec 16 15-23-16" src="https://cloud.githubusercontent.com/assets/3109112/21266965/9552337c-c3a8-11e6-86c3-f247a55991be.png">
<img width="697" alt="screenshot at dec 16 15-23-47" src="https://cloud.githubusercontent.com/assets/3109112/21266967/95582de0-c3a8-11e6-996a-ff11cd482c61.png">
<img width="700" alt="screenshot at dec 16 15-24-19" src="https://cloud.githubusercontent.com/assets/3109112/21266968/955d1a62-c3a8-11e6-84df-2a0e80263768.png">


Query

```
$products     = pods( 'product', array( 'limit' => - 1 ) );
$productTypes = pods( 'product_type', array( 'limit' => - 1 ) );

if ( $products ) {
	while ( $products->fetch() ) {
		echo $products->display( 'name' ) . "\n";
	}
	var_export( $products->total_found() );
	echo "\n\n";
}

if ( $productTypes ) {
	while ( $productTypes->fetch() ) {
		echo $productTypes->display( 'name' ) . "\n";
	}
	var_export( $productTypes->total_found() );
}

**Comment by dangson** [comment] 2016-12-19 02:09
@srdjan-jcc Thanks for investigating. It was a configuration issue on my end (step #2 in your list).

**Comment by aleix10kst** [comment] 2016-12-19 07:56
@srdjan-jcc 
Hello, excuse me for this late replay, all work as expected. Thank you very much!

**Comment by jlami** [comment] 2016-12-19 09:24
@srdjan-jcc I think you should compare the results with the normal output of `get_terms()` from default wordpress. This is even filtered if you don't specify auto_adjust_ids.
But because you don't want the extra query overhead when querying by id, there should still be some logic that checks for auto_adjust_ids in that case.

I believe the behaviour for post-types are a bit different, but I haven't tested this recently. As I recall get_posts (or WP_Query) only filters by language if the suppress_filters argument is not true. Pods could do something similar, but I don't know if it has any option that is similar.

**Comment by srdjan-jcc** [comment] 2016-12-20 14:42
@jlami To be honest - after spending time on this, I cannot think of logic
in which case to (not) consider using auto_adjust_ids.
All I see is option to remove or keep auto_adjust_ids check.
Please let me know if you have some idea.

@dangson Please make sure Product Types are set as translatable on screen:
WPML > Translation Management > Multilingual Content Setup

**Comment by jlami** [comment] 2016-12-20 15:15
I believe `get_table_info` is now not really aware of whether it is called for a single item (by id) in which case the auto_adjust_ids flag should be honored, or whether it is called for all the items (without id) in which case the query should always be adjusted. (Although I'm not sure if pods works the same way as WPML integrates with normal WP when it comes to loading by ID.)
`get_current_language` should also take this into account, and should return the language also when auto_adjust_ids is false.

But I do agree that pods has some code that is not really ready for these conditions. So I would also not really know where to fix this.

**Comment by quasel** [comment] 2018-09-01 22:12
Sorry for the late reply, feel free to comment if you still have questions, but we're closing this due to inactivity!

**Closed by quasel** 2018-09-01 22:12 UTC
Labels: Closed: Out of scope, Focus: i18n, Status: Need Reproduction, Type: Bug
