### ISSUE TITLE
Pods BiDirectional Relationship Fields MultiSelect Issue

### ISSUE THREAD

**Issue by coadr93** [pods-framework/pods#6956] opened 2022-11-24 08:14 UTC
### Description

When creating a bidirectional multi select relationship between two pods, at some point, randomly, it stops working.

The issue is that the pods don't show in shortcodes anymore.

If you try to edit a taxonomy to add relationships, the old ones you've selected are still there but when you search it says no results to add new ones.

I was trying to create a relationship between two taxonomies so that I can display some URLs to index only the ones that have that relationship.

I used multiselect because Tax1 can be linked to multiple Tax2 and vice-versa.

### Version

2.9.9

### Testing Instructions

1. Create two taxonomies
2. Extend both with pods and in each one create a bidirectional relationship field
3. At some point, it just doesn't work. I couldn't really figure out what triggers it...
4. When you edit one of the taxonomies and try to add a relationship, it will say NO RESULTS
5. If there are preselected relationships that were added before, it seems to show them and you can still search between them, just not new ones. So if I have taxes 1,2,3,4,5 and I relationship 1,2,3 and then it stops working randomly if I edit I still see 1,2,3 and I can search for 1,2,3 but not for 4 and 5.
6. Relinking the fields sometimes gets it to work again (so removing bidirectional relation or deleting the field and creating it again)
7. It seems to be an issue with the bidirectional field. Mostly, that's what I can figure. If I add bidirectional it seems to crash at some point... If I remove bidirectional it seems to work but then I have to link the taxonomies twice, once in the first and then once in the second and it's hard to manage.

### Screenshots / Screencast

![3](https://user-images.githubusercontent.com/68494579/203726575-973edc58-0b35-471c-b407-c7b89682b648.png)
![2scr3](https://user-images.githubusercontent.com/68494579/203726580-108962b2-bffc-4052-8948-9b7d2a55f546.png)
![2scr-2](https://user-images.githubusercontent.com/68494579/203726583-70cd48cb-37ee-4701-9ba7-f75e6027a7c1.png)
![2scr](https://user-images.githubusercontent.com/68494579/203726586-3ac42b96-d754-476b-b682-4dd574f43658.png)
![1scr](https://user-images.githubusercontent.com/68494579/203726590-9352883f-22f0-4e46-a556-7eb011c80392.png)

### Possible Workaround

7. It seems to be an issue with the bidirectional field. Mostly, that's what I can figure. If I add bidirectional it seems to crash at some point... If I remove bidirectional it seems to work but then I have to link the taxonomies twice, once in the first and then once in the second and it's hard to manage.

### Site Health Information

```text
`
### wp-core ###

version: 6.0.3
site_language: ro_RO
user_language: ro_RO
timezone: +03:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: closed
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/vhosts/angelsauto.ro/httpdocs
wordpress_size: loading...
uploads_path: /var/www/vhosts/angelsauto.ro/httpdocs/wp-content/uploads
uploads_size: loading...
themes_path: /var/www/vhosts/angelsauto.ro/httpdocs/wp-content/themes
themes_size: loading...
plugins_path: /var/www/vhosts/angelsauto.ro/httpdocs/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

maintenance.php: true

### wp-active-theme ###

name: ajzaa child theme (ajzaa-child)
version: 1.0
author: angelsauto
author_website: (undefined)
parent_theme: Ajzaa (ajzaa)
theme_features: core-block-patterns, post-thumbnails, post-formats, automatic-feed-links, custom-background, title-tag, woocommerce, html5, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, custom-header, editor-styles, editor-style, align-wide, editor-color-palette, editor-font-sizes, menus, widgets-block-editor, widgets
theme_path: /var/www/vhosts/angelsauto.ro/httpdocs/wp-content/themes/ajzaa-child
auto_update: Dezactivată

### wp-parent-theme ###

name: Ajzaa (ajzaa)
version: 3.0
author: Mymoun
author_website: http://www.webdevia.com/
theme_path: /var/www/vhosts/angelsauto.ro/httpdocs/wp-content/themes/ajzaa
auto_update: Dezactivată

### wp-themes-inactive (3) ###

Flozen Theme: version: 1.2.4, author: NasaTheme, Actualizările automate sunt dezactivate
Twenty Twenty-One: version: 1.0, author: echipa WordPress (latest version: 1.7), Actualizările automate sunt dezactivate
Twenty Twenty-Two: version: 1.2, author: echipa WordPress (latest version: 1.3), Actualizările automate sunt dezactivate

### wp-plugins-active (45) ###

Add Admin JavaScript: version: 2.0, author: Scott Reilly, Actualizările automate sunt dezactivate
Advanced Order Export For WooCommerce: version: 3.3.2, author: AlgolPlus (latest version: 3.3.3), Actualizările automate sunt dezactivate
Akismet Anti-Spam: version: 4.1.10, author: Automattic (latest version: 5.0.1), Actualizările automate sunt dezactivate
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: version: 3.0, author: codewoogeek, Actualizările automate sunt dezactivate
Checkout Field Editor for WooCommerce: version: 1.7.1, author: ThemeHigh (latest version: 1.8.0), Actualizările automate sunt dezactivate
Contact Form 7: version: 5.4.1, author: Takayuki Miyoshi (latest version: 5.6.4), Actualizările automate sunt dezactivate
Duplicate Menu: version: 0.2.2, author: Jonathan Christopher, Actualizările automate sunt dezactivate
Easy Watermark: version: 1.0.11, author: BracketSpace, Actualizările automate sunt dezactivate
Email Subscribers & Newsletters: version: 5.4.6, author: Icegram (latest version: 5.5.0), Actualizările automate sunt dezactivate
FiboSearch - AJAX Search for WooCommerce: version: 1.12.0, author: FiboSearch Team (latest version: 1.21.0), Actualizările automate sunt dezactivate
Insert PHP Code Snippet: version: 1.3.3, author: xyzscripts.com, Actualizările automate sunt dezactivate
JSON Basic Authentication: version: 0.1, author: WordPress API Team, Actualizările automate sunt dezactivate
Loco Translate: version: 2.6.3, author: Tim Whitlock, Actualizările automate sunt dezactivate
Media Library Filter: version: 1.0.10, author: datafeedr.com, Actualizările automate sunt dezactivate
NETOPIA Payments Payment Gateway: version: 1.0, author: Netopia, Actualizările automate sunt dezactivate
PixelYourSite PRO: version: 8.6.6, author: PixelYourSite (latest version: 9.3.6), Actualizările automate sunt dezactivate
PixelYourSite Super Pack: version: 3.0.7, author: PixelYourSite, Actualizările automate sunt dezactivate
Pluginception: version: 1.3, author: Otto, Actualizările automate sunt dezactivate
Pods - Custom Content Types and Fields: version: 2.9.9, author: Pods Framework Team, Actualizările automate sunt dezactivate
Post Category Filter: version: 1.6.1, author: Javier Villanueva, Actualizările automate sunt dezactivate
Product Catalog Feed Pro by PixelYourSite: version: 5.1.2, author: PixelYourSite (latest version: 5.3.1), Actualizările automate sunt dezactivate
Product CSV Import Export (BASIC): version: 2.0.3, author: WebToffee (latest version: 2.2.6), Actualizările automate sunt dezactivate
Product Filter by WooBeWoo: version: 2.2.1, author: WooBeWoo (latest version: 2.2.3), Actualizările automate sunt dezactivate
Rank Math SEO: version: 1.0.100.1, author: Rank Math (latest version: 1.0.102.1), Actualizările automate sunt dezactivate
Retainful - Abandoned Cart Recovery Emails and Next Order Coupons: version: 2.6.15, author: Retainful (latest version: 2.6.16), Actualizările automate sunt dezactivate
Simple Custom CSS and JS: version: 3.37, author: SilkyPress.com (latest version: 3.41), Actualizările automate sunt dezactivate
Slider Revolution: version: 6.5.4, author: ThemePunch, Actualizările automate sunt dezactivate
Webdevia main plugin: version: 2.7, author: Mymoun, Actualizările automate sunt dezactivate
Widget CSS Classes: version: 1.5.4.1, author: Jory Hogeveen, Actualizările automate sunt dezactivate
WooCommerce: version: 5.4.4, author: Automattic (latest version: 7.1.0), Actualizările automate sunt dezactivate
WooCommerce Admin: version: 2.4.1, author: WooCommerce (latest version: 3.3.2), Actualizările automate sunt dezactivate
WooCommerce Price Based on Country (Basic): version: 2.0.22, author: Oscar Gare (latest version: 2.2.8), Actualizările automate sunt dezactivate
WooCommerce Side Cart: version: 2.1, author: XootiX, Actualizările automate sunt dezactivate
Woo Discount Rules: version: 2.4.5, author: Flycart (latest version: 2.5.2), Actualizările automate sunt dezactivate
Woo Discount Rules PRO 2.0: version: 2.4.4, author: Flycart, Actualizările automate sunt dezactivate
Woo Product Filter PRO: version: 2.1.8, author: WooBeWoo (latest version: 2.2.3), Actualizările automate sunt dezactivate
Woo Quick View: version: 1.1.0, author: Arshid, Actualizările automate sunt dezactivate
Wordfence Security: version: 7.5.4, author: Wordfence (latest version: 7.7.1), Actualizările automate sunt dezactivate
WP All Export Pro: version: 1.6.3, author: Soflyy (latest version: 1.8.1), Actualizările automate sunt dezactivate
WP All Import - WooCommerce Import Add-On Pro: version: 3.3.3, author: Soflyy (latest version: 3.3.4), Actualizările automate sunt dezactivate
WP All Import Pro: version: 4.7.5, author: Soflyy (latest version: 4.7.8), Actualizările automate sunt dezactivate
WP Anunturi: version: 1.0, author: Angels Auto, Actualizările automate sunt dezactivate
WPBakery Page Builder: version: 6.6.0, author: Michael M - WPBakery.com (latest version: 6.10.0), Actualizările automate sunt dezactivate
WP Crontrol: version: 1.10.0, author: John Blackbourn & crontributors (latest version: 1.14.0), Actualizările automate sunt dezactivate
WP phpMyAdmin: version: 5.1.1.05, author: Puvox.software (latest version: 5.2.0.7), Actualizările automate sunt dezactivate

### wp-plugins-inactive (9) ###

Advanced AJAX Product Filters for WooCommerce: version: 1.5.5, author: BeRocket (latest version: 1.6.3.3), Actualizările automate sunt dezactivate
Extendons: WooCommerce Product Image Watermark Plugin: version: 1.0.7, author: Extendons, Actualizările automate sunt dezactivate
Navigation menu as dropdown Widget: version: 1.3.0, author: Jeroen Peters (latest version: 1.3.3), Actualizările automate sunt dezactivate
Product Feed PRO for WooCommerce: version: 11.1.3, author: AdTribes.io (latest version: 12.0.3), Actualizările automate sunt dezactivate
Regenerate Thumbnails: version: 3.1.5, author: Alex Mills (Viper007Bond), Actualizările automate sunt dezactivate
WooCommerce Advanced Free Shipping: version: 1.1.4, author: Jeroen Sormani (latest version: 1.1.5), Actualizările automate sunt dezactivate
WooCommerce Products Image Watermark: version: 3.0.6.1, author: BeRocket, Actualizările automate sunt dezactivate
WordPress REST API Authentication: version: 1.6.1, author: miniOrange (latest version: 2.4.2), Actualizările automate sunt dezactivate
YITH WooCommerce Wishlist: version: 3.0.17, author: YITH (latest version: 3.15.0), Actualizările automate sunt dezactivate

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1692
imagemagick_version: ImageMagick 6.9.12-54 Q16 x86_64 17322 https://legacy.imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 Mo
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 125 Go
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 125 Go
	imagick::RESOURCETYPE_MEMORY: 63 Go
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, A, AAI, AI, APNG, ART, ARW, AVI, AVS, B, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, C, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K, K25, KDC, LABEL, M, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, O, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, R, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCREENSHOT, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, Y, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.18.0-305.3.1.el8_4.x86_64 x86_64
httpd_software: nginx/1.20.2
php_version: 7.4.33 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 600
memory_limit: 256000M
max_input_time: 600
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.61.1 OpenSSL/1.1.1k
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.3.35-MariaDB
client_version: mysqlnd 7.4.33
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/vhosts/angelsauto.ro/httpdocs/wp-content
WP_PLUGIN_DIR: /var/www/vhosts/angelsauto.ro/httpdocs/wp-content/plugins
WP_MEMORY_LIMIT: 256000M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Nedefinită
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: nginx/1.20.2
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
pods-session-save-path: /var/lib/php/session
pods-session-save-path-exists: Nu
pods-session-save-path-writable: Nu
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: Nu
pods-opcode-cache-memcached: Nu
pods-opcode-cache-opcache: Nu
pods-opcode-cache-redis: Nu
pods-object-cache-apc: Nu
pods-object-cache-apcu: Nu
pods-object-cache-memcache: Nu
pods-object-cache-memcached: Nu
pods-object-cache-redis: Da
pods-memory-current-usage: 44,739M
pods-memory-current-usage-real: 2,000M
pods-network-wide: Nu
pods-install-location: /wp-content/plugins/pods/
pods-developer: Nu
pods-tableless-mode: Nu
pods-relationship-table-enabled: Da
pods-light-mode: Nu
pods-strict: Nu
pods-allow-deprecated: Da
pods-api-cache: Da
pods-shortcode-allow-evaluate-tags: Nu
pods-sessions: Disable sessions
pods-can-use-sessions: Nu
pods-relationship-table-status: 5

`
```

### Pods Package

```json
{
    "@meta": {
        "version": "2.9.9",
        "build": 1669277440
    },
    "settings": {
        "types_only": "0",
        "watch_changed_fields": "0",
        "metadata_integration": "0",
        "metadata_override_get": "0",
        "session_auto_start": "0",
        "wisdom_opt_out": "1"
    },
    "pods": [
        {
            "name": "product_cat",
            "id": 78759,
            "label": "Product Cat",
            "description": "",
            "type": "taxonomy",
            "storage": "meta",
            "object": "product_cat",
            "_migrated_28": "1",
            "required": "0",
            "repeatable": "0",
            "pfat_enable": "0",
            "pfat_filter_single": "get_the_archive_description",
            "write_all": "product_cat",
            "groups": [
                {
                    "name": "mai_multe_campuri",
                    "id": 78760,
                    "label": "Mai multe c\u00e2mpuri",
                    "description": "",
                    "weight": 0,
                    "fields": [
                        {
                            "name": "modele_relevante_indexare",
                            "id": 83310,
                            "label": "Modele relevante pentru indexare",
                            "description": "",
                            "weight": 0,
                            "type": "pick",
                            "pick_object": "taxonomy",
                            "pick_val": "product_tax",
                            "pick_table": "-- Selecteaz\u0103 Unul --",
                            "required": "0",
                            "pick_format_type": "multi",
                            "pick_format_single": "dropdown",
                            "pick_format_multi": "list",
                            "pick_display_format_multi": "default",
                            "pick_display_format_separator": ", ",
                            "pick_allow_add_new": "1",
                            "pick_taggable": "0",
                            "pick_show_icon": "1",
                            "pick_show_edit_link": "1",
                            "pick_show_view_link": "1",
                            "pick_limit": "0",
                            "pick_user_role": "Administrator",
                            "pick_post_status": "publish",
                            "pick_post_author": "0",
                            "repeatable": "0",
                            "repeatable_format": "default",
                            "roles_allowed": "administrator",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1"
                        }
                    ]
                }
            ]
        },
        {
            "name": "product_tax",
            "id": 78756,
            "label": "Product Tax",
            "description": "",
            "type": "taxonomy",
            "storage": "meta",
            "object": "product_tax",
            "_migrated_28": "1",
            "required": "0",
            "repeatable": "0",
            "pfat_enable": "0",
            "pfat_single": "DummyTemplate",
            "write_all": "product_tax",
            "groups": [
                {
                    "name": "mai_multe_campuri",
                    "id": 78757,
                    "label": "Mai multe c\u00e2mpuri",
                    "description": "",
                    "weight": 0,
                    "fields": [
                        {
                            "name": "brand_auto",
                            "id": 78940,
                            "label": "Aceasta categorie este un brand auto?",
                            "description": "Da = Acesta taxonomie este un brand auto | Nu = Model masina",
                            "weight": 0,
                            "type": "boolean",
                            "sister_id": "-- Selecteaz\u0103 Unul --",
                            "required": "0",
                            "repeatable": "0",
                            "boolean_format_type": "dropdown",
                            "boolean_yes_label": "Da, acesta este un brand auto",
                            "boolean_no_label": "Nu, acesta este un model auto",
                            "roles_allowed": "administrator",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1",
                            "default_value": "Nu, acesta este un model auto"
                        },
                        {
                            "name": "categorii_relevante_indexare",
                            "id": 83309,
                            "label": "Categorii relevante pentru indexare",
                            "description": "",
                            "weight": 1,
                            "type": "pick",
                            "pick_object": "taxonomy",
                            "pick_val": "product_cat",
                            "pick_table": "-- Selecteaz\u0103 Unul --",
                            "required": "0",
                            "pick_format_type": "multi",
                            "pick_format_single": "dropdown",
                            "pick_format_multi": "list",
                            "pick_display_format_multi": "default",
                            "pick_display_format_separator": ", ",
                            "pick_allow_add_new": "1",
                            "pick_taggable": "0",
                            "pick_show_icon": "1",
                            "pick_show_edit_link": "1",
                            "pick_show_view_link": "1",
                            "pick_limit": "0",
                            "pick_user_role": "Administrator",
                            "pick_post_status": "publish",
                            "pick_post_author": "0",
                            "repeatable": "0",
                            "repeatable_format": "default",
                            "roles_allowed": "administrator",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1"
                        }
                    ]
                }
            ]
        }
    ],
    "templates": [
        {
            "name": "DummyTemplate2",
            "code": "",
            "id": 79898,
            "_edit_lock": "1666034179:1",
            "_edit_last": "1",
            "admin_only": "0",
            "restrict_capability": "0",
            "show_restrict_message": "0",
            "_pods_capability_allowed": [
                ""
            ],
            "pod_reference": {
                "pod": "product_tax"
            }
        }
    ]
}
```

**Comment by coadr93** [comment] 2022-11-24 08:28
I know the pods are still there even if they don't show because I've exported them with WP all export and the IDs are in the list.

There seems to be an anomaly in the database as one column is with unserialised IDs and the other with seralized IDs, but in the column of the unserialised ones there is a serialized cell.

So as you will be able to see below, they match but the column before 2154|3276|5126 is different...

**Should I edit the database and try to match these?**


**UNSERALIZED COLUMN**

modele_relevante_indexare

3454|3457|3439|2175|2182|2153|3404|3280

2153|3687|3404|2082|4011|4906

2154|3277|2175|5060|5007

a:4:{i:0;s:4:"3404";i:1;s:4:"2175";i:2;s:4:"2182";i:3;s:4:"2153";}|a:4:{i:0;s:4:"3404";i:1;s:4:"2175";i:2;s:4:"2182";i:3;s:4:"2153";}|a:4:{i:0;s:4:"3404";i:1;s:4:"2175";i:2;s:4:"2182";i:3;s:4:"2153";}|a:4:{i:0;s:4:"3404";i:1;s:4:"2175";i:2;s:4:"2182";i:3;s:4:"2153";}|a:4:{i:0;s:4:"3404";i:1;s:4:"2175";i:2;s:4:"2182";i:3;s:4:"2153";}

2154|3276|5126

**SERIALIZED COLUMN**

_pods_modele_relevante_indexare

a:8:{i:0;i:3454;i:1;i:3457;i:2;i:3439;i:3;i:2175;i:4;i:2182;i:5;i:2153;i:6;i:3404;i:7;i:3280;}

a:6:{i:0;i:2153;i:1;i:3687;i:2;i:3404;i:3;i:2082;i:4;i:4011;i:5;i:4906;}

a:5:{i:0;i:2154;i:1;i:3277;i:2;i:2175;i:3;i:5060;i:4;i:5007;}

a:5:{i:0;i:3404;i:1;i:2175;i:2;i:2182;i:3;i:2153;i:4;i:3452;}

a:3:{i:0;i:2154;i:1;i:3276;i:2;i:5126;}

**Comment by sc0ttkclark** [comment] 2023-03-06 00:17
This may have been fixed via https://github.com/pods-framework/pods/issues/7018

**Comment by sc0ttkclark** [comment] 2023-03-06 00:18
I can't reproduce the issue with being unable to search for terms in the search box, digging in further.

**Comment by sc0ttkclark** [comment] 2023-03-06 00:20
No luck there, this may need more testing to determine if there's something else going on with a console error or an unexpected JSON response from the AJAX request when it performs that search.

Do you have 30+ product category or 30+ product tax terms in your DB?

**Comment by coadr93** [comment] 2023-03-06 09:23
Thanks :)

Yes, definitely more than 30 categories and custom tax terms.

I'm running latest. I will retest everything on my end and let you know.

Any idea what the best way of clearing the database of the relationships would be?

**Comment by sc0ttkclark** [comment] 2023-03-06 14:48
Can you clarify what you want to do with clearing relationships? Do you mean removing the fields or removing just the data (reset the relationships data for specific fields)?

**Comment by coadr93** [comment] 2023-03-06 16:12
Yes, so in the backend of WP the relationships between those two pods don't show, but they are still in the database when I use WP all export to export the fields.

**Comment by sc0ttkclark** [comment] 2023-03-06 16:19
I think perhaps you are looking for a tool to repair relationship data for a relationship field:

* Ensure data is in the right places for wp_podsrel table and meta table (for meta-based Pods)
* Populate bidirectional data where it's missing

I'll see what I can put together here but I don't really have a great off-the-shelf solution for this at the moment for you.

**Comment by coadr93** [comment] 2023-03-06 16:52
No biggie, I can just create new fields and redo the relationships on those new fields, and leave the old ones there. I have enough space for the DB :) I'll create new fields, redo the relationships and see if the issue repeats itself.

**Comment by coadr93** [comment] 2023-03-06 19:02
Great, thanks for letting me know :)

**Closed** 2023-05-29 17:01 UTC
Labels: Type: Bug, Status: Need User Feedback, Closed: Could not reproduce, Status: PR > QA pending
