### ISSUE TITLE
Problem date-time date

### ISSUE THREAD

**Issue by favy87** [pods-framework/pods#5664] opened 2020-04-03 09:02 UTC
**Describe the bug**
Funcionaba todo correcto hasta el año 2020.
Estamos creando una clase "factura" de pods en PHP y le estamos pasando la fecha de la factura en el formato "dd-mm-aaaa" pero POD's parece que ahora no entiende la fecha y pone otra fecha diferente, ejemplo:
dd-mm-aaaa________________dd-mm-aaaa
02-01-2020 lo convierte en 31-01-2020
01-02-2020 lo convierte en 01-01-2020
01-03-2020 lo convierte en 02-01-2020

mm-dd-aaaa________________dd-mm-aaaa
01-02-2020 lo convierte en 01-01-2020
02-01-2020 lo convierte en 31-01-2020
03-01-2020 lo convierte en 29-02-2020

**Screenshots**
![github 0](https://user-images.githubusercontent.com/5238141/78342985-782f4a80-759a-11ea-98aa-32fa918a0062.JPG)
![github 1](https://user-images.githubusercontent.com/5238141/78342184-2e923000-7599-11ea-9f6b-27fbc7785821.JPG)

## Pods Version
Pods - Custom Content Types and Fields: 2.7.17.1

## WordPress Environment
WordPress Version: 5.3.2
PHP Version: 7.3.15
MySQL Version: 5.7.29
Server Software: Apache

**Comment by JoryHogeveen** [comment] 2020-04-03 10:20
Hello @favy87 

**Please answer in English**

The formats you mention work fine on my local installation. Please give us more info on how to step-by-step reproduce your issue.

Cheers, Jory

**Comment by mmonllor** [comment] 2020-04-17 08:25
Hi. I have the same problem. When I add a pod object that contains a date field "dd/mm/ YYYY", the result is not as desired. This occurs from December 2019.

"04/01/2020" transforms it to "03/01/2020"
"01/02/2020" transforms it to "01/31/2020"

**Comment by JoryHogeveen** [comment] 2020-04-17 08:37
Hi @mmonllor
Pleasr provide more info. Do you mean when you edit the dat field within WordPress Admin?

**Comment by mmonllor** [comment] 2020-04-17 08:51
No.

For example, the following code PHP shows me in Wordpress "03/01/2020"

$pod = pods( 'document' );
$data = array('name' => 'test',  'date' => '01/04/2020');
$new_document = $pod->add( $data );

**Comment by JoryHogeveen** [comment] 2020-04-17 09:08
Correct, date input should be in sql dat format: Y-m-d

**Comment by mmonllor** [comment] 2020-04-17 09:42
But since when is "Y-m-d" the correct date format? The date format "dd/mm/YYYY" worked fine in version 2.7.15.

**Comment by JoryHogeveen** [comment] 2020-04-17 10:24
Version 2.7.15 already had this change. Pods always stored as Y-m-d but for compatibility with more complex formats the input also changed to Y-m-d.
I afraid this is my doing and I didn't consider that users would manually input different dates since that would be strange from a programming perspective.

In any case, I have made a patch that would allow the field display format for input.
Please see PR #5687 for a possible fix and let me know if that works for you. If so, I'll add tests in the framework to prevent this from breaking again and make sure this fix will be included in the next update.

Cheers, Jory

**Comment by mmonllor** [comment] 2020-04-17 10:57
Hi Jory

The patch has worked perfectly.

Thank you very much.

Cheers

**Comment by JoryHogeveen** [comment] 2020-04-17 11:33
Hi @mmonllor 
Thanks for your quick feedback!

**Comment by favy87** [comment] 2020-04-20 06:12
Gracias !!
Parece que la modificacion funciona correctamente.

**Closed** 2020-06-25 16:02 UTC
Labels: Focus: Back Compat, Status: Reproduced, Type: Bug
