### ISSUE TITLE
2.8 Field Groups

### ISSUE THREAD

**Issue by JessieBee3** [pods-framework/pods#6187] opened 2021-10-19 11:29 UTC
## Description
It isn't possible to move existing field into new group sections. Right now, only new fields can be placed in new groups.

## Testing instructions
Drag/drop any existing field into a newly created Field Group.

## Expected behavior
The existing field should move into the new field group.

## Possible workaround
I'm continuing to use the workaround for groups in the functions.

## Pods version
2.8

<details>
<summary>WordPress Environment</summary>
  
```
This is a staging site.
`
### wp-core ###

version: 5.8.1
site_language: es_ES
user_language: en_US
timezone: America/Chicago
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 19609
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html/obrerofiel
wordpress_size: loading...
uploads_path: /var/www/html/obrerofiel/wp-content/uploads
uploads_size: loading...
themes_path: /var/www/html/obrerofiel/wp-content/themes
themes_size: loading...
plugins_path: /var/www/html/obrerofiel/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (2) ###

advanced-cache.php: true
db.php: true

### wp-active-theme ###

name: Obrero Fiel Astra Pro (0brero-fiel-astra-pro)
version: 1.0
author: Jessie Bee
author_website: http://jessiebeecreative.com/
parent_theme: Astra (astra)
theme_features: core-block-patterns, woocommerce, astra_hooks, widgets-block-editor, align-wide, automatic-feed-links, title-tag, post-thumbnails, html5, post-formats, custom-logo, customize-selective-refresh-widgets, editor-style, rank-math-breadcrumbs, amp, editor-color-palette, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, fl-theme-builder-headers, fl-theme-builder-footers, fl-theme-builder-parts, widgets, menus
theme_path: /var/www/html/obrerofiel/wp-content/themes/0brero-fiel-astra-pro
auto_update: Disabled

### wp-parent-theme ###

name: Astra (astra)
version: 3.7.3
author: Brainstorm Force
author_website: https://wpastra.com/about/
theme_path: /var/www/html/obrerofiel/wp-content/themes/astra
auto_update: Disabled

### wp-themes-inactive (7) ###

Obrero Fiel Astra: version: 1.0.1534958231, author: Jessie Bee, Auto-updates disabled
Eduma: version: 3.3.0, author: ThimPress, Auto-updates disabled
obrerofiel: version: 0.1.1508421384, author: Keruxgroup, Auto-updates disabled
Twenty Nineteen: version: 2.1, author: the WordPress team, Auto-updates disabled
Twenty Seventeen: version: 2.8, author: the WordPress team, Auto-updates disabled
Twenty Twenty: version: 1.8, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.4, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (40) ###

a3 Lazy Load: version: 2.4.7, author: a3rev Software, Auto-updates disabled
Admin Custom Login: version: 3.3.0, author: Weblizar, Auto-updates disabled
Adminimize: version: 1.11.7, author: Frank Bültge, Auto-updates disabled
Advanced Custom Fields PRO: version: 5.9.9, author: Delicious Brains, Auto-updates disabled
Advanced Editor Tools (previously TinyMCE Advanced): version: 5.6.0, author: Automattic, Auto-updates disabled
Akismet Anti-Spam: version: 4.2.1, author: Automattic, Auto-updates disabled
Astra Pro: version: 3.6.1, author: Brainstorm Force, Auto-updates disabled
Beaver Builder Plugin (Standard Version): version: 2.4.2.5, author: The Beaver Builder Team, Auto-updates disabled
Beaver Themer: version: 1.3.3.1, author: The Beaver Builder Team, Auto-updates disabled
Better Search Replace: version: 1.3.4, author: Delicious Brains, Auto-updates disabled
Caldera Forms: version: 1.9.4, author: Caldera Forms, Auto-updates disabled
Caldera Forms Mailchimp: version: 2.0.2, author: Caldera Forms, Auto-updates disabled
CalderaWP License Manager: version: 1.2.11, author: CalderaWP, Auto-updates disabled
Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates disabled
Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: version: 6.6.0, author: SeedProd, Auto-updates disabled
Custom Content Shortcode: version: 3.8.7, author: Eliot Akira, Auto-updates disabled
Custom Post Type UI: version: 1.10.0, author: WebDevStudios, Auto-updates disabled
eBook store: version: 5.743, author: Shopfiles Ltd, Auto-updates disabled
Embed Extended: version: 1.3.0, author: Rudy Susanto, Auto-updates disabled
Free Downloads WooCommerce Pro: version: 3.3.21, author: Square One Media, Auto-updates disabled
Loco Translate: version: 2.5.5, author: Tim Whitlock, Auto-updates disabled
MC4WP: Mailchimp for WordPress: version: 4.8.6, author: ibericode, Auto-updates disabled
Multi-column Tag Map: version: 17.0.16, author: Alan Jackson, Auto-updates disabled
Ninja Beaver Lite Addons for Beaver Builder: version: 2.4.4, author: Ninja Team, Auto-updates disabled
PDF Embedder Premium Secure: version: 4.4.5, author: Lever Technology LLC, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 2.8.0, author: Pods Framework Team, Auto-updates disabled
Pods Beaver Themer Add-On: version: 1.3.6, author: Quasel, Pods Framework Team, Auto-updates disabled
Preview E-mails for WooCommerce: version: 1.6.8, author: Digamber Pradhan, Auto-updates disabled
Redirection: version: 5.1.3, author: John Godley, Auto-updates disabled
Regenerate Thumbnails Advanced: version: 2.4.0, author: ShortPixel, Auto-updates disabled
reSmush.it Image Optimizer: version: 0.4.1, author: reSmush.it, Auto-updates disabled
Safe SVG: version: 1.9.9, author: Daryll Doyle, Auto-updates disabled
Ultimate Addons for Beaver Builder: version: 1.34.0, author: Brainstorm Force, Auto-updates disabled
User Role Editor: version: 4.60.2, author: Vladimir Garagulya, Auto-updates disabled
WooCommerce: version: 5.8.0, author: Automattic, Auto-updates disabled
WooCommerce AJAX Products Filter: version: 3.0.5, author: BeRocket, Auto-updates disabled
WooCommerce PayPal Checkout Gateway: version: 2.1.3, author: WooCommerce, Auto-updates disabled
WooCommerce Role-O-Matic: version: 8.3, author: Lagudi Domenico, Auto-updates disabled
WooCommerce Subscriptions: version: 3.1.4, author: WooCommerce, Auto-updates disabled
WordPress Importer: version: 0.7, author: wordpressdotorg, Auto-updates disabled

### wp-plugins-inactive (17) ###

Advanced Ads: version: 1.29.1, author: Thomas Maier, Advanced Ads GmbH, Auto-updates disabled
All-in-One WP Migration: version: 7.48, author: ServMask (latest version: 7.49), Auto-updates disabled
Easy Forms for Mailchimp: version: 6.8.5, author: YIKES, Inc., Auto-updates disabled
Gmail SMTP: version: 1.2.2, author: naa986, Auto-updates disabled
List Custom Taxonomy Widget: version: 4.1, author: Nick Halsey, Auto-updates disabled
MC4WP: Mailchimp User Sync: version: 1.8.1, author: ibericode, Auto-updates disabled
Nextend Social Login: version: 3.1.2, author: Nextendweb, Auto-updates disabled
Restrict Content: version: 2.2.10, author: iThemes, Auto-updates disabled
ScaleSTACK Control: version: 1.3.1, author: Entasis Technology Consulting, Auto-updates disabled
WordPress Users & WooCommerce Customers Import Export(BASIC): version: 2.2.0, author: WebToffee, Auto-updates disabled
WP All Export: version: 1.3.2, author: Soflyy, Auto-updates disabled
WP Email Users: version: 1.7.6, author: techspawn1, Auto-updates disabled
WP Fastest Cache: version: 0.9.5, author: Emre Vona, Auto-updates disabled
WP Sheet Editor - WooCommerce Products (Premium): version: 1.0.14, author: WP Sheet Editor, Auto-updates disabled
YITH WooCommerce Ajax Product Filter Premium: version: 4.0.2, author: YITH, Auto-updates disabled
YITH WooCommerce Ajax Search: version: 1.11.0, author: YITH, Auto-updates disabled
Yoast SEO: version: 17.3, author: Team Yoast (latest version: 17.4), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 32M
upload_max_filesize: 32M
max_effective_size: 32 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.14.238-182.422.amzn2.x86_64 x86_64
httpd_software: Apache/2.4.51 ()
php_version: 7.4.21 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
max_input_time: 60
upload_max_filesize: 32M
php_post_max_size: 32M
curl_version: 7.61.1 OpenSSL/1.0.2k
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.5.12-MariaDB
client_version: mysqlnd 7.4.21

### wp-constants ###

WP_HOME: https://dev.obrerofiel.com
WP_SITEURL: https://dev.obrerofiel.com
WP_CONTENT_DIR: /var/www/html/obrerofiel/wp-content
WP_PLUGIN_DIR: /var/www/html/obrerofiel/wp-content/plugins
WP_MEMORY_LIMIT: false
WP_MAX_MEMORY_LIMIT: false
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: Apache/2.4.51 ()
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 Firefox/93.0
pods-session-save-path: /var/lib/php/session
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 129.393M
pods-memory-current-usage-real: 7.000M
pods-network-wide: No
pods-install-location: /var/www/html/obrerofiel/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Yes
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No
pods-sessions: Disable sessions
pods-can-use-sessions: No

`

```

</details>

**Comment by JoryHogeveen** [comment] 2021-10-19 12:38
Duplicate of #5937

**Closed by JoryHogeveen** 2021-10-19 12:38 UTC
Labels: Type: Bug
