### ISSUE TITLE
writing or pasting a <style> tag breaks the templates editor

### ISSUE THREAD

**Issue by sonicparke** [pods-framework/pods#2656] opened 2015-01-27 15:42 UTC
This codemirror issue looks like it's the exact problem and fix.

https://github.com/codemirror/CodeMirror/issues/2774

**Comment by Shelob9** [comment] 2015-01-27 15:46
Caused by #2657

**Comment by Shelob9** [comment] 2015-03-02 22:14
Closing as fixed via #2662

**Closed by Shelob9** 2015-03-02 22:14 UTC
Labels: Bug: Regression
