### ISSUE TITLE
A "1" is populating under my template.

### ISSUE THREAD

**Issue by jillyk** [pods-framework/pods#6447] opened 2022-02-12 19:46 UTC
### Description

I have a Pods Item List on my site homepage. It is pulling in a pods template that is a simple field: <div>{@featured_policy}</div>

It's pulling in the field content fine, but there's a "1" under it. I need that to go away!

See it below in the yellow box within the screen shot.

### Version

Version 2.8.10

### Screenshots / Screencast

<img width="1210" alt="Screen Shot 2022-02-12 at 2 45 11 PM" src="https://user-images.githubusercontent.com/99559049/153726059-4d5c6214-0922-40e8-825a-26da2ab37532.png">

**Comment by JoryHogeveen** [comment] 2022-02-14 08:19
HI @jillyk 

Can you please include the full template you are using?
Also, what other changes have you made? This almost looks like manual debug output.

**Comment by jillyk** [comment] 2022-02-14 11:29
Here's the site page: 
https://utpolicystage.wpengine.com/
The theme is GeneratePress. 

Interestingly, since I could solve, I just removed that block from the page. Since I just heard back from you, though, I though I'd re-add it and see if you could help. (I'd prefer the block to be on the site!) 

Anyhow here's what's happening now:
1) the 1 has disappeared. 
2) when I decided to delete the block from the homepage, I no longer had a need for the @featured_policy field, so I deleted it as a housekeeping measure.
3) so now, it's displaying beautifully, but I do not know where my pod template is grabbing content from because the reference field doesn't exist. Here's the pod template code: <div>{@featured_policy}</div>. 
4) featured_policy now only exists on the site as a category. 

Let me know if you can make sense of where the pod template is getting the first graph of the content!

Thanks so much,
Jill

**Comment by JoryHogeveen** [comment] 2022-02-22 10:29
Hi @jillyk 
This almost sounds like a formatting issue to a field that no longer exists.
`1` usually means `true` when stored as metadata so there might be some context to find there relating to this issue.
However, I do not understand what rendered this value in your case. I almost get the impression that there could be a hook active that does this? As I said before, this almost looks like manual debug output.

In any case, since it is resolved at the moment, I'm closing this issue. I you encounter it again and are able to reproduce the issue so we can test, let me know!

**Closed by JoryHogeveen** 2022-02-22 10:29 UTC
Labels: Type: Bug
