### ISSUE TITLE
Pods plugin breaks ability to use Theme Editor to update files in Wordpress 4.9.1

### ISSUE THREAD

**Issue by azcomps** [pods-framework/pods#4595] opened 2017-12-01 20:04 UTC
After upgrading from Wordpress from 4.8.4 to 4.9.1, I was no longer able to update files using the Theme Editor (/wp-admin/theme-editor.php) page. Deactivating Pods plugin restored this functionality. 

Healthcheck plugin's troubleshooter revealed following error:

> Your PHP code changes were rolled back due to an error on line 20 of file wp-content/themes/q/template-homepage.php. Please fix and try saving again.
> 
> Uncaught Error: Call to undefined function pods() in wp-content/themes/quiessence/template-homepage.php:20
> Stack trace:
> #0 wp-includes/template-loader.php(74): include()
> #1 wp-blog-header.php(19): require_once('/home/88998-702...')
> #2 index.php(17): require('/home/88998-702...')
> #3 {main}
>   thrown

**Comment by jimtrue** [comment] 2017-12-01 20:17
@azcomps This may be an obvious question, but what is on line 20 of your template-homepage.php?

**Comment by azcomps** [comment] 2017-12-01 20:28
Line #20 is: 

$pod = pods('slide');

**Comment by jimtrue** [comment] 2017-12-01 20:37
Do you have a pod named `slide`? And what are you attempting to edit/change and in what file when you get the error?

Is this a child theme of 'quiessence' or did you edit the actual theme files to add a slider on your homepage using Pods?

**Comment by jimtrue** [comment] 2017-12-01 20:37
It would be helpful if you shared your template-homepage.php as well.

**Comment by azcomps** [comment] 2017-12-01 20:42
Yes, there's a pod named slide. Editing the actual theme files, not a child theme. 

Attempting to edit a php file in the theme, which I know isn't advised to do from within WP admin panel. However, it worked before with Pods plugin enabled up until Wordpress 4.9 so I'm trying to figure out what broke the functionality. Perhaps it's something Wordpress 4.9 introduced and it's not the Pods plugin at all?

**Comment by jimtrue** [comment] 2017-12-01 20:52
I'll be honest with you, this has _more_ to do with the WP 4.9 'editor' enhancements than anything to do with Pods. My guess is there's something possibly kicking a debug warning somewhere and that's what is kicking the error for the new editor and forcing your changes to be rolled back. It's not being terribly helpful with it's error logging or details, either. If you're working on a dev server, you can add [Debugging to your WordPress installation](https://codex.wordpress.org/Debugging_in_WordPress) and hopefully get more details about the errors that might've been there all along.

Editing the theme within WordPress is _never_ advised, the new editor functionality (which they should've given you an 'opt-out' option on) is deliberately over-protecting some people. And the Health Check plugin (if you've gone that route) is blaming the plugin, when it's not actually capturing the error causing the problem, which often is theme related.

And another word of caution: editing the actual theme files? Really bad idea, especially if it updates on you, because then all your changes are lost. Child Themes are safer, because your code changes reside in your own folders.

**Comment by jimtrue** [comment] 2017-12-01 20:54
If you can share what you're trying to change, we might be able to point you down the right path. If you can enable the debugging linked above, getting those errors will be even more helpful.

**Comment by jimtrue** [comment] 2017-12-01 20:58
BTW, that editor from the healthcheck up above? That's what you would get if you disabled pods (which is all the HealthCheck does) and tried to load the homepage-template: 
`Uncaught Error: Call to undefined function pods() in wp-content/themes/quiessence/template-homepage.php:20 
`
Since Pods is disabled, it can't load `pods()`.

**Comment by pglewis** [comment] 2018-05-23 02:08
This may be a duplicate of #4931 and should be tested against the PR in #4953

**Closed** 2018-06-02 02:44 UTC
Labels: Fixed / Needs Testing, Needs User Feedback
