### ISSUE TITLE
2.7 - list view seems to have issues with a test post from wptest.io - doesn't save relation! 

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods#4315] opened 2017-06-18 07:13 UTC
Select it but it doesn't save! 

<img width="882" alt="wptest" src="https://user-images.githubusercontent.com/9464217/27258884-48953360-5406-11e7-8d8a-c765f60f4464.png">

**Comment by pglewis** [comment] 2017-07-22 19:32
Any details at all on this?  Can you reproduce in a test environment so it can be debugged?

**Comment by pglewis** [comment] 2017-07-27 04:07
Pinging @quasel...

**Comment by pglewis** [comment] 2017-08-04 05:20
I have nothing to go on here since I can't reproduce it locally... it allows me to select and save.

![works](https://user-images.githubusercontent.com/1973916/28955225-f0e4a21e-78b2-11e7-8823-ed32811762f0.jpg)

Re-open or create a new issue if there are more details.

**Comment by leepeterson** [comment] 2017-08-05 23:39
I'm actually having this same issue. I've checked the DOM and nothing saves or gets hidden. I've checked console, server and debug logs but I've found no errors.

![screen recording 2017-08-05 at 07 31 pm](https://user-images.githubusercontent.com/972141/28999435-bd5b5b5a-7a14-11e7-9a77-e5ab232616b3.gif)

WordPress Version: 4.8.1
PHP Version: 7.1.7
MySQL Version: 5.7.19
Server Software: Apache/2.4.27 (Unix) OpenSSL/1.0.2g
Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36 OPR/47.0.2631.34 (Edition beta)
Session Save Path: /srv/users/{USER}/tmp/{APPNAME}
Session Save Path Exists: Yes
Session Save Path Writeable: Yes
Session Max Lifetime: 1440
Opcode Cache:
Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:
APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_2c98704552_
WP Multisite Mode: No
WP Memory Limit: 144M
Pods Network-Wide Activated: No
Pods Install Location: /srv/users/{USER}/apps/{APPNAME}/public/wp-content/plugins/pods-2.7.0-b-1/
Pods Tableless Mode Activated: No
Pods Light Mode Activated: No
Currently Active Plugins:
Admin Columns - Pods add-on: 1.0.2
Admin Columns Pro: 4.0.7
ARI Adminer: 1.1.4
FastDev: 1.3
Feed Pull: 0.2.6
GitHub Updater: 7.0.0
Gravity Forms: 2.2.3.16
Gravity Forms REST API: 2.0-beta-2
Gravity Forms Twilio Add-On: 2.3.1
Members: 2.0.0
Pods - Custom Content Types and Fields: 2.7.0-b-2
Restsplain: 1.0.0
Revisr: 2.0.2
UpdraftPlus - Backup/Restore: 2.13.4.21
WP-SCSS: 1.2.2

**Comment by jimtrue** [comment] 2017-08-06 10:48
Need you to de-activate everything else and see if you're still getting the error, Just leave Pods activated. Neither Phil nor I can replicate this issue, so there's got to be something conflicting in there.

**Comment by jimtrue** [comment] 2017-08-06 10:53
@leepeterson Sorry should have mentioned you on the above comment. @quasel If you're still experiencing this issue, we need help narrowing it down as well.

**Comment by pglewis** [comment] 2017-08-06 16:49
@leepeterson that looks like possibly the same issue as #4288? 

If so, I hadn't mentally linked this one with the other one because "it doesn't save" misled me into thinking this was a publish/save problem and not a selection problem.

**Comment by leepeterson** [comment] 2017-08-06 17:58
@jimtrue @pglewis There's almost nothing running on the site currently since it's still very much in early development, and no errors, warnings or other obvious log data shows me what could be causing this. But one outlier here could be that I'm generating Pods posts using a modified version of Feed Pull to grab GTFS, JSON and XML data to create posts and postmeta. I think I'll spin up a new sandbox and test this again, but without Feed Pull and that post creation process.

Can you guys help clarify one thing, though? What's the difference between the Autocomplete and List types? Should they appear almost visually identical? Should they both be using Select2?

**Comment by pglewis** [comment] 2017-08-06 18:19
"Autocomplete" is basically a stock select2 implementation, "List View" uses the select2 list to select items but has a more ornate list, including icon and links to edit and display the item.  

It would be good to know if this appears to be a duplicate of #4288, I prefer to keep the troubleshooting conversation thread in one place and that one would be the one to keep open if so.  

Server logs are only going to complain about issues on the server side and I don't have any reason to suspect this is anything on the server side... so clean logs is no surprise.  

Clean console logs is a little surprising if this were a select2 version conflict but I can't completely rule that out.  

> There's almost nothing running on the site currently since it's still very much in early development

I'm seeing maybe a dozen plugins in your output above?  It would help rule out plugin conflict if you're able to turn everything off except Pods to see if it still happens.

**Comment by rob** [comment] 2017-08-07 16:59
Yes, this looks like what's happening with my issue in #4388. I also deactivated all plugins except Pods and had the same issue.

![pods](https://user-images.githubusercontent.com/503/29037128-4f203f9a-7b70-11e7-9958-405f3922f284.png)

**Comment by pglewis** [comment] 2017-08-07 17:03
I'm going to go ahead and close this one again in favor of #4388.  I know something is up but we just haven't found the right magic combination to reproduce it yet (both Jim and I have tried multiple things to recreate it without any luck)

**Closed by pglewis** 2017-08-07 17:03 UTC
Labels: Bug, Duplicate

**Comment by pglewis** [comment] 2017-08-08 21:30
#4405 should address this.
