### ISSUE TITLE
pods jquery-ui styles affecting other areas

### ISSUE THREAD

**Issue by lolli-pop** [pods-framework/pods#4639] opened 2017-12-08 18:48 UTC
Hi Pods team,

pods css jquery ui styles specifically .ui-tabs are affecting other areas.  screenshot on contact form 7 screen with pods activated and deactivated

![pods-jui-issue](https://user-images.githubusercontent.com/34381040/33780207-dbde05d0-dc04-11e7-9df7-765fdb443045.jpg)

**Comment by pglewis** [comment] 2017-12-08 18:49
Duplicate of #4612

**Closed by pglewis** 2017-12-08 18:49 UTC
