### ISSUE TITLE
Pagination not fully working with pods 2.5 and Wordpress 4.1

### ISSUE THREAD

**Issue by EliotBerriot** [pods-framework/pods#2630] opened 2015-01-21 09:36 UTC
It seems the pagination does not output correctly anymore with `echo $my_pods->pagination( array( 'type' => 'paginate' ) );`.

On the first page, everything is okay, I get:
    
    <span class="page-numbers current">1</span>
    <a class="page-numbers" href="?pg=2">2</a>
    <a class="page-numbers" href="?pg=3">3</a>
    <span class="page-numbers dots">…</span>
    <a class="page-numbers" href="?pg=5">5</a>
    <a class="next page-numbers" href="?pg=2">Next ›</a>

However, when viewing another page, each page number links to the same page. Exemple when viewing the second page:
    
    <a class="prev page-numbers" href="?pg=2">‹ Previous</a>
    <a class="page-numbers" href="?pg=2">1</a>
    <span class="page-numbers current">2</span>
    <a class="page-numbers" href="?pg=2">3</a>
    <a class="page-numbers" href="?pg=2">4</a>
    <a class="page-numbers" href="?pg=2">5</a>
    <a class="next page-numbers" href="?pg=2">Next ›</a>

You can see a [live example](http://adjemian.net/galerie/peintures/) at the bottom of the bottom of the page.

I've tested locally (with a replica of the linked website), the problem occured after I upgraded to Wordpress 4.1.

**Comment by sc0ttkclark** [comment] 2015-01-21 16:20
I've found some issues with `paginate_links` in general that produce the same problem. I wonder if something changed in WP 4.x, or if we've uncovered a bug with it.

**Comment by sc0ttkclark** [comment] 2015-01-21 16:23
The fix I had in place by the way, was to actually do this:

```php
if ( isset( $_GET[ 'pg' ] ) ) {
    $find = array( 'https://' . $_SERVER[ 'HTTP_HOST' ], 'http://' . $_SERVER[ 'HTTP_HOST' ] );

    $_SERVER[ 'REQUEST_URI' ] = str_replace( $find, '', remove_query_arg( 'pg' ) );
}
```

It's not a good hack at all, and but it seems to work for the cases which I'm using `paginate_links` normally (outside of Pods).

**Comment by EliotBerriot** [comment] 2015-01-22 07:24
Just tested locally, the bug also appear on pods 2.4.3 with Wordpress 4.1.

Thanks for your fix, it works, even with  `echo $pod->pagination( array( 'type' => 'paginate' ) );` !

**Comment by sc0ttkclark** [comment] 2015-01-22 07:48
I'm beginning to think it may be a WP core bug, I haven't narrowed things down yet, or know which WP version it was last working in. Those are probably things we'll have to follow up with.

**Comment by EliotBerriot** [comment] 2015-01-22 20:12
I don't know if it helps, but my site was previously working on Wordpress 4.0, without any problems. Don't hesitate to tell me if you need additional data.

**Comment by sc0ttkclark** [comment] 2015-01-22 20:30
Well that does help, I'll go find a diff of WP 4.0 and 4.1 in the file that handles the pagination.

**Comment by sc0ttkclark** [comment] 2015-01-22 20:34
Aha! Found it!

This is what broke it:

http://sc0tt.me/image/3u0C211J2g0F/Screen%20Shot%202015-01-22%20at%202.34.34%20PM.png

**Comment by sc0ttkclark** [comment] 2015-01-22 20:36
Core WP bug introduced by WP 4.1

Already changed and fixed too!

https://core.trac.wordpress.org/changeset/31203
https://core.trac.wordpress.org/ticket/30831

**Comment by Shelob9** [comment] 2015-01-22 20:44
Just so this is clear for anyone who finds this issue, the problem is with WordPress 4.1 and is fixed in 4.1.1.

Closing.

**Closed by Shelob9** 2015-01-22 20:44 UTC
Labels: Bug: Regression, Needs Contributor, Needs Research

**Comment by EliotBerriot** [comment] 2015-01-22 21:45
Thanks again guys, it's amazing to get fast and precise answers like these !

**Comment by sc0ttkclark** [comment] 2015-01-22 21:47
You're in good hands here :)
