### ISSUE TITLE
JS errors when using pods_ui_manage() to display forms on front end

### ISSUE THREAD

**Issue by senabean33** [pods-framework/pods#5036] opened 2018-06-13 17:52 UTC
**Describe the bug**

I am using `pods_ui_mange()` to display the manage/edit/add forms on the front end of our website.
And the Gallery image upload button is missing 
Are the related fields supposed to show up too?

<details>
<summary>View JS Errors</summary>

```
jquery.min.js:2 Uncaught TypeError: e.indexOf is not a function
    at w.fn.init.w.fn.load (jquery.min.js:2)
    at main.js?ver=1.5.4:23
w.fn.load @ jquery.min.js:2
(anonymous) @ main.js?ver=1.5.4:23
jquery.min.js:2 jQuery.Deferred exception: $(...).Pods is not a function TypeError: $(...).Pods is not a function
    at HTMLDocument.<anonymous> (https://trails.hikeitbaby.com/my-trail-networks?action1=edit&id1=3970:645:23)
    at j (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29999)
    at k (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
S @ jquery.min.js:3
jquery.min.js:2 jQuery.Deferred exception: e.indexOf is not a function TypeError: e.indexOf is not a function
    at w.fn.init.w.fn.load (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:82468)
    at HTMLDocument.<anonymous> (https://trails.hikeitbaby.com/wp-content/plugins/monarch/js/custom.js?ver=1.2:645:15)
    at l (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:29375)
    at c (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:29677) undefined
w.Deferred.exceptionHook @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
_ @ jquery.min.js:2
jquery.min.js:2 jQuery.Deferred exception: this.$el.sortable is not a function TypeError: this.$el.sortable is not a function
    at n.onAttach (https://trails.hikeitbaby.com/wp-content/plugins/pods/ui/js/pods-dfv/pods-dfv.min.js?ver=2.7.1:1:3406)
    at n.triggerMethod$1 (https://trails.hikeitbaby.com/wp-content/plugins/pods/ui/js/marionette/backbone.marionette.js?ver=3.1.0:159:21)
    at n.triggerMethod (https://trails.hikeitbaby.com/wp-content/plugins/pods/ui/js/marionette/backbone.marionette.js?ver=3.1.0:1237:31)
    at triggerMethodOn (https://trails.hikeitbaby.com/wp-content/plugins/pods/ui/js/marionette/backbone.marionette.js?ver=3.1.0:178:34)
    at constructor._attachView (https://trails.hikeitbaby.com/wp-content/plugins/pods/ui/js/marionette/backbone.marionette.js?ver=3.1.0:1435:7)
    at constructor.show (https://trails.hikeitbaby.com/wp-content/plugins/pods/ui/js/marionette/backbone.marionette.js?ver=3.1.0:1372:10)
    at n.showChildView (https://trails.hikeitbaby.com/wp-content/plugins/pods/ui/js/marionette/backbone.marionette.js?ver=3.1.0:1909:24)
    at n.onRender (https://trails.hikeitbaby.com/wp-content/plugins/pods/ui/js/pods-dfv/pods-dfv.min.js?ver=2.7.1:1:8410)
    at n.triggerMethod$1 (https://trails.hikeitbaby.com/wp-content/plugins/pods/ui/js/marionette/backbone.marionette.js?ver=3.1.0:159:21)
    at n.triggerMethod (https://trails.hikeitbaby.com/wp-content/plugins/pods/ui/js/marionette/backbone.marionette.js?ver=3.1.0:1237:31) undefined
w.Deferred.exceptionHook @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
_ @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: $(...).Pods is not a function
    at HTMLDocument.<anonymous> (my-trail-networks?action1=edit&id1=3970:645)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
(anonymous) @ my-trail-networks?action1=edit&id1=3970:645
j @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
r.readyException @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
j @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
S @ jquery.min.js:3
jquery.min.js:2 Uncaught TypeError: e.indexOf is not a function
    at w.fn.init.w.fn.load (jquery.min.js:2)
    at HTMLDocument.<anonymous> (custom.js?ver=1.2:645)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)
w.fn.load @ jquery.min.js:2
(anonymous) @ custom.js?ver=1.2:645
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
w.readyException @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
_ @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: this.$el.sortable is not a function
    at n.onAttach (file-upload-list.js:62)
    at n.triggerMethod$1 (trigger-method.js:36)
    at n.triggerMethod (view.js:181)
    at triggerMethodOn (trigger-method.js:51)
    at constructor._attachView (region.js:137)
    at constructor.show (region.js:75)
    at n.showChildView (regions.js:150)
    at n.onRender (file-upload.js:55)
    at n.triggerMethod$1 (trigger-method.js:36)
    at n.triggerMethod (view.js:181)
onAttach @ file-upload-list.js:62
triggerMethod$1 @ trigger-method.js:36
triggerMethod @ view.js:181
triggerMethodOn @ trigger-method.js:51
_attachView @ region.js:137
show @ region.js:75
showChildView @ regions.js:150
onRender @ file-upload.js:55
triggerMethod$1 @ trigger-method.js:36
triggerMethod @ view.js:181
render @ view.js:131
(anonymous) @ pods-dfv-init.js:56
each @ jquery.min.js:2
each @ jquery.min.js:2
jQuery.fn.PodsDFVInit @ pods-dfv-init.js:23
(anonymous) @ pods-dfv.js:19
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
w.readyException @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
l @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
c @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
u @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
_ @ jquery.min.js:2
```
</details>

Go to https://trails.hikeitbaby.com/my-trail-networks?action1=edit&id1=3970

**To Reproduce**

1) Go to https://trails.hikeitbaby.com/my-trail-networks?action1=edit&id1=3970

2) Scroll down to Gallery Field "Add Image" button is missing

3) Scroll down to Trails field "Add new" button is missing

Inspect to see Js errors

**Expected behavior**
The form loading on front end looks and behaves the same as the back end.

**Screenshots**

Backend screenshot
https://imgur.com/HCYSuMP

Front End screenshot
https://imgur.com/GVZP6p4

## WordPress Environment

<details>
```
Debug Information
WordPress Version: 4.9.6

PHP Version: 5.6.31-4+wpengine10

MySQL Version: 5.6.40

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: hib_5_

WP Multisite Mode: Yes

WP Memory Limit: 512M

Pods Network-Wide Activated: Yes

Pods Install Location: /nas/content/live/hikeitnew/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: HikeitBaby Subsite

Currently Active Plugins:

Admin Columns - Pods add-on: 1.0.2
Admin Columns Pro: 4.0.4
Advanced Ads: 1.8.29
Advanced Ads Pro: 1.3.1.2
Bootstrap 3 Shortcodes: 3.3.12
Custom Content Shortcode: 3.7.0
Exports and Reports: 0.7.4
Filters: 0.3
Font Awesome Shortcodes: 4.2
Gravity Forms: 2.3.2
Gravity Forms MailChimp Add-On: 4.3
Gravity Forms Webhooks Add-On: 1.1
Instagram Feed: 1.8.3
Monarch Plugin: 1.2
Page Builder by SiteOrigin: 2.5.16
Pods - Custom Content Types and Fields: 2.7.1
Pods Gravity Forms Add-On: 1.3
SiteOrigin Widgets Bundle: 1.11.2
Support System: 2.1.9.4
Tabify Edit Screen: 0.9.7
User Switching: 1.0.9
User Switching in Admin Bar: 1.1
WooCommerce: 2.6.7
WooCommerce Helper: 1.7.2
WooCommerce Memberships: 1.8.9
WP Crontrol: 1.5
WP Multisite SSO: 1.0.3
WP Smush: 2.7.6
WP User Avatar: 2.0.7
Yoast SEO: 5.5.1
```
</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.1","build":1528912332},"pods":{"3980":{"id":3980,"name":"trail_network","label":"Trail Networks","description":"","type":"post_type","storage":"table","object":"","alias":"","fields":{"featured_image":{"id":4123,"name":"featured_image","label":"Featured Image","description":"","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"1","unique":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"1","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add Photo","file_modal_title":"Attach a file","file_modal_add_button":"Add Photo","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","file_allowed_extensions":""},"city":{"id":3981,"name":"city","label":"City","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","text_repeatable":"0","text_placeholder":""},"state":{"id":3982,"name":"state","label":"State","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"us_state","pick_val":"","sister_id":"","required":"1","unique":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"center_lat":{"id":3994,"name":"center_lat","label":"Latitude","description":"","help":"","class":"","type":"number","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"number","number_format":"i18n","number_decimals":"10","number_format_soft":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"13","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","number_repeatable":"0","number_placeholder":""},"center_long":{"id":3983,"name":"center_long","label":"Longitude","description":"Area Center Longitude","help":"","class":"","type":"number","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"number","number_format":"9999.99","number_decimals":"10","number_format_soft":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"13","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","number_repeatable":"0","number_placeholder":""},"network-trails":{"id":3984,"name":"network-trails","label":"Trails","description":"","help":"","class":"","type":"pick","weight":5,"pick_object":"post_type","pick_val":"trail","sister_id":"3978","required":"0","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"autocomplete","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"30","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"gallery":{"id":3985,"name":"gallery","label":"Gallery","description":"Featured Trail Photos (6 max \/ 2M limit)","help":"","class":"","type":"file","weight":6,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","unique":"0","file_format_type":"multi","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"1","file_limit":"6","file_restrict_filesize":"2MB","file_type":"images","file_field_template":"rows","file_add_button":"Add Photo","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","file_allowed_extensions":""},"map_zoom_level":{"id":3995,"name":"map_zoom_level","label":"Map Zoom Level","description":"","help":"","class":"","type":"number","weight":7,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"slider","number_format":"i18n","number_decimals":"2","number_format_soft":"1","number_step":".25","number_min":"1","number_max":"21","number_max_length":"4","pick_post_status":["publish"],"default_value":"12","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","number_repeatable":"0","number_placeholder":""},"trail_area_features":{"id":3996,"name":"trail_area_features","label":"Trail Area Features","description":"Parking lot, hazards, restrooms, etc.","help":"","class":"","type":"pick","weight":8,"pick_object":"pod","pick_val":"trail_feature","sister_id":"3958","required":"0","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"autocomplete","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"links":{"id":4042,"name":"links","label":"Related Links","description":"","help":"","class":"","type":"pick","weight":9,"pick_object":"pod","pick_val":"partner_link","sister_id":"4041","required":"0","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"autocomplete","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"ambassador":{"id":4001,"name":"ambassador","label":"Ambassador","description":"","help":"","class":"","type":"pick","weight":10,"pick_object":"table","pick_val":"hib_7_posts","sister_id":"","pick_table":"hib_7_posts","required":"0","unique":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_table_id":"ID","pick_table_index":"ID","pick_display":"{@username.display_name}","pick_user_role":[],"pick_where":"post_type = \"ambassador\"","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_select_text":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Trail Network","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"trail_network","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_action-group":"0","built_in_taxonomies_advanced_ads_groups":"0","built_in_taxonomies_category":"0","built_in_taxonomies_difficulty":"0","built_in_taxonomies_event_type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_product_cat":"0","built_in_taxonomies_product_shipping_class":"0","built_in_taxonomies_product_tag":"0","built_in_taxonomies_product_type":"0","built_in_taxonomies_trail_feature_type":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_single":"HiB Event","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-location-alt","menu_position":"5","built_in_taxonomies_prize_type":"0"}},"pages":{"my-trail-networks":{"id":4050,"name":"my-trail-networks","code":"","type":"page","slug":"my-trail-networks","options":{"_edit_lock":"1528748517:38567","_edit_last":"38567","sponsor_url":null,"page_title":"My HiB Trail Networks","precode":"","page_template":"page-mytrailnetworks.php","pod":"trail_network","pod_slug":"","admin_only":"","restrict_role":"","roles_allowed":"","restrict_capability":"","capability_allowed":"","restrict_redirect":"","restrict_redirect_login":"","restrict_redirect_url":""}}}}
```

**Additional context**

**Possible Workaround**
If you have discovered a workaround, please include it below.

**Comment by jimtrue** [comment] 2018-06-14 15:27
Did you mean to close this one @senabean33 ? What was the resolution?

**Comment by senabean33** [comment] 2018-06-14 17:09
I think I'm actually going to reopen. I resolved the missing "Add Image" button by removing a duplicate js include for Jquery but two of the related field options are not showing up. JSON for the options is there but they don't display. Seems like it's throwing an error when it gets to where the "Add New" button would be.
![bug_related_fields](https://user-images.githubusercontent.com/20054958/41427057-8c2bb9b6-6fba-11e8-970e-6d2ddeb97236.jpg)

**Comment by jimtrue** [comment] 2018-06-14 17:34
@senabean33 If you're using custom code, you need to provide it to us as well as part of this issue.

**Comment by pglewis** [comment] 2018-06-14 17:50
> Seems like it's throwing an error when it gets to where the "Add New" button would be.

You need to check your dev tools/firebug console and find the errors and callstack reported there.

**Comment by GaryJones** [comment] 2018-06-15 04:51
@pglewis There an initial `View JS Errors` in the initial post, in case you missed it, and if that's still relevant. I put it inside a `<details>` element to make the post easier to read.

**Comment by pglewis** [comment] 2018-06-15 15:39
> @pglewis There an initial View JS Errors in the initial post, in case you missed it, and if that's still relevant. I put it inside a <details> element to make the post easier to read.

The errors there appear to be related to jQuery and the previous comment suggests a jQuery conflict was subsequently resolved, so I'm far from certain that error is current.

**Comment by senabean33** [comment] 2018-06-15 18:54
@pglewis  I resolved the duplicate jQuery  include but still get the following errors..
The last 3 fields are relationship fields & I swapped around the order to test my theory that they're error happens where the "Add New" button would be in the admin view & the first field always renders fine. The following fields are missing. Does that make sense?
![js_errors_pods_form](https://user-images.githubusercontent.com/20054958/41484623-67a8e4aa-7092-11e8-9004-9bf8d19a7ae7.PNG)

**Comment by pglewis** [comment] 2018-06-15 19:14
1. You are loading jQuery 3.3.1 somewhere.  WordPress still distrubutes version 1.x and plugins are only going to be reliably compatible with the version of jQuery that WordPress ships with.  This appears to be the cause of the `e.indexOf is not a function` errors and those seem to be emanating from somewhere else (plugins/monarch).  

1. There may be some other scripts you need to manually enqueue on the Pods side.  We normally take care of all the enqueueing but you're outside the admin and bypassing some of that.  SelectWoo (select2) appears to be one of those, and possibly `jquery.pods.js`.  I'll need to look closer at our dependencies to see what may be done there.

**Comment by senabean33** [comment] 2018-06-15 19:50
Bloody Hell. I don't know how I missed that but you are spot on --#1 fixed it. I am so damned thrilled I'm going to go donate to Pods right now. Thank so much & sorry for the non-bug issue trouble.
Have a great weekend!
![js_errors_pods_form](https://user-images.githubusercontent.com/20054958/41486731-8c73fccc-709a-11e8-9186-2f70b9e780af.PNG)

**Closed** 2018-06-15 19:59 UTC
Labels: Status: Need User Feedback

**Comment by GaryJones** [comment] 2018-06-16 16:08
> You are loading jQuery 3.3.1 somewhere. WordPress still distrubutes version 1.x

Aside: There is some movement to getting jQuery 3.x into core.

**Comment by leontdi** [comment] 2018-08-21 12:44
Sorry I have the same problem and i dont know to resolve
[ramenparados.com-1534855455132.log](https://github.com/pods-framework/pods/files/2306277/ramenparados.com-1534855455132.log)
