### ISSUE TITLE
New entry with missing info gives full page error message instead of  the in-line right of field error message

### ISSUE THREAD

**Issue by Sheriziya** [pods-framework/pods#2958] opened 2015-05-21 17:34 UTC
When you add a new pod item and you leave a "Relationship -> Simple Custom Defined, multiple select -> multi select" field empty, you'll get a full page error message instead of the in-line right of the field. When you press the back button to go back (there is no other option), the pod item is empty save for the plain text field. Even the Title is gone.

I understand this error should give an error message at the in-line right of the field, instead of the full page error message. @jimtrue adviced me to post this here, since it seems to be a bug.

This was both in the old version (2.5.1.2) and the new version (2.5.2) of Pods.

Images:
The error message as I get it now:
![podserrormessagenotinpodnewentryscreen](https://cloud.githubusercontent.com/assets/3530524/7754905/7ca3483e-fff0-11e4-919a-017bddae621b.png)

The error message as it should be (in this case with another field, not of the same type, but simply to show what I mean):
![podsexpectederrormessagedisplay](https://cloud.githubusercontent.com/assets/3530524/7754913/949ca052-fff0-11e4-945e-ca6980d81b6e.png)

**Comment by Shelob9** [comment] 2015-05-21 17:39
@Sheriziya What content type is this Pod?

**Comment by Sheriziya** [comment] 2015-05-21 18:16
Hey Josh,

It's CPT with a Table based storage.

**Comment by sc0ttkclark** [comment] 2015-05-29 19:00
Duplicate of #2424

**Closed by sc0ttkclark** 2015-05-29 19:00 UTC
Labels: Bug: Normal
