### ISSUE TITLE
Number Field Output Format For Values < 1

### ISSUE THREAD

**Issue by qrahaman** [pods-framework/pods#4686] opened 2017-12-26 20:04 UTC
I have a plain number field with the following: Format - 1234.00; Decimals - 4; Maximum Length - 12.  The field is populated via the REST API.  Issue (Pod display in Admin): When viewing the field, if the value is greater than 1 (for example, 1.634), the value displayed in Admin is 1.634 (great!).  If the value is less than 1 (for example, 0.894), the value displayed is 894.  Why?  The database captures the correct values.

**Comment by pglewis** [comment] 2018-04-12 17:06
I'm unable to reproduce this.  The scenario given works for me: 
* Manually entering values in the adming
* Programmatically with test values as strings
* Programmatically with test values as numeric values

I don't immediately see how/why the REST/API being involved would make a difference, but maybe.

**Comment by quasel** [comment] 2018-09-01 09:13
Hi, we didn't hear back from you - so I'm closing the issue!

**Closed by quasel** 2018-09-01 09:13 UTC
Labels: Status: Could not reproduce, Status: Need Research, Status: Need User Feedback
