### ISSUE TITLE
URL field format doesn't remove protocol

### ISSUE THREAD

**Issue by pagehubdesign** [pods-framework/pods#4545] opened 2017-11-02 17:37 UTC
Using the following code to display a URL field:

`[pods]{@useful_link_website}[/pods]`

If I change the field format within the additional field options tab to "example.com" or the other two options which should hide http:// or https://, the full URL still shows.

![screen shot 2017-11-02 at 11 23 08](https://user-images.githubusercontent.com/29798438/32340992-16e53b58-bff4-11e7-8494-7463f6ff63da.png)
![screen shot 2017-11-02 at 11 30 10](https://user-images.githubusercontent.com/29798438/32340995-1df33ec2-bff4-11e7-9e00-86a4f934217c.png)

Using WP 4.8.3, Pods 2.7

**Comment by pglewis** [comment] 2017-11-02 17:41
Is this possibly a duplicate of #4050?

**Comment by pagehubdesign** [comment] 2017-11-02 17:50
Don't think so. When the format is set to example.com, I can add/amend test.com or www.test.com and they display with http:// added.

**Field being added**
![screen shot 2017-11-02 at 17 48 35](https://user-images.githubusercontent.com/29798438/32341728-3610be42-bff6-11e7-83cd-818bc6677c3c.png)

**Field saved**
![screen shot 2017-11-02 at 17 48 44](https://user-images.githubusercontent.com/29798438/32341737-3df6deb6-bff6-11e7-8b6a-65460c0c8884.png)

**Front end**
![screen shot 2017-11-02 at 17 49 18](https://user-images.githubusercontent.com/29798438/32341745-46445b2a-bff6-11e7-889f-2ce6b6baf632.png)

**Comment by pagehubdesign** [comment] 2017-11-03 10:34
Reverted to 2.6.11 and can confirm that the format option works
![screen shot 2017-11-03 at 10 32 27](https://user-images.githubusercontent.com/29798438/32369784-82e3c232-c082-11e7-84ac-c2b845fb6f27.png)

**Comment by pglewis** [comment] 2017-11-07 18:45
This appears to have broken here: https://github.com/pods-framework/pods/commit/013fb6e

It's not far-fetched to guess that #4050 may be related

**Comment by JoryHogeveen** [comment] 2017-11-21 02:46
The problem is that `esc_url()` is added since the 2.7 branch.
There is also a `none` option in the code which allows for no format but it's not in the UI option.

Adding patch for:
- Add the `none` or "No format" option in the field UI
- Remove `esc_url()` since this is not compatible with our URL parser.

**Comment by pglewis** [comment] 2017-12-05 18:14
#4583 appears to fix this for me

**Comment by quasel** [comment] 2017-12-05 18:39
can confirm #4583 fixing this too although didn't test all the other combinations or Magic Tags!

**Closed** 2017-12-05 19:43 UTC
Labels: Bug, Fixed / Needs Testing, Verified/Reproduced
