### ISSUE TITLE
don't show pods in widget with [each]

### ISSUE THREAD

**Issue by hvvi** [pods-framework/pods#3571] opened 2016-06-09 05:06 UTC
I use pod participants relateshiped to users
I use template with following code:
```
[each participants]
{@display_name}
[/each]
```
as result - empty code
but if i use without [each]:
`{@participants.display_name}`
i have right result:
`alex, Globetrotter, Lolik, Lubko, skytalec, and Unforgiven`

i need to add link to each username and i don't know how

**Comment by hvvi** [comment] 2016-06-09 07:05
when i use php:
```
<?php
$param = array('limit'=>5);
$pod = pods(job_listing,$param);
$include - array();
while ($pod->fetch()){
	$include[] = $pod->field('participants'));
}
$attr = array('include' =>$include);
echo $attr;
?>
```
output: Array

**Comment by jimtrue** [comment] 2016-06-11 13:20
I'll duplicate this locally and see if I see the same issue.

**Comment by hvvi** [comment] 2016-06-14 15:03
Thanks, waiting for issue

**Comment by hvvi** [comment] 2016-07-06 07:40
any news?

**Comment by jimtrue** [comment] 2016-07-07 14:57
This is a duplicate of #3468 which was reported before your issue so closing in favor of that one. You should be able (as a workaround) get to the values of the user id's by passing them to your own php function and creating the links manually. ie, `{@participants,output_userlist}` where `output_userlist` would take the array value of `@partcipants` and loop through them outputting your link to the author's page in your php function, possibly by relating the author's id to the WP function, https://codex.wordpress.org/Function_Reference/get_author_posts_url

**Closed by jimtrue** 2016-07-07 14:57 UTC
Labels: Bug, Duplicate, Verified/Reproduced

**Comment by hvvi** [comment] 2016-07-11 08:52
solution:
<?php
$pod = pods( 'job_listing', get_the_id() );
$related = $pod->field( 'participants' );
if ( ! empty( $related ) ) {
	foreach ($related as $rel) {
		echo "<a href=\"http://beskyd.org/user/" . $rel['user_nicename'];
		echo "\">" . $rel['display_name'] . "</a> ";
	}
}

?>

**Comment by jimtrue** [comment] 2016-07-11 09:43
Sorry, should have mentioned you could always do this with PHP. This is specifically an issue with the [each] template tag and relationships to users.
