### ISSUE TITLE
ACT Reorder page - no drag and drop

### ISSUE THREAD

**Issue by bretthamm** [pods-framework/pods#2952] opened 2015-05-19 16:36 UTC
I cannot drag and drop ACT's on the reorder page. When I and drag, nothing moves. It was working before I upgraded to 2.5.2. I have all disabled plugins except Pods, deleted everything in my functions.php file, and cleared the pods cache (just incase!), but the problem persists. There are no errors in the console. Here's my debug information:

WordPress Version: 4.2.2

PHP Version: 5.6.7

MySQL Version: 5.5.42

Server Software: Apache/2.2.29 (Unix) mod_wsgi/3.4 Python/2.7.8 PHP/5.6.7 mod_ssl/2.2.29 OpenSSL/0.9.8zd DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.8 Perl/v5.20.0

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

Session Save Path: /Applications/MAMP/tmp/php

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /Users/bretth/Sites/home/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Home Base

Currently Active Plugins:

Pods - Custom Content Types and Fields: 2.5.2

**Comment by Shelob9** [comment] 2015-05-19 17:03
This is a duplicate of #2843 which we will be addressing in Pods 2.5.3

**Closed by Shelob9** 2015-05-19 17:03 UTC
