### ISSUE TITLE
Pods Field Formatting Being Removed

### ISSUE THREAD

**Issue by jklwebsites** [pods-framework/pods#6329] opened 2021-11-26 17:37 UTC
### Description

The issue I'm having is that the field formatting is being removed. For example, there's a field for Price with the formatting $5,980 but upon saving the post it renders it 5980; I can then manually format it in Custom Field and update just that field, and then it works, but if I save/update the entire post the formatting for all fields is removed again.

### Version

2.8.5

### Testing Instructions

I'm using the currency field and I've configured the Advanced Options to have the formatting. The formatting is being removed from other fields as well, such as Plain Text (with commas), and even something as simple as capitalization doesn't appear ie Manual or Gas shown in the screenshot.

Software used: WP 5.8.2, Divi 4.14.1, Pods 2.8.5

### Screenshots / Screencast

Here are some screenshots showing it working (when I manually format the field), and then not working (when I save the post it removes the formatting). Also, how the Fields are set up.

<img width="1280" alt="Screen Shot 2021-11-26 at 8 24 49 AM" src="https://user-images.githubusercontent.com/95098350/143615341-82a98f21-61a4-44bf-ad25-4e7ce248b9db.png">
<img width="1280" alt="Screen Shot 2021-11-26 at 8 25 18 AM" src="https://user-images.githubusercontent.com/95098350/143615346-6c7dc69f-4890-42a6-a4b6-f66dafe12c2c.png">
<img width="1280" alt="Screen Shot 2021-11-26 at 8 25 31 AM" src="https://user-images.githubusercontent.com/95098350/143615351-244199a1-b555-40c3-8cd9-814da01bf4aa.png">
<img width="1280" alt="Screen Shot 2021-11-26 at 8 25 40 AM" src="https://user-images.githubusercontent.com/95098350/143615352-a0cc35d9-559c-481f-937f-8f2f294a6f79.png">
<img width="1280" alt="Screen Shot 2021-11-26 at 9 13 32 AM" src="https://user-images.githubusercontent.com/95098350/143615356-b5b35e38-b1e7-4a6f-b0ef-fe7799f0330c.png">
<img width="1280" alt="Screen Shot 2021-11-26 at 9 15 02 AM" src="https://user-images.githubusercontent.com/95098350/143615357-f20f9de9-da94-48bb-ac3f-6d15a35aab26.png">

### Possible Workaround

I can then manually format it in Custom Field and update just that field, and then it works, but if I save/update the entire post the formatting for all fields is removed again.

### Site Health Information

```text
`
### wp-core ###

version: 5.8.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /wordpress
wordpress_size: 43.68 MB (45806806 bytes)
uploads_path: /www/wp-content/uploads
uploads_size: 15.83 MB (16600567 bytes)
themes_path: /www/wp-content/themes
themes_size: 45.92 MB (48153406 bytes)
plugins_path: /www/wp-content/plugins
plugins_size: 11.75 MB (12316016 bytes)
database_size: 7.31 MB (7667712 bytes)
total_size: 124.50 MB (130544507 bytes)

### wp-dropins (1) ###

db-error.php: true

### wp-active-theme ###

name: Divi (Divi)
version: 4.14.1
author: Elegant Themes
author_website: http://www.elegantthemes.com
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, custom-background, automatic-feed-links, post-thumbnails, menus, title-tag, post-formats, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, editor-style, widgets
theme_path: /www/wp-content/themes/Divi
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-One: version: 1.4, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (2) ###

Duplicate Page: version: 4.4.5, author: mndpsingh287, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 2.8.5, author: Pods Framework Team, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.5.1
file_uploads: File uploads is turned off
post_max_size: 1000M
upload_max_filesize: 1000M
max_effective_size: 1,000 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 51 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 51 GB
	imagick::RESOURCETYPE_MEMORY: 25 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.0
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: unknown
httpd_software: Flywheel/5.1.0
php_version: 7.4.26 64bit
php_sapi: fpm-fcgi
max_input_variables: 5000
time_limit: 178
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 1000M
php_post_max_size: 1000M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.36-google
client_version: mysqlnd 7.4.26

### wp-constants ###

WP_HOME: https://otas.flywheelsites.com
WP_SITEURL: https://otas.flywheelsites.com
WP_CONTENT_DIR: /www/wp-content
WP_PLUGIN_DIR: /www/wp-content/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: not writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: Flywheel/5.1.0
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
pods-session-save-path: /tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: Yes
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 5.856M
pods-memory-current-usage-real: 4.000M
pods-network-wide: No
pods-install-location: /www/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Yes
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No
pods-sessions: Disable sessions
pods-can-use-sessions: Yes

`
```

### Pods Package

```json
{
    "meta": {
        "version": "2.8.5",
        "build": 1637948140
    },
    "pods": [
        {
            "name": "vehicles",
            "id": 123,
            "label": "Vehicles",
            "description": "",
            "label_singular": "Vehicle",
            "public": "1",
            "show_ui": "1",
            "supports_title": "1",
            "supports_editor": "1",
            "type": "post_type",
            "storage": "meta",
            "publicly_queryable": "1",
            "exclude_from_search": "0",
            "capability_type": "post",
            "capability_type_custom": "car",
            "capability_type_extra": "1",
            "has_archive": "0",
            "hierarchical": "0",
            "rewrite": "1",
            "rewrite_with_front": "1",
            "rewrite_feeds": "0",
            "rewrite_pages": "1",
            "query_var": "1",
            "can_export": "1",
            "default_status": "draft",
            "supports_author": "0",
            "supports_thumbnail": "1",
            "supports_excerpt": "0",
            "supports_trackbacks": "0",
            "supports_custom_fields": "1",
            "supports_comments": "0",
            "supports_revisions": "0",
            "supports_page_attributes": "0",
            "supports_post_formats": "0",
            "built_in_taxonomies_category": "1",
            "built_in_taxonomies_link_category": "0",
            "built_in_taxonomies_post_tag": "1",
            "built_in_taxonomies_project_category": "0",
            "built_in_taxonomies_project_tag": "0",
            "show_in_menu": "1",
            "menu_position": "0",
            "show_in_nav_menus": "1",
            "show_in_admin_bar": "1",
            "pfat_enable": "0",
            "pfat_append_single": "append",
            "pfat_filter_single": "the_content",
            "pfat_append_archive": "append",
            "pfat_filter_archive": "the_excerpt",
            "pfat_run_outside_loop": "0",
            "rest_enable": "0",
            "read_all": "0",
            "write_all": "0",
            "built_in_taxonomies_wp_theme": "0",
            "_migrated_28": "1",
            "groups": [
                {
                    "name": "more_fields",
                    "id": 318,
                    "label": "More Fields",
                    "description": "",
                    "weight": 0,
                    "fields": [
                        {
                            "name": "newfeaturedsold_tag",
                            "id": 276,
                            "label": "New\/Featured\/Sold Tag",
                            "description": "",
                            "weight": 0,
                            "type": "file",
                            "required": "0",
                            "file_format_type": "single",
                            "file_uploader": "attachment",
                            "file_attachment_tab": "upload",
                            "file_upload_dir": "wp",
                            "file_edit_title": "1",
                            "file_show_edit_link": "1",
                            "file_linked": "0",
                            "file_limit": "0",
                            "file_restrict_filesize": "10MB",
                            "file_type": "images",
                            "file_field_template": "rows",
                            "file_add_button": "Add File",
                            "file_modal_title": "Attach a file",
                            "file_modal_add_button": "Add File",
                            "file_wp_gallery_output": "0",
                            "file_wp_gallery_link": "post",
                            "file_wp_gallery_columns": "1",
                            "file_wp_gallery_random_sort": "0",
                            "file_wp_gallery_size": "thumbnail",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1",
                            "unique": "0"
                        },
                        {
                            "name": "price",
                            "id": 124,
                            "label": "Price",
                            "description": "",
                            "weight": 1,
                            "type": "currency",
                            "required": "0",
                            "currency_format_type": "number",
                            "currency_format_sign": "cad",
                            "currency_format_placement": "beforeaftercode",
                            "currency_format": "9,999.99",
                            "currency_decimals": "0",
                            "currency_decimal_handling": "none",
                            "currency_step": "1",
                            "currency_min": "0",
                            "currency_max": "1000",
                            "currency_max_length": "12",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1",
                            "unique": "0",
                            "currency_repeatable": "0"
                        },
                        {
                            "name": "transmission",
                            "id": 125,
                            "label": "Transmission",
                            "description": "",
                            "weight": 2,
                            "type": "pick",
                            "required": "1",
                            "pick_format_type": "single",
                            "pick_format_single": "dropdown",
                            "pick_format_multi": "checkbox",
                            "pick_display_format_multi": "default",
                            "pick_display_format_separator": ", ",
                            "pick_allow_add_new": "1",
                            "pick_taggable": "0",
                            "pick_show_icon": "1",
                            "pick_show_edit_link": "1",
                            "pick_show_view_link": "1",
                            "pick_limit": "0",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1",
                            "unique": "0",
                            "pick_object": "custom-simple",
                            "pick_custom": "manual|Manual\nautomatic|Automatic"
                        },
                        {
                            "name": "fuel",
                            "id": 231,
                            "label": "Fuel",
                            "description": "",
                            "weight": 3,
                            "type": "pick",
                            "required": "1",
                            "pick_format_type": "single",
                            "pick_format_single": "dropdown",
                            "pick_format_multi": "checkbox",
                            "pick_display_format_multi": "default",
                            "pick_display_format_separator": ", ",
                            "pick_allow_add_new": "1",
                            "pick_taggable": "0",
                            "pick_show_icon": "1",
                            "pick_show_edit_link": "1",
                            "pick_show_view_link": "1",
                            "pick_limit": "0",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1",
                            "unique": "0",
                            "pick_object": "custom-simple",
                            "pick_custom": "gas|Gas\ndiesel|Diesel\nhybrid|Hybrid\nelectric|Electric"
                        },
                        {
                            "name": "kilometres",
                            "id": 232,
                            "label": "Kilometres",
                            "description": "",
                            "weight": 4,
                            "type": "number",
                            "required": "1",
                            "number_format_type": "number",
                            "number_format": "9,999.99",
                            "number_decimals": "0",
                            "number_format_soft": "0",
                            "number_step": "1",
                            "number_min": "0",
                            "number_max": "100",
                            "number_max_length": "12",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1",
                            "unique": "0",
                            "number_repeatable": "0"
                        },
                        {
                            "name": "body_type",
                            "id": 233,
                            "label": "Body Type",
                            "description": "",
                            "weight": 5,
                            "type": "pick",
                            "required": "1",
                            "pick_format_type": "single",
                            "pick_format_single": "dropdown",
                            "pick_format_multi": "checkbox",
                            "pick_display_format_multi": "default",
                            "pick_display_format_separator": ", ",
                            "pick_allow_add_new": "1",
                            "pick_taggable": "0",
                            "pick_show_icon": "1",
                            "pick_show_edit_link": "1",
                            "pick_show_view_link": "1",
                            "pick_limit": "0",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1",
                            "unique": "0",
                            "pick_object": "custom-simple",
                            "pick_custom": "car|Car\ntruck|Truck\nminivan|Minivan\nsuv|SUV"
                        },
                        {
                            "name": "engine",
                            "id": 234,
                            "label": "Engine",
                            "description": "",
                            "weight": 6,
                            "type": "pick",
                            "required": "1",
                            "pick_format_type": "single",
                            "pick_format_single": "dropdown",
                            "pick_format_multi": "checkbox",
                            "pick_display_format_multi": "default",
                            "pick_display_format_separator": ", ",
                            "pick_allow_add_new": "1",
                            "pick_taggable": "0",
                            "pick_show_icon": "1",
                            "pick_show_edit_link": "1",
                            "pick_show_view_link": "1",
                            "pick_limit": "0",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1",
                            "unique": "0",
                            "pick_object": "custom-simple",
                            "pick_custom": "4cyl|4 Cylinder\nv6|V6\nv8|V8\nv10|V10\nelectric|Electric"
                        },
                        {
                            "name": "photos",
                            "id": 257,
                            "label": "Photos",
                            "description": "",
                            "weight": 7,
                            "type": "file",
                            "required": "1",
                            "file_format_type": "multi",
                            "file_uploader": "attachment",
                            "file_attachment_tab": "upload",
                            "file_upload_dir": "wp",
                            "file_edit_title": "1",
                            "file_show_edit_link": "0",
                            "file_linked": "0",
                            "file_limit": "0",
                            "file_restrict_filesize": "10MB",
                            "file_type": "images",
                            "file_field_template": "rows",
                            "file_add_button": "Add File",
                            "file_modal_title": "Attach a file",
                            "file_modal_add_button": "Add File",
                            "file_wp_gallery_output": "0",
                            "file_wp_gallery_link": "post",
                            "file_wp_gallery_columns": "1",
                            "file_wp_gallery_random_sort": "0",
                            "file_wp_gallery_size": "thumbnail",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1",
                            "unique": "0",
                            "sister_id": "-- Select One --"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by sc0ttkclark** [comment] 2021-11-28 03:45
@jklwebsites What are you doing to output that field? Is that using a shortcode, block, pod template, or something else? Are there any details you can provide there?

**Comment by jklwebsites** [comment] 2021-11-30 19:15
Hi @sc0ttkclark, thanks for looking into this. I'm using a Divi module with dynamic content to output those fields - screenshot attached.

<img width="1280" alt="Screen Shot 2021-11-30 at 11 09 41 AM" src="https://user-images.githubusercontent.com/95098350/144112662-559985c0-f3a4-49d2-9b3b-0de18470fd38.png">

**Comment by JoryHogeveen** [comment] 2021-12-01 10:34
This is actually not a bug.
We store numeric fields unformatted, only on display are they formatted into the format of choice.

Divi in this case only renders raw metadata and doesn't support auto-formatters of any plugin.

**Comment by sc0ttkclark** [comment] 2021-12-01 16:32
I can take a look and see if there's anything I can do to filter this in the Pods Pro Page Builder Toolkit integration for Divi.

**Comment by jklwebsites** [comment] 2021-12-02 16:23
Thanks @JoryHogeveen and @sc0ttkclark, I appreciate your input on this. Yes, if there is a solution such as using the Pods Pro Page Builder Toolkit, please let me know. This is the response that I got from Elegant Themes regarding the Field formatting and taxonomies in Custom Posts; it's disappointing that Pods & Divi don't seem to work well together yet:

"1) ACF number field doesn't support formatting. Please try this solution https://support.advancedcustomfields.com/forums/topic/insert-commas-into-acf-number-field/

2) Blog module doesn't show the taxonomies of CPT. I will forward this feature request to our development team for consideration."

**Comment by jklwebsites** [comment] 2022-01-04 21:33
Hi Guys, just wanted to provide an update here in case it helps you or others.

I didn't change anything on Divi's end, and they said that this was an issue on the plugin end

> This is actually not a bug. We store numeric fields unformatted, only on display are they formatted into the format of choice.
> 
> Divi in this case only renders raw metadata and doesn't support auto-formatters of any plugin.

Hi Guys, I wanted to provide an update here in case it helps you or others with a similar problem. I didn't change anything on Divi's end, I purchased your Pods Pro and uploaded the Page Builder Toolkit add-on, then refreshed the page and the formatting worked! I'm happy that it works properly now and that I didn't have to re-do any of the dynamic fields, but I don't understand your comment about "[Divi] doesn't support auto-formatters", yet once I uploaded the additional functionality for your Pods plugin it did work - which leads me to conclude that the issue was on the plugin's end not Divi's - is that correct? Maybe I'm misunderstanding and you could please explain.

Either way, thank you for all of your efforts in developing Pods! I'm happy to pay for the Pro version.

**Comment by JoryHogeveen** [comment] 2022-01-07 09:34
Hi @jklwebsites 

Pods formats using the default WP methods, we do not include specific Page Builder code.
If the page builder uses the WP core methods for getting metadata (with the use of WP core's filters) it should work out of the box. If not, like the case is with Divi, it probably uses raw metadata.

The Pods Page Builder toolkit targets specific page builders with compatibility code. So this plugin operates outside of the default WP core methods and hooks into specific plugin methods to create compatibility.

So the difference is that is the builder is following WordPress core methods including it's core filters, it will be compatible, otherwise it won't and will require addons for compatibility.

**Comment by sc0ttkclark** [comment] 2022-01-21 23:06
The Pods Pro by SKCDEV Page Builder Toolkit Add-On was built to create and improve integration with Page Builders + Pods. In some areas, we add new integrations and in others we improve existing integrations that may already live in a Page Builder like Divi.

Looks like the issue is solved by using the Page Builder Toolkit Add-On so I'm going to close this for now.

In the future, if we get enough funding we can merge the Page Builder Toolkit Add-On into Pods core but due to the time involved in maintaining compatibility and supporting that Add-On, it's not going to be a simple process.

**Closed by sc0ttkclark** 2022-01-21 23:06 UTC
Labels: Type: Bug, Focus: Other Compatibility
