### ISSUE TITLE
GROUP BY not respecting the ORDER BY for related fields

### ISSUE THREAD

**Issue by mike200015** [pods-framework/pods#4459] opened 2017-09-08 21:27 UTC
When running a find() with a GROUP BY on a related field, and an ORDER BY, the GROUP BY is being run before the ORDER BY, causing incorrect grouped results. 

For example, with two Pods:
1. Product
2. Review - has relationship field for Product

If you want to find the most recent Review for each Product, you should be able to run a query with the params below:
```
$params = array(
        'groupby' => 'related_product.ID',
        'orderby' => 't.post_date DESC'
    );
```
This does not produce the expected results, as the groupby is happening before the orderby, and as such the results do not give the most recent Review for each related_product.

**Comment by sc0ttkclark** [comment] 2017-09-08 21:35
This is a common MySQL issue, it's problematic :(

Best way to alleviate it is to add a new `'select' => 't.*, MAX( t.post_date ) AS most_recent_date'` and then modify your orderby to `'orderby' => 'most_recent_date DESC'`.

The problem is rooted in GROUP BY grouping the records but not properly choosing exactly which rows to give you access to in each grouped row as you are expecting to be able to in the ORDER BY.

**Comment by sc0ttkclark** [comment] 2017-09-08 21:36
Closing issue, let us know if you have any further troubles.

**Comment by mike200015** [comment] 2017-09-08 21:59
Thanks for the reply. I've tried your suggestion but it is still not producing the correct results. Maybe it has to do with the fact it's grouping by a realted field, but we're trying to sort by a field on the main table?

**Comment by sc0ttkclark** [comment] 2017-11-29 21:02
I apologize for the late response, but unfortunately this is not something we can support within Pods itself. This is a MySQL limitation which has to be approached by a custom select as suggested previously. I might not have had the exact select query correct for your use case, but you'll need to seek help with the MySQL side of this.

To clarify my previous message, you'll still need to group by the field you were before.

**Closed by sc0ttkclark** 2017-11-29 21:02 UTC
Labels: Docs Improvements
