### ISSUE TITLE
utf8mb4_general_ci vs utf8_general_ci Can't mix collation types?

### ISSUE THREAD

**Issue by qrahaman** [pods-framework/pods#4809] opened 2018-03-23 18:15 UTC
## Issue Overview

The default database collation for new WordPress installs is utf8mb4_general_ci.  It would appear that PODS for custom tables sets the collation to utf8_general_ci

## Steps to Reproduce (for bugs)
I am using wpdatatables to create "tables" that are used to feed Highcharts.  All of my tables and charts worked until yesterday.  Two of the charts would not display which is due to two wpdatatables producing an error: mix of collation types.  The wpdatatable is pulling from a MySQL VIEW.  One of those fields in the VIEW is from a custom PODS table with a collation of utf8_general_ci.

I am assuming that this difference is what generates the error.

**Comment by Ramoonus** [comment] 2018-03-24 10:33
i know default formatting can be edited in wp-config and in the database (for new tables) 
so we have 2 locations we need to verify 
and fallback if this encoding cannot be found

**Comment by quasel** [comment] 2018-08-31 21:25
Duplicate of #2834 - and WordPress uses `utf8mb4_unicode_520_ci` but yep can be an issue but there are plugins out there to fix that or a DB Query should be easy in most of the cases!

**Closed by quasel** 2018-08-31 21:25 UTC
Labels: Closed: Duplicate, Type: Bug
