### ISSUE TITLE
Set dimensions on image field, so users have to crop to set dimensions on upload.

### ISSUE THREAD

**Issue by jbotte** [pods-framework/pods#1105] opened 2013-03-01 20:58 UTC
When creating a custom pod for authors on my site, it would be useful to be able to set dimensions on the image field. If dimensions are set, once the image is uploaded, it would be nice to use jcrop and force the dimensions for user driven cropping. 

For instance if there was a custom post type for staff and the admin intended to display staff headshots in 100x100 on the front end, when someone writes a new staff post, they would be prompted to crop out a 100x100 portion of the image, and the jcrop tool could force the 1:1 aspect ratio. This would be an improvement upon forcing an automatic crop since this would ensure the user selected the part of the image they want shown, instead of auto cropping a torso instead of the head by accident. 

Best example would be shown here, the crop tool is forcing a 1x1 aspect ratio, jcrop also allows max width and height settings. http://deepliquid.com/projects/Jcrop/demos/tutorial3.html

**Comment by webxolutions** [comment] 2015-05-12 23:00
Hey Pods Peeps,

Just wondering if this has been developed or implemented, as I am currently seeking a similar solution to provide cropping on image upload for dimension-specific areas. (Rather than a secondary step after upload, via a plugin or the WP Edit Media (image editor action).

I found a way to hard-code the dimension, but this won't allow a user to select what area to crop:
http://blog.stefanxo.com/2013/08/display-thumbnails-with-pods/

Thanks!

**Comment by pglewis** [comment] 2016-01-24 05:21
Is this a dupe of or solve by #615?

**Comment by jbotte** [comment] 2016-01-24 16:25
yea i was looking for the same thing as 615 when i filed this many moons ago.

**Closed** 2016-01-24 17:40 UTC
Labels: Duplicate, Needs Contributor, Needs Research, Needs Tasklist, Plugin Material
