### ISSUE TITLE
Backend - position defaults to first multiselect field on entering Edit Pod CPT

### ISSUE THREAD

**Issue by Brian-Milnes** [pods-framework/pods#4703] opened 2018-01-09 13:17 UTC
When you edit a Pod created CPT, the position of entry is determined by the first multiselect field, rather than stay at the the top of the edit page.

**Comment by jimtrue** [comment] 2018-03-17 12:33
Duplicate of #4725

**Closed by jimtrue** 2018-03-17 12:33 UTC
