### ISSUE TITLE
Problem with empty lines in dropdown of relationship

### ISSUE THREAD

**Issue by aschulze1969** [pods-framework/pods#5765] opened 2020-07-04 21:52 UTC
**Describe the bug**
Hello,
We had the same issues with showing `&nbsp;` instead of an tab/indent as described in the issue #5753
After update to 2.7.21 the dropdown with the relationship shows nothing for hierachical items. Only the items of the first level will be shown. All lines with the second or third levels are completly empty. Now it is impossible to select the correct item.
The field is a relationship to a taxonomie defined in pods.
After the update of pods I have cleared the browser cache. The issue comes with chrome and edge. In both browsers the same behavior.

We need a quick solution :-)

**Screenshots**
![error](https://user-images.githubusercontent.com/67761389/86521220-1f4ba880-be4e-11ea-98c4-4765f6f703d8.png)

## Pods Version
2.7.21

## WordPress Environment

<details>
`
### wp-core ###

version: 5.4.2
site_language: de_DE
user_language: de_DE
timezone: Europe/Berlin
permalink: /%year%/%monthnum%/%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 6
dotorg_communication: true

### wp-active-theme ###

name: Septera (septera)
version: 1.5.0
author: Cryout Creations
author_website: http://www.cryoutcreations.eu
parent_theme: none
theme_features: editor-style, title-tag, automatic-feed-links, html5, post-formats, custom-background, custom-logo, menus, post-thumbnails, custom-header, responsive-embeds, editor-color-palette, editor-font-sizes, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets
theme_path: ...

### wp-plugins-active (23) ###

Admin Columns Pro: version: 5.2, author: AdminColumns.com
Admin Columns Pro - Pods: version: 1.5, author: AdminColumns.com
Colored Admin Post List: version: 2.1, author: Stevie
Cryout Serious Slider: version: 1.2.0, author: Cryout Creations
Default Startup Folder for Real Media Library: version: 1.0.5, author: Matthias Günter
Duplicator: version: 1.3.34, author: Snap Creek (latest version: 1.3.36)
Google XML Sitemaps: version: 4.1.0, author: Arne Brachhold
Gwolle Guestbook: version: 4.0.2, author: Marcel Pol (latest version: 4.0.4)
Improved Save Button: version: 1.2.1, author: Label Blanc
Pods - Custom Content Types and Fields: version: 2.7.21, author: Pods Framework Team
Post Expirator: version: 2.4.0.1, author: Aaron Axelsen
Responsive Lightbox & Gallery: version: 2.2.3.1, author: dFactory
Shortcodes Ultimate: version: 5.9.0, author: Vladimir Anokhin (latest version: 5.9.2)
TinyMCE Advanced: version: 5.4.0, author: Andrew Ozz
UpdraftPlus - Backup/Restore: version: 1.16.25, author: UpdraftPlus.Com, DavidAnderson (latest version: 1.16.26)
User Role Editor: version: 4.53.1, author: Vladimir Garagulya (latest version: 4.55.1)
WP Dashboard Notes: version: 1.0.9, author: Jeroen Sormani
WP External Links: version: 2.46, author: WebFactory Ltd
WPForms Lite: version: 1.6.0.2, author: WPForms (latest version: 1.6.1)
WP Mailto Links - Hide & Protect Emails: version: 3.1.2, author: Ironikus
WP Real Media Library: version: 3.4.2, author: Matthias Günter
WP Statistics: version: 12.6.13, author: VeronaLabs
Öffnungszeiten Tierheim Hildesheim: version: 0.1, author: Andreas Schulze

### wp-plugins-inactive (2) ###

Force Regenerate Thumbnails: version: 2.0.6, author: Pedro Elsner
Loco Translate: version: 2.4.0, author: Tim Whitlock

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-47 Q16 x86_64 2019-05-28 https://imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 765 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 192
	imagick::RESOURCETYPE_MAP: 765 GB
	imagick::RESOURCETYPE_MEMORY: 383 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: SunOS localhost 5.10 Generic_150401-49 i86pc SunOS localhost 5.10 Generic_150401-49 i86pc SunOS localhost 5.10 Generic_150401-49 i86pc
httpd_software: Apache/2.4.43 (Unix)
php_version: 7.4.6
php_sapi: cgi-fcgi
max_input_variables: 4000
time_limit: 240
memory_limit: 256M
max_input_time: 60
upload_max_size: 64M
php_post_max_size: 76M
curl_version: 7.54.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.6.42-log
client_version: 5.5.54

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: ...
WP_PLUGIN_DIR: ...
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### wpforms ###

version: 1.6.0.2
license: false
lite: Jan 16, 2019 @ 11:30am
total_forms: 1
total_entries: 161

### pods ###

pods-server-software: Apache/2.4.43 (Unix)
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
pods-session-save-path: 2;/var/tmp
pods-session-save-path-exists: No
pods-session-save-path-writable: No
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 20,628M
pods-memory-current-usage-real: 8,000M
pods-network-wide: No
pods-install-location: /mnt/web406/.../wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`</details>

**Comment by JoryHogeveen** [comment] 2020-07-06 12:26
Hello @aschulze1969 

I cannot reproduce this behavior. Can you share more about your installation?
What is the relationship? Is it a custom simple relationship? Or to a post type? A taxonomy?

Cheers, Jory

**Comment by aschulze1969** [comment] 2020-07-06 14:55
Hello Jory,
the relationship is a taxonomy created with pods.
![relationship](https://user-images.githubusercontent.com/67761389/86603441-49af7a00-bfa4-11ea-92bc-d5ffa28c138f.png)

The developertools from chrome shows this html:
![htmlcode](https://user-images.githubusercontent.com/67761389/86603589-7794be80-bfa4-11ea-94a2-5732473ef247.png)
The levels 2 and 3 are empty.

This is the export of the posttype an the taxonomy:
<details>
`{"meta":{"version":"2.7.21","build":1594042006},"pods":{"126":{"id":126,"name":"rasse","label":"Rasse","description":"","type":"taxonomy","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Rasse","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"rasse","query_var":"0","sort":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_post":"0","built_in_post_types_attachment":"0","menu_location":"default","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"1","pfat_enable":"1","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0","expirationdate_year":"2019","expirationdate_month":"05","expirationdate_day":"21","expirationdate_hour":"23","expirationdate_minute":"11","expirationdate_formcheck":"true","expirationdate_expiretype":"draft","label_add_new_item":"Rasse hinzufügen","label_edit_item":"Rasse bearbeiten","label_update_item":"Rasse bearbeiten","label_all_items":"Alle Rassen","label_search_items":"Rasse suchen","built_in_post_types_mitarbeiter":"0","built_in_post_types_rl_gallery":"0","built_in_post_types_user_request":"0","built_in_post_types_amn_wpforms-lite":"0","built_in_post_types_wpforms":"0","built_in_post_types_wpforms_log":"0","built_in_post_types_tier":"1","built_in_post_types_fragenundantworten":"0","built_in_post_types_cryout_serious_slide":"0","built_in_post_types_wp_block":"0","menu_name":"Rassen","built_in_post_types_ffnungszeiten":"0","built_in_post_types_oeffnungszeiten":"0","built_in_post_types_link":"0","built_in_post_types_termin":"0","built_in_post_types_testpost":"0"},"113":{"id":113,"name":"tier","label":"Tiere","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"tiername":{"id":151,"name":"tiername","label":"Name","description":"Name des Tiers","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"gruppe":{"id":823,"name":"gruppe","label":"Gruppe","description":"In welcher Gruppe soll das Tier angezeigt werden?","help":"","class":"","type":"pick","weight":1,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"Hund\nKatze\nKatzenwiese\nKleintier\nSorgenkind\nVermittelt auf Probe\nPrivatvermittlungen","required":"1","oembed_enabled_providers_collegehumorcom":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"2","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"rel_rasse":{"id":175,"name":"rel_rasse","label":"Rasse","description":"Um welche Rasse handelt es sich bei dem Tier?","help":"","class":"","type":"pick","weight":2,"pick_object":"taxonomy","pick_val":"rasse","sister_id":"","required":"0","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"beschreibung":{"id":177,"name":"beschreibung","label":"Beschreibung","description":"Ausführliche Beschreibung des Tiers","help":"","class":"","type":"wysiwyg","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","wysiwyg_editor":"tinymce","wysiwyg_media_buttons":"1","wysiwyg_oembed":"0","wysiwyg_wptexturize":"1","wysiwyg_convert_chars":"1","wysiwyg_wpautop":"1","wysiwyg_allow_shortcode":"1","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","wysiwyg_repeatable":"0","wysiwyg_editor_height":"","wysiwyg_allowed_html_tags":""},"geschlecht":{"id":116,"name":"geschlecht","label":"Geschlecht","description":"Geschlecht und Status der Kastration","help":"","class":"","type":"pick","weight":4,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"männlich\nweiblich\nmännlich kastriert\nweiblich kastriert\nmännlich und weiblich\nmännlich kastriert und weiblich\nmännlich kastriert und weiblich kastriert\nmännlich und weiblich kastriert","required":"0","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"fundtier":{"id":117,"name":"fundtier","label":"Fundtier","description":"Fundtier oder Eigenabgabe?","help":"","class":"","type":"pick","weight":5,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"Fundtier\nEigenabgabe","required":"0","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"fundort":{"id":127,"name":"fundort","label":"Fundort","description":"Bei Fundtier: Fundort, sonst leer","help":"","class":"","type":"text","weight":6,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"abgabedatum":{"id":129,"name":"abgabedatum","label":"Abgabedatum","description":"Datum der Abgabe","help":"","class":"","type":"date","weight":7,"pick_object":"","pick_val":"","sister_id":"","required":"0","date_type":"wp","date_format":"mdy","date_allow_empty":"1","date_html5":"0","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","date_repeatable":"0","date_format_custom":"","date_format_custom_js":"","date_year_range_custom":""},"id_fundtierverwaltung":{"id":130,"name":"id_fundtierverwaltung","label":"ID Fundtierverwaltung","description":"ID der Fundtierverwaltung","help":"","class":"","type":"text","weight":8,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"50","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"fotos":{"id":131,"name":"fotos","label":"Fotos","description":"","help":"","class":"","type":"file","weight":9,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"multi","file_uploader":"attachment","file_attachment_tab":"browse","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"20","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"1","file_wp_gallery_link":"file","file_wp_gallery_columns":"2","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"medium_large","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"koerpergroesse":{"id":152,"name":"koerpergroesse","label":"Körpergröße\/Gewicht","description":"","help":"","class":"","type":"text","weight":10,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"kinderlieb":{"id":153,"name":"kinderlieb","label":"Kinderlieb","description":"","help":"","class":"","type":"pick","weight":11,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"\nja\nnein\nja, aber nur große Kinder\n","required":"0","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"andere_tiere":{"id":154,"name":"andere_tiere","label":"andere Tiere","description":"","help":"","class":"","type":"pick","weight":12,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"\nja\nnein\nbedingt\nnur Hunde\nnur Katzen","required":"0","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_display_format_multi":"default","pick_display_format_separator":", ","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"geburtsdatum":{"id":155,"name":"geburtsdatum","label":"Geburtsdatum","description":"","help":"","class":"","type":"text","weight":13,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"50","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_photobucketcom":"0","oembed_enabled_providers_polldaddycom":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"reserviert":{"id":4859,"name":"reserviert","label":"Reserviert","description":"","help":"","class":"","type":"boolean","weight":14,"pick_object":"","pick_val":"","sister_id":"","required":"0","pick_post_status":["publish"],"boolean_format_type":"checkbox","boolean_yes_label":"Ja","boolean_no_label":"Nein","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2"}},"show_in_menu":"1","label_singular":"Tier","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"tier","capability_type_extra":"1","has_archive":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"1","pfat_run_outside_loop":"1","pfat_append_single":"replace","pfat_filter_single":"the_content","pfat_append_archive":"replace","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","expirationdate_year":"2020","expirationdate_month":"06","expirationdate_day":"17","expirationdate_hour":"10","expirationdate_minute":"33","expirationdate_formcheck":"true","expirationdate_expiretype":"draft","pfat_single":"Detailansicht Tiere","pfat_archive":"Tiere Übersicht","built_in_taxonomies_wpforms_log_type":"0","built_in_taxonomies_cryout_serious_slider_category":"0","label_add_new":"Tier hinzufügen","label_add_new_item":"Tier hinzufügen","label_new_item":"Tier hinzufügen","label_edit_item":"Tier bearbeiten","label_view_item":"Tier ansehen","label_view_items":"Tiere ansehen","label_all_items":"Alle Tiere","label_search_items":"Tier suchen","built_in_taxonomies_rasse":"1","label_featured_image":"Vorschaufoto","label_set_featured_image":"Vorschaufoto wählen","label_remove_featured_image":"Vorschaufoto entfernen","label_use_featured_image":"Benutze als Vorschaufoto","menu_position":"0","built_in_taxonomies_testtaxo":"0"}}}`
</details>

My next steps was:
- clear the pods cache: no result
- I added a new posttype with pods and added a relationship to the old taxonomy: the same result: lines are empty
- I added a new taxonomy with some entries and levels. I added this to the new posttype: the same result: lines are empty
![new post an taxonomy](https://user-images.githubusercontent.com/67761389/86604674-fa6a4900-bfa5-11ea-9ae7-42388ede3ed7.png)

and the same html-code:
![htmlcode2](https://user-images.githubusercontent.com/67761389/86604796-1ec62580-bfa6-11ea-9abb-c10d88d0abac.png)

With 2.7.20.1 comes the issues with showing `&nbsp;` instead of an tab/indent as described in the issue #5753 and with 2.7.21 the lines are empty !?
The PHP-Version is 7.4.6

Best regards
Andreas Schulze

**Comment by JoryHogeveen** [comment] 2020-07-06 16:12
Hmm, weird, I cannot reproduce your issue on my local installation.
Even if I use the same names for my categories they show up nicely.

Not sure but this might be a plugin/theme conflict.
Could you check? https://docs.pods.io/faqs/plugin-theme-conflicts/

Let me know!

**Comment by aschulze1969** [comment] 2021-01-03 15:22
After update to version 2.7.25 all items are visible, but with three "?" for each level...

![image](https://user-images.githubusercontent.com/67761389/103482178-9b17b500-4ddf-11eb-8893-bb1887c4bf1a.png)

**Comment by JoryHogeveen** [comment] 2021-01-04 14:09
Hi @aschulze1969 

I checked locally and still cannot reproduce your issue.
In my case I just see the spacing, not the question marks...
Might be a long shot, but what browser and version are you using?

**Comment by JoryHogeveen** [comment] 2021-02-01 10:19
Closing issue due to no reply!

**Closed by JoryHogeveen** 2021-02-01 10:19 UTC
Labels: Status: Need Reproduction, Status: Need User Feedback, Type: Bug
