### ISSUE TITLE
Varnish caching issue

### ISSUE THREAD

**Issue by OceanWind** [pods-framework/pods#4325] opened 2017-06-24 23:19 UTC
Jim True in the chat room suggested I submit a bug report on this. Our site is hosted at Dreamhost on their custom WP hosting solution, Dreampress. In addition to other optimization features, it uses Varnish and to cache the site.

However, **PODS is disabling Varnish's ability to cache** because of the following:

- setting a **PHPSESSID cookie on every pageload**. This makes Varnish not deliver cached pages.
- setting the **header Cache-Control to "no-cache"** which means visitors will never get cached pages.
- setting the **header Pragma to "no-cache"** which means visitors will never get cached pages.

I've attached a screenshot of the report on the Varnish Status page. I've conclusively determined that PODS is causing this issue.

Thanks! 
(btw, **PODS is awesome**)

![screen shot 2017-06-24 at 5 15 45 pm](https://user-images.githubusercontent.com/7664120/27512531-cee6b476-5900-11e7-9427-72df3cd8092b.png)

**Comment by Ramoonus** [comment] 2017-06-25 08:38
I`m wondering how Dreamhost` cache is causing some of these issues

**Comment by OceanWind** [comment] 2017-06-25 18:18
I think it's less to do with Dreamhost and more to do with Varnish. Seems like it has to do with PODS setting no-cache headers and session_ids on every page. Lots of articles on how this conflicts with Varnish:

No Cache Headers & Varnish
https://duckduckgo.com/?q=varnish+cache+no+cache+header

Session IDs & Varnish
https://duckduckgo.com/?q=varnish+session+ID

But I get that PODS might need these for some reason. Perhaps there could be an option to use cookies for session persistence instead and to turn off the no-cache header, leaving that to the user to configure manually in their cache server...?

**Comment by OceanWind** [comment] 2017-07-23 16:07
Just curious if this is being looked into. What needs to happen is that PODS does not automatically set no-cache headers and load session IDs into every page.

If these could be turned into options that could be managed through the PODS settings, it should fix the problem. For example, you could add two options to the PODS settings:

1. **Disable no-cache headers** (with a warning that this could affect currency of data being displayed).
1. **Use cookies instead of hard-coded session IDs**.

That should fix the issue. I can only guess that the Varnish caching engine is not the only caching app that this affects...

**Comment by zackeryfretty** [comment] 2017-08-30 16:56
I also can confirm that this is an issue with Dreamhost (specifically Dreampress) - has there been any movement as far as a solution? 

I'll be reaching out to Dreamhost's support later today to see if they can help at all, will report back if there's some sort of setting they can tweak on their end for a short term fix.

**Comment by flberger** [comment] 2021-04-07 12:29
I just got hit by this issue. I am running WordPress 5.7 + Pods 2.7.26 , and I am setting up NGINX in front of that as a speed up / failover cache. I can confirm @OceanWind 's issue that Pods adds a `PHPSESSID` cookie, a `Cache-Control: no-cache` header, and a `Pragma: no-cache` on *every* request. This not only disables Varnish caching, it disables *any* sane cache in front of WP + Pods whatsoever.

It's curious that this has not been fixed in 3+ years, especially since to me there seem to be no apparent reasons for Pods to mess with caching headers without being told so.

@OceanWind 's proposed solution

> you could add two options to the PODS settings:
>  1. Disable no-cache headers (with a warning that this could affect currency of data being displayed).
>  2. Use cookies instead of hard-coded session IDs.

looks reasonable and effective to me.

A fix would be very appreciated.

@Ramoonus Bug title could probably be changed from "Varnish caching issue" to "HTTP headers cause caching issues", as this is not Varnish-specific.

**Comment by sc0ttkclark** [comment] 2021-08-03 14:43
Disabling sessions in Pods solves the problem generally, which can trigger these kinds of headers. Add this to your wp-config.php file:

`define( 'PODS_SESSION_AUTO_START', false );`

Sessions are used by Pods with our public forms feature to further secure what fields are allowed to be saved from a form when someone is not logged in. If you don't use that, you can disable it.

We are working on #5600 to address this further and hopefully come up with a more flexible solution that does not default to on.

**Comment by sc0ttkclark** [comment] 2021-10-06 02:00
Caching is defaulted to off now in Pods 2.8 🎉

**Closed by sc0ttkclark** 2021-10-06 02:00 UTC
Labels: Type: Bug
