### ISSUE TITLE
Pods Template editor can not resize

### ISSUE THREAD

**Issue by pierluigiabramo** [pods-framework/pods#4589] opened 2017-11-29 16:59 UTC
Clean WP install
WP 4.9 but also in 4.8.3
PODS 2.7 RC1 (Not happen in 2.6.11)
PHP 7.1.11 but also in 5.6.32

Tested in Firefox, Chrome & Safari all last versions
![schermata 2017-11-29 alle 17 47 56](https://user-images.githubusercontent.com/17725824/33387900-c1fd27fe-d52e-11e7-9a1e-86521807046c.png)

**Comment by jimtrue** [comment] 2017-11-29 18:47
@pierluigiabramo Can you check your Javascript console on those browsers to see if there's any errors? I'm not seeing this on my locals, but CodeMirror would be the likely culprit.

**Comment by JoryHogeveen** [comment] 2017-11-30 02:08
This is definitely a JS issue. Can't reproduce but could be related to the CodeMirror included in WP core since 4.9?

**Comment by jimtrue** [comment] 2017-11-30 02:14
If we're unable to replicate, we're definitely going to need the error to troubleshoot. Concerned that we're not able to replicate. Wonder if it has to do with already having the library in place and upgrading as opposed to starting with the new library in place.

**Comment by pierluigiabramo** [comment] 2017-11-30 06:56
![schermata 2017-11-30 alle 07 55 22](https://user-images.githubusercontent.com/17725824/33417982-fde4b0be-d5a3-11e7-94b7-31e20af84093.png)

**Comment by pierluigiabramo** [comment] 2017-11-30 07:53
Sorry guys but i think the problem was the theme..i have changed and now pods template work correctly..

**Comment by JoryHogeveen** [comment] 2017-11-30 11:46
No problem, thanks for your reply!

**Comment by pierluigiabramo** [comment] 2017-12-07 09:21
Hi guys!.. sorry for re-open but with another test i see the problems was not the theme ( i have changed many themes but with clean wp install) but Caldera Forms (1.5.7.1) if deactivated the disappear..

**Comment by pierluigiabramo** [comment] 2017-12-07 09:34
`[07-Dec-2017 09:16:06 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/waqyehdk/public_html/wp-content/plugins/caldera-forms/ui/edit.php on line 839`

**Comment by jimtrue** [comment] 2017-12-08 18:00
Did you engage CalderaWP on this error? Especially since it's coming directly from their plugin? @pierluigiabramo

**Comment by pierluigiabramo** [comment] 2017-12-09 12:59
Hi, sorry for response delay..no Jim beacuse i have the CF free version and the support is only for pay users. I think is better tag the author of the plugin @jimtrue

**Comment by pierluigiabramo** [comment] 2017-12-09 13:20
Or better if you have a e-mail direct

**Comment by jimtrue** [comment] 2017-12-09 15:43
I saw that you opened a CF bug report. That's the appropriate way to handle it!
https://github.com/CalderaWP/Caldera-Forms/issues/2124

I can verify & reproduce this one. I had to find a site of mine that had Caldera Forms installed along with Pods 2.7. The Template Editor will not allow a resize.

This is the JavaScript Console error I get:
```
JQMIGRATE: Migrate is installed, version 1.4.1
shortcode-insert.min.js?ver=1.5.7.1:1 Uncaught TypeError: Cannot read property 'views' of undefined
    at HTMLDocument.<anonymous> (shortcode-insert.min.js?ver=1.5.7.1:1)
    at i (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-tooltip&ver=4.9.1:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-tooltip&ver=4.9.1:2)
    at Function.ready (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-tooltip&ver=4.9.1:2)
    at HTMLDocument.K (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-tooltip&ver=4.9.1:2)
(anonymous) @ shortcode-insert.min.js?ver=1.5.7.1:1
i @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-tooltip&ver=4.9.1:2
fireWith @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-tooltip&ver=4.9.1:2
ready @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-tooltip&ver=4.9.1:2
K @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter,jquery-ui-tooltip&ver=4.9.1:2
```

**Comment by 0xLBF** [comment] 2017-12-10 09:16
I can confirm the bug with latest Caldera and Pods 2.7.1.
`load-scripts.php?c=0&load[]=hoverIntent,common,admin-bar,wp-ajax-response,jquery-color,wp-lists,jquery-ui-sortable,postbox,heartbeat,autosave,suggest,jquery&load[]=-ui-menu,wp-a11y,jquery-ui-autocomplete,tags-suggest,tags-box,underscore,word-count,post,jquery-ui-resizable,svg-painter,wp-auth&load[]=-check,thickbox,shortcode,media-upload&ver=4.9.1:310 Uncaught TypeError: Cannot read property 'hasClass' of undefined
    at HTMLDocument.<anonymous> (load-scripts.php?c=0&load[]=hoverIntent,common,admin-bar,wp-ajax-response,jquery-color,wp-lists,jquery-ui-sortable,postbox,heartbeat,autosave,suggest,jquery&load[]=-ui-menu,wp-a11y,jquery-ui-autocomplete,tags-suggest,tags-box,underscore,word-count,post,jquery-ui-resizable,svg-painter,wp-auth&load[]=-check,thickbox,shortcode,media-upload&ver=4.9.1:310)
    at HTMLDocument.dispatch (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter&ver=4.9.1:3)
    at HTMLDocument.r.handle (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter&ver=4.9.1:3)
    at Object.trigger (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter&ver=4.9.1:3)
    at Object.a.event.trigger (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter&ver=4.9.1:9)
    at HTMLDocument.<anonymous> (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter&ver=4.9.1:3)
    at Function.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter&ver=4.9.1:2)
    at a.fn.init.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter&ver=4.9.1:2)
    at a.fn.init.trigger (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-position,jquery-ui-draggable,jquery-u&load[]=i-slider,jquery-touch-punch,iris,wp-color-picker,wp-pointer,zxcvbn-async,password-strength-meter&ver=4.9.1:3)
    at Object.<anonymous> (load-scripts.php?c=0&load[]=hoverIntent,common,admin-bar,wp-ajax-response,jquery-color,wp-lists,jquery-ui-sortable,postbox,heartbeat,autosave,suggest,jquery&load[]=-ui-menu,wp-a11y,jquery-ui-autocomplete,tags-suggest,tags-box,underscore,word-count,post,jquery-ui-resizable,svg-painter,wp-auth&load[]=-check,thickbox,shortcode,media-upload&ver=4.9.1:21)`

**Comment by 0xLBF** [comment] 2017-12-10 12:29
Seems to be the same issue as https://github.com/pods-framework/pods/issues/4287

**Comment by 0xLBF** [comment] 2017-12-28 14:34
This appears to have been fixed as of Caldera Forms v. 1.5.8.2.

**Comment by pierluigiabramo** [comment] 2017-12-28 14:38
yes I confirm it was solved

**Closed** 2017-12-28 15:27 UTC
Labels: Compatibility, Verified/Reproduced
