### ISSUE TITLE
Need to resave settings after plugin updates in order to make my CPT work again

### ISSUE THREAD

**Issue by harrispap** [pods-framework/pods#5535] opened 2019-11-16 13:04 UTC
## Issue Overview
Hello!
I have created a custom post type with a custom field (a pdf file) in it (using pods obviously) :slightly_smiling_face: .
Every time I update the pods plugin the post type doesn't work (it gives an error while trying to add / upload the pdf file) and I have to open the plugin settings and press save (without making any changes) in order to make it work.
It happens when I update the pods plugin and only then. Otherwise it works as normal.

## Expected Behavior
Plugin to work flawlesly after its updates

## Current Behavior
CPTs built with pods stop working after the plugin (Pods) updates.
I need to go and save the pods settings in order to make it work back,

## Steps to Reproduce (for bugs)

1.  Update plugin
2.  Try to make a new CPT.
3.
4.

## WordPress Environment
Wordpress, Theme and plugins are all updated to latest versions

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

## Workaround or Alternate Solution Until Bug is Addressed
Go and press "save" in pod's settings (w/o making any changes) after plugin updates

**Comment by JoryHogeveen** [comment] 2019-11-18 14:16
Hello @harrispap 
I cannot reproduce this behavior on any sites that I manage.
Could you test is this also happens on a clean installation with ONLY Pods active and a default WordPress theme?
This can also be done with the Site Health plugin in troubleshoot mode:
https://wordpress.org/plugins/health-check/

Thanks!

**Comment by harrispap** [comment] 2019-11-18 17:59
Hello @JoryHogeveen ,
I also don't face the same issue in other sites I manage.
I asked in the slack support channel for advice on the issue and I was adviced to open a bug ticket.
I have to mention here that the problem DIDN'T came up after the last plugin update (I updated yesterday). It came up though at at least the 10-15 latest updates before this one.

Thanks!
Harris

**Comment by JoryHogeveen** [comment] 2019-11-19 12:10
Hello @harrispap 
Hmm I cannot reproduce at this point. Unless you can provide a way to reproduce this issue on various installtions (including my own) it's impossible to debug and I'm inclined to assume this is probably an external issue (server / other plugin incompatibility)

**Comment by harrispap** [comment] 2019-11-19 12:46
Ι understand.
I only posted it here because I was told so in the Slack support channel.

**Comment by JoryHogeveen** [comment] 2019-11-19 13:42
No problem! Sorry for the inconvenience.
Closing this topic!

**Closed by JoryHogeveen** 2019-11-19 13:42 UTC
Labels: Status: Need Reproduction, Status: Need User Feedback, Type: Bug
