### ISSUE TITLE
$ is displayed instead of ¥

### ISSUE THREAD

**Issue by Toraji123** [pods-framework/pods#6315] opened 2021-11-18 12:35 UTC
### Description

Even though I set the Currency Sign to “JPY: Japanese Yen(¥)“, the sign displayed in the form is “$” after upgrading to 2.8.0.
“¥” was displayed before the upgrade.

I use form() to show this field.

Thanks for your help!

### Version

2.8.4

### Screenshots / Screencast

![image (1)](https://user-images.githubusercontent.com/40485661/142415952-7fa416ad-0e04-4c6d-a279-c7c84c0fa831.png)

**Comment by JoryHogeveen** [comment] 2021-11-26 18:57
I cannot reproduce this issue on Pods 2.8.5

**Comment by JoryHogeveen** [comment] 2021-11-26 18:59
@Toraji123 How are you using `form()`

**Comment by Toraji123** [comment] 2021-11-27 05:09
@JoryHogeveen 
Thank you for looking into this.
I'm using Pods 2.8.5 and WordPress 5.8.2

Here is my form and definition.
`echo $mypod->form( 'wpm-price' );`

![image](https://user-images.githubusercontent.com/40485661/143668756-ebd9ef97-9033-4653-9ba1-1367d4a04920.png)

![image](https://user-images.githubusercontent.com/40485661/143668777-7462df94-6aab-4e21-9ca5-61d130381083.png)

![image](https://user-images.githubusercontent.com/40485661/143668788-b843a45b-fd80-4bde-b8d2-ca8af577b562.png)

Here is what I see.
![image](https://user-images.githubusercontent.com/40485661/143668859-13a7352f-5605-4d78-b20e-e7f0346f68d9.png)

Thanks!

**Comment by JoryHogeveen** [comment] 2021-11-29 14:42
Hi @Toraji123 

I'm sorry but I cannot reproduce your issue on any version.
@pdclark can you try to reproduce this?

**Comment by pdclark** [comment] 2021-11-29 22:45
@JoryHogeveen Reproduced with both shortcode and block:

<img width="1438" alt="Screen Shot 2021-11-29 at 2 44 42 PM" src="https://user-images.githubusercontent.com/126889/143954497-64ad193d-13a3-4f19-8aa2-37aa046fbf3e.png">

See Yen displays okay in wp-admin on left, but dollar displays in front-end forms on right.

**Comment by sc0ttkclark** [comment] 2021-11-29 23:21
Fixed via 688c2b706c34e7fe5f13471bfc549df439968497

**Closed by sc0ttkclark** 2021-11-29 23:21 UTC
Labels: Type: Bug, Status: Could not reproduce, Keywords: Regression, Component: DFV
