### ISSUE TITLE
Validation check problems with Date field 

### ISSUE THREAD

**Issue by andrepetrini** [pods-framework/pods#7016] opened 2023-02-23 13:33 UTC
### Description

I have a bunch of Date fields inside a POD. It worked fine at the beginning, but when I tried to change the values, I get the "Invalid date" error message, even with the "Allow empty value" option set to yes.

### Version

2.9.11

### Screenshots / Screencast

![image](https://user-images.githubusercontent.com/16229307/220921198-d3fcc8bd-9e8d-49a8-ab20-2580ec3788a9.png)
<img width="928" alt="Captura de Tela 2023-02-23 às 10 33 49" src="https://user-images.githubusercontent.com/16229307/220921571-fb17f3b0-c7c9-4bf0-a344-ec76860fcabc.png">

**Comment by Shelob9** [comment] 2023-04-19 22:38
I am testing this now, I can reproduce it when a date range is set. I can not reproduce it when date range is not set. Likely the issue is its checking if empty date is in range.

**Comment by Shelob9** [comment] 2023-04-19 23:10
Throw happened here, beacuse empty string is not valid date according to moment.

https://github.com/pods-framework/pods/blob/main/ui/js/dfv/src/helpers/validators.js#L122-L124

Should be fixed via #7063

**Closed** 2023-04-20 13:41 UTC
Labels: Type: Bug
