### ISSUE TITLE
Allow "wp-admin only" use of pods

### ISSUE THREAD

**Issue by rogerlos** [pods-framework/pods#2068] opened 2014-03-04 12:12 UTC
I adore the tools pods gives me in WP's admin for managing custom post types. But in a very challenging environment (high traffic, slow server farm, slower DB farm, personalized pages which don't play well with off-the-shelf caching...don't ask!) I'm having to do a lot of hair-pulling to avoid pods calls on the front end in an effort to squeeze out every last morsel of performance. 

Because of the site's data structure, I have a few pages where there are thousands of calls to "pods_sanitize" and other pods functions when building the page. (I've had to abandon get_post_meta because of the load pods puts on that function, and am now writing joined queries via wpdb instead--definitely not best practice but is a better performer in my particular case.)

My idea would be to allow those of us who really enjoy pods admin functionality have an advanced option to "disable pods on front end", or at least remove its hooks and filters on "normal" WP functions unless specifically called to do so. I recognize that my use case is an edge, but y'all bring a ton of value to the management of custom post types and taxonomies which I am reluctant to lose.

**Comment by jamesgol** [comment] 2015-01-27 08:24
Duplicate of #1064

**Closed by jamesgol** 2015-01-27 08:24 UTC
Labels: Enhancement, Feature
