### ISSUE TITLE
Need help with form on UI

### ISSUE THREAD

**Issue by hvvi** [pods-framework/pods#3655] opened 2016-07-08 08:08 UTC
I have job-manager plugin
Add field participant with relationship to users 
![Image of Yaktocat](http://clip2net.com/clip/m519893/4b4a5-clip-148kb.png)
In admin panel when i create new job - all work perfect
But I want that users can add job from ui
I add follow code:

```
            <?php $pods = pods('job_listing'); 
            echo $pods->display( 'participants' );
            $params = array('fields_only' => true, 'fields' => array('participants') ); 
            echo $pods->form($params);?>
```

but participants did not saved when publish job
then i add button Save Change to form:
![Image of Yaktocat](http://clip2net.com/clip/m519893/ed48f-clip-26kb.png)
when press save change - page reload:
Form submitted successfully
Then I press Publish and have next result:
Pod not found
![Image of Yaktocat](http://clip2net.com/clip/m519893/eb3a3-clip-42kb.png)

Whats wrong?

**Comment by JoryHogeveen** [comment] 2016-07-11 23:41
Hi @hvvi,
Though I'm not 100% sure I'd think this is a capability issue.
After saving, what data can be found in the database for that meta_key?

**Comment by hvvi** [comment] 2016-07-12 07:17
![Image of Yaktocat](http://clip2net.com/clip/m519893/ee5a6-clip-50kb.png)
Data about listing

![Image of Yaktocat](http://clip2net.com/clip/m519893/aeb22-clip-48kb.png)
No data about participants

**Comment by hvvi** [comment] 2016-07-27 08:53
any ideas? bc I cant search some solution

**Comment by lukecav** [comment] 2016-07-27 21:14
So front-end job submission by user?

**Comment by lukecav** [comment] 2016-07-27 21:16
I think WP Job Manager already has that function built into core. 

https://wpjobmanager.com/document/setting-up-wp-job-manager/

**Comment by JoryHogeveen** [comment] 2016-08-01 15:31
@jimtrue can you take a quick look?

**Comment by jimtrue** [comment] 2016-08-01 15:38
This sounds more like a conflict than anything else. I'd have to replicate in order to reproduce. Also i can't tell from the discussion above, is this changes to the back end ( which should just work) or is this a front end form that is not behaving properly?

**Comment by JoryHogeveen** [comment] 2016-08-02 00:35
From what I can tell this is a pod field that is beying edited on the front end.
The system returns a success response on the front end but no actual data is created.

@hvvi can you provide us with an import package for the pod? Also, can we see you dev installation?

**Comment by jimtrue** [comment] 2016-08-02 00:44
incorporating a field on the front-end into another plugins' form controls is out of my area of expertise. In looking at the note above, it's only being applied to it's own unique form, not the overall form. That would be, to me, why it's not working. It needs to be incorporated into the 'overall' form action.

**Comment by hvvi** [comment] 2016-08-02 11:33
hello guys.
I update Pods to last version ( 2.6.6 )
Now when i save participants with Save button from pods form - in back-end created post with that participants, url of page in front-end change to /?success=1. But without other data, so all fields in job are empty. 
![Image of Yaktocat](http://clip2net.com/clip/m519893/6a865-clip-100kb.png)

Then I can't press Preview button from WPJM. Job can't accepted with participants without any notice.
Maybe just create one button which will be add participant and preview job?
http://beskyd.org/new-trip/

**Comment by JoryHogeveen** [comment] 2016-08-02 12:44
Sorry I'm not sure I understand the problem/question correctly.
Please tell me if I'm correct:

- **Case**: You have a CPT "Jobs" that have a relationship with users (or participants)
- **Case**: You want users to add/assign participants to these jobs in the **front end**
- **Problem**: The form saves successfully in the frond end but no actual users/participants are saved in the relationships

If this is correct:
- When editing in backend, does that work?
- If you set `WP_DEBUG` to `true` in `wp-config.php`, do you see any errors?

**Comment by hvvi** [comment] 2016-08-02 13:13
- **Case**: Yes, field participant have relationship with user
-**Case**: Yes
-**Problem**: Nope, on back-end all work perfect, on the front-end the form save participants but ignore all other data,
-**Question:** How to save pods and post data togeter

**Comment by JoryHogeveen** [comment] 2016-08-02 14:02
Talked it over with @jimtrue 
`$pods->form()` generates a standalone form with your config (`$params`). So the current setup will not work since there are two from elements.

If you want Pods to generate the form you should use this function only and generate a full form for the post aswell with all the fields. (http://pods.io/docs/code/pods/form/)

Another option is to create your own custom form and only handle saving the Pods fields with Pods.

**Comment by quasel** [comment] 2018-09-01 22:54
Hi, we didn't hear back from you - so I'm closing the issue!

**Closed by quasel** 2018-09-01 22:54 UTC
Labels: Status: Need Dev Feedback, Type: Bug
