### ISSUE TITLE
Add new Field Type: Table

### ISSUE THREAD

**Issue by datverse** [pods-framework/pods#6137] opened 2021-09-13 17:51 UTC
Hi,
Can I request a new feature is: Add new Field Type: "Table"?
It's like: Advanced Custom Fields: Table Field
https://wordpress.org/plugins/advanced-custom-fields-table-field/

`It's generate <table> html in the front end.`

Thanks

**Comment by sc0ttkclark** [comment] 2021-09-23 01:41
Love the idea, let's see if we can find more people who would like this too. If there's enough interest in it, we can look at what it will take here. It's definitely a lot of work, even taking existing solutions and trying to put them ontop of Pods for this.

**Comment by JoryHogeveen** [comment] 2021-09-23 11:32
Duplicate of #3456

**Closed by JoryHogeveen** 2021-09-23 11:32 UTC
Labels: Type: Enhancement, Status: Need Votes

**Comment by vesna-droid** [comment] 2022-03-30 09:46
This could be really useful. Status shows: needs votes. Where do I vote?

**Comment by JoryHogeveen** [comment] 2022-03-30 11:55
> It's a +1 thumb up on any issue, or a comment on any issue in support
> But honestly, the best way to vote is to donate and vote in the feature votes there (Friend of Pods)

**Comment by vesna-droid** [comment] 2022-03-30 12:32
I did donate (one time donation) but i dont see feature votes on my account page there.
