### ISSUE TITLE
Pods::save does not flush cache

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#1786] opened 2013-10-18 00:24 UTC
```
<?php
$pod = pods('three', 40);
//orignal value = 'Gandalf The Grey'
echo "My name is: " . $pod->display('field_of_names');

$data = array( 
    'field_of_names' => 'Gandalf The White',  
);
$pod->save( $data, $value = null, $id = 40);

echo "\nMy new name is: " . $pod->display('field_of_names');
?>
```
Returns: 
My name is: Gandalf the Grey My new name is: Gandalf the Grey

re-running this returns My name is: Gandalf the White My new name is: Gandalf the White

So it tried this with a new post:

```
<?php
$pod = pods('three', 41);
//orignal value = 'Smeagaol'
echo "My name is: " . $pod->display('field_of_names');

$data = array( 
    'field_of_names' => 'Gollum',  
);
$pod->save( $data, $value = null, $id = 41);

$pod = pods('three', 41);
echo "\nMy new name is: " . $pod->display('field_of_names');
?>
```
Returns: 
My name is: Smeagaol My new name is: Gollum

I tested this with meta based storage and table based storage and got the same results.

**Comment by tuanmh** [comment] 2015-04-17 07:15
It seems the code suggested by @sc0ttkclark was merged to 2.5.1.2 but the bug is still there. Below is my SSCCE (Short, Self Contained, Correct Example). It's basically creating a row in DB then update the row and retrieve it back using both Pods and classical Wpdb for comparison. You could see something like the following picture in console. The 'Updated, Retrieved by Pods' must have the same value as 'Local Modified' and 'Retrieved by Wpdb'. I hope it would help.

![image](https://cloud.githubusercontent.com/assets/3193353/7197468/e089c01c-e524-11e4-85bf-d9eeb81eeef2.png)

Please modify path to wp-load.php and schema file.
PHP file:
```
<?php
$path_to_wp_load = '../wp-load.php';
$path_to_pods_importer = '../wp-content/plugins/pods/components/Migrate-Packages/Migrate-Packages.php';
require_once $path_to_wp_load;
wp();
require_once $path_to_pods_importer;

$podAPI = pods_api();
$string = file_get_contents(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'schema.json');
$data = json_decode($string,true);
$importer = new Pods_Migrate_Packages();
$result = $importer->import($data, true);

//Creating data
$id = pods( 'post_item' )->add(['main_post_id' => 100000, 'section_number' => "1.1", 'cached_flattened_order' => 1]);
$items_created_by_pod = retrieveUsingPods(100000); //retrieving data back using pods

//updating data using pods
global $wpdb;
$wpdb->query("START TRANSACTION;");
{
    $data = ["section_number" => "1.2", "cached_flattened_order" => 2];
    $pod = pods( 'post_item', intval($id) );
    if ($pod->exists()) {
        $pod->save( $data );
    }
}
$wpdb->query("COMMIT;");

//3. Retrieve data using Pods
$items_from_pod = retrieveUsingPods(100000);

//4. Retrieve data using wpdb
$items_from_db = $wpdb->get_results("SELECT * FROM wp_pods_post_item where main_post_id = 100000", ARRAY_A);

echo "<br><b>section_number</b><br>";
echo "Created by pods: " . $items_created_by_pod[0]['section_number'] . "<br>";
echo "Local Modified: 1.2<br>";
echo "Updated, Retrieved by Pods: " . $items_from_pod[0]['section_number'] . "<br>";
echo "Retrieved by Wpdb: " . $items_from_db[0]['section_number'] . "<br><br>";

echo "<br><b>cached_flattened_order</b><br>";
echo "Created by pods: " . $items_created_by_pod[0]['cached_flattened_order'] . "<br>";
echo "Local Modified: 2<br>";
echo "Updated, Retrieved by Pods: " . $items_from_pod[0]['cached_flattened_order'] . "<br>";
echo "Retrieved by Wpdb: " . $items_from_db[0]['cached_flattened_order'] . "<br><br>";


function retrieveUsingPods($main_post_id) {
    global $wpdb;
    $pod = pods('post_item', array(
        "where"   => "t.post_status <> 'trash' AND " . $wpdb->prepare( "d.main_post_id = %d", $main_post_id),
        "orderby" => "ABS(d.cached_flattened_order) ASC",
        "limit"   => -1
    ));
    $items = array();
    while ( $pod->fetch() ) {
        $items[] = from_pod( $pod );
    }
    return $items;
}

function from_pod( $pod ){
    $post_item = array();
    $post_item['id']            = intval( $pod->id() );
    $post_item['main_post_id']  = intval( $pod->raw('main_post_id') );
    $post_item['section_number']  = strval( $pod->raw('section_number') );
    $post_item['cached_flattened_order'] = intval( $pod->raw('cached_flattened_order') );
    return $post_item;
}
```

Schema:
```
{
  "meta": {
    "version": "2.5.1.2",
    "build": 1429249640
  },
  "pods": {
    "55791": {
      "id": 55791,
      "name": "post_item",
      "label": "post_item",
      "description": "",
      "type": "post_type",
      "storage": "table",
      "object": "",
      "alias": "",
      "fields": {
        "main_post_id": {
          "id": 55792,
          "name": "main_post_id",
          "label": "Main Post",
          "description": "",
          "help": "",
          "class": "",
          "type": "number",
          "weight": 0,
          "pick_object": "",
          "pick_val": "",
          "sister_id": "",
          "required": "1",
          "unique": "0",
          "number_format_type": "number",
          "number_format": "i18n",
          "number_decimals": "0",
          "number_step": "1",
          "number_min": "0",
          "number_max": "100",
          "number_max_length": "12",
          "default_value": "0",
          "admin_only": "0",
          "restrict_role": "0",
          "restrict_capability": "0",
          "hidden": "0",
          "read_only": "0",
          "roles_allowed": ["administrator"],
          "number_repeatable": "0"
        },
        "associate_post_id": {
          "id": 55793,
          "name": "associate_post_id",
          "label": "Associated Post",
          "description": "",
          "help": "",
          "class": "",
          "type": "number",
          "weight": 1,
          "pick_object": "",
          "pick_val": "",
          "sister_id": "",
          "required": "0",
          "unique": "0",
          "number_format_type": "number",
          "number_format": "i18n",
          "number_decimals": "0",
          "number_step": "1",
          "number_min": "0",
          "number_max": "100",
          "number_max_length": "12",
          "default_value": "0",
          "admin_only": "0",
          "restrict_role": "0",
          "restrict_capability": "0",
          "hidden": "0",
          "read_only": "0",
          "roles_allowed": ["administrator"],
          "number_repeatable": "0"
        },
        "section_number": {
          "id": 55796,
          "name": "section_number",
          "label": "Section Number",
          "description": "",
          "help": "",
          "class": "",
          "type": "text",
          "weight": 2,
          "pick_object": "",
          "pick_val": "",
          "sister_id": "",
          "required": "0",
          "unique": "0",
          "text_allow_shortcode": "0",
          "text_allow_html": "0",
          "text_allowed_html_tags": "strong em a ul ol li b i",
          "text_max_length": "255",
          "admin_only": "0",
          "restrict_role": "0",
          "restrict_capability": "0",
          "hidden": "0",
          "read_only": "0",
          "roles_allowed": ["administrator"],
          "text_repeatable": "0"
        },
        "prev_item_id": {
          "id": 55797,
          "name": "prev_item_id",
          "label": "Previous Item",
          "description": "",
          "help": "",
          "class": "",
          "type": "number",
          "weight": 3,
          "pick_object": "",
          "pick_val": "",
          "sister_id": "",
          "required": "0",
          "unique": "0",
          "number_format_type": "number",
          "number_format": "i18n",
          "number_decimals": "0",
          "number_step": "1",
          "number_min": "0",
          "number_max": "100",
          "number_max_length": "12",
          "default_value": "0",
          "admin_only": "0",
          "restrict_role": "0",
          "restrict_capability": "0",
          "hidden": "0",
          "read_only": "0",
          "roles_allowed": ["administrator"],
          "number_repeatable": "0"
        },
        "next_item_id": {
          "id": 55798,
          "name": "next_item_id",
          "label": "Next Item",
          "description": "",
          "help": "",
          "class": "",
          "type": "number",
          "weight": 4,
          "pick_object": "",
          "pick_val": "",
          "sister_id": "",
          "required": "0",
          "unique": "0",
          "number_format_type": "number",
          "number_format": "i18n",
          "number_decimals": "0",
          "number_step": "1",
          "number_min": "0",
          "number_max": "100",
          "number_max_length": "12",
          "default_value": "0",
          "admin_only": "0",
          "restrict_role": "0",
          "restrict_capability": "0",
          "hidden": "0",
          "read_only": "0",
          "roles_allowed": ["administrator"],
          "number_repeatable": "0"
        },
        "cached_flattened_order": {
          "id": 55803,
          "name": "cached_flattened_order",
          "label": "Cached Flattened Order",
          "description": "",
          "help": "",
          "class": "",
          "type": "number",
          "weight": 5,
          "pick_object": "",
          "pick_val": "",
          "sister_id": "",
          "required": "0",
          "unique": "0",
          "number_format_type": "number",
          "number_format": "i18n",
          "number_decimals": "0",
          "number_step": "1",
          "number_min": "0",
          "number_max": "100",
          "number_max_length": "12",
          "admin_only": "0",
          "restrict_role": "0",
          "restrict_capability": "0",
          "hidden": "0",
          "read_only": "0",
          "roles_allowed": ["administrator"],
          "number_repeatable": "0"
        }
      },
      "show_in_menu": "0",
      "label_singular": "Post Item",
      "public": "1",
      "show_ui": "0",
      "supports_title": "1",
      "supports_editor": "0",
      "publicly_queryable": "1",
      "exclude_from_search": "1",
      "capability_type": "post",
      "capability_type_custom": "syllabus_item2",
      "capability_type_extra": "1",
      "has_archive": "0",
      "hierarchical": "1",
      "rewrite": "1",
      "rewrite_with_front": "1",
      "rewrite_feeds": "0",
      "rewrite_pages": "1",
      "query_var": "1",
      "can_export": "1",
      "default_status": "draft",
      "supports_author": "0",
      "supports_thumbnail": "0",
      "supports_excerpt": "0",
      "supports_trackbacks": "0",
      "supports_custom_fields": "0",
      "supports_comments": "1",
      "supports_revisions": "0",
      "supports_page_attributes": "1",
      "supports_post_formats": "0",
      "built_in_taxonomies_category": "0",
      "built_in_taxonomies_link_category": "0",
      "built_in_taxonomies_post_tag": "0",
      "menu_position": "0",
      "show_in_nav_menus": "0",
      "show_in_admin_bar": "0"
    }
  }
}
```

**Comment by tuanmh** [comment] 2015-04-20 00:45
And surprisingly, it's still not working when I disabled cache server (Memcache)

**Comment by sc0ttkclark** [comment] 2015-04-20 04:51
@tuanmh What happens when you do it outside of a transaction?

**Comment by tuanmh** [comment] 2015-04-20 23:55
> @tuanmh What happens when you do it outside of a transaction?

@sc0ttkclark thanks for suggesting but the bug is still there.

**Comment by tuanmh** [comment] 2015-04-22 23:22
I think the problem is on this line, in fetch method:
```php
if ( is_array( $this->row ) && !empty( $this->row ) ) {
    $this->row = array_merge( $row, $this->row );
}
```

Fetch method combines the existing data in pod instance ($this->row) and the data retrieved from db ($row) if there is no existing cache item. We have an incorrect order here ```$this->row = array_merge( $row, $this->row );```. quote from php manual: ```If the input arrays have the same string keys, then the later value for that key will overwrite the previous one. ```. Hence, $this->row will never be updated with latest data from DB ($row), leading to the cache containing old data. 

I propose this instead:

```php
if ( is_array( $this->row ) && !empty( $this->row ) ) {
    $this->row = array_merge( $this->row, $row );
}
```

Please see 9948175749963afb43d840acd3fafbd6d9fd11c8 for more detail. PR is also fired, thanks!

**Closed** 2015-05-14 15:48 UTC
Labels: Bug: Normal, Fixed / Needs Testing, Needs Unit Test
