### ISSUE TITLE
Saving pod item returns you to Manage Pods rather than open item

### ISSUE THREAD

**Issue by andymakesglasses** [pods-framework/pods#2942] opened 2015-05-15 13:43 UTC
In previous versions of Pods when you saved a pod item the page refreshed to the item you were working on which was quite useful.

Now (and in the last release) when you save a pod item it instead returns you to the Manage screen which means if you want to continue working on that item you have to search for it again.

**Comment by sc0ttkclark** [comment] 2015-05-15 15:23
This definitely wasn't intended, we'll look into it

**Comment by jimtrue** [comment] 2015-05-15 15:39
I'm not seeing this particular action happening on either an existing installation with 2.5.1.2, or on a new installation with 2.5.2 (or the previous one upgraded). Are you sure you don't have any other actions or plugins interacting with your UI? Can you try with all plugins save Pods and a default WordPress theme activated to test?

To be clear, you're seeing this in the Pods Admin, when Editing a Pod, correct? Or are you talking about the Edit Post Type screens? (I checked both to be sure).

**Comment by andymakesglasses** [comment] 2015-05-15 15:53
I can confirm that the issue still occurs with all plugins deactivated and a default WordPress theme installed.

I'm seeing this when I'm editing an individual pod record. So for example if I go to:

Pods > Manage *pod name*

And then select one of the pod items to edit from the list.

Actually, I now remember that the issue started on the previous version of Pods when I downloaded development files to fix this issue:

http://pods.io/forums/topic/problems-with-form-code-field/#post-188975

Could whatever was contained in the development files be causing this? If so, would replacing everything in the "pods" folder in wp-content/plugins with the latest download of Pods potentially fix it?

**Comment by jimtrue** [comment] 2015-05-15 16:01
You do manage to get the odd unusual bugs, huh? I remember that forum post. There were significant fixes to the CodeMirror issues in this particular patch so it definitely includes those.

That's always one of the cleanest ways to make sure you don't have other code stepping on top of itself. You should be able to deactivate Pods, wipe it's directory and re-install the plugin and activate without losing anything (just run a backup first). Just don't delete from within WordPress (use FTP/SFTP/SSH). 

See if that fixes your issue upon replacing and activating and also do a Clear Pods Cache in Pods Admin, Settings. If it's still not working, we'll need your Debug Details, I believe.

**Comment by andymakesglasses** [comment] 2015-05-15 16:18
Ok, I've done that and the problem is continuing. Here's my Debug Information:

Debug Information

WordPress Version: 4.2.2

PHP Version: 5.2.11

MySQL Version: 5.1.37

Server Software: Apache/2.0.63 (Unix) PHP/5.2.11 DAV/2

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17

Session Save Path: /Applications/MAMP/tmp/php

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /Applications/MAMP/htdocs/stravaiging2015/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Stravaiging 2015

Currently Active Plugins:

Advanced Excerpt: 4.2.3
AJAX Thumbnail Rebuild: 1.12
Akismet: 3.1.1
All In One SEO Pack: 2.2.6.2
Auto Post Thumbnail: 3.3.3
BAW Post Views Count: 2.19.11
Contact Form 7: 4.1.2
CSV Importer For Pods: 0.8
Disqus Comment System: 2.84
Exec-PHP: 4.9
Feed Statistics: 4.0.1
Google Analytics Dashboard: 2.1.1
Jetpack by WordPress.com: 3.5.3
MailChimp: 1.4.2
No Self Pings: 0.2
Pods - Custom Content Types and Fields: 2.5.2
Revision Control: 2.3.1
Smarter Archives: 3.2.3
UpdraftPlus - Backup/Restore: 1.10.1
YARPP Experiments: 1.1
Yet Another Related Posts Plugin: 4.2.5

**Comment by jimtrue** [comment] 2015-05-15 17:32
I notice your'e running locally on a MAMP box with PHP 5.2. Are you also seeing the same issue on your live server (ie multiple installations)?

Is it possible for you to upgrade your PHP version? You should be running PHP 5.3+ (but 5.4 + is recommended).

**Comment by jimtrue** [comment] 2015-05-15 18:00
@andymakesglasses While the information is good for you regardless, I didn't realize you were talking about ACT's until I got into a discussion with @pglewis and @sc0ttkclark I just tested this locally on an ACT and I have the same issue. When you save the ACT, you are not returned to the screen you were editing but one level up, the 'Manage Pod' screen.

**Comment by andymakesglasses** [comment] 2015-05-15 18:03
Ah, ok, glad it's not just me!

Thanks for the information about the PHP versions, I'm in the process of upgrading MAMP now and have contacted my hosting company to ask about upgrading it there.

**Comment by pglewis** [comment] 2015-05-15 18:05
Step 1 should probably be go back through history and find where it started misbehaving.

**Comment by andymakesglasses** [comment] 2015-05-15 18:10
If it's any help it would've been the 3rd or 4th of February when I downloaded the development files, which is when I first noticed this behaviour.

**Comment by pglewis** [comment] 2015-05-18 07:01
https://github.com/pods-framework/pods/commit/b25498

![2942](https://cloud.githubusercontent.com/assets/1973916/7675756/2c6129a6-fd0a-11e4-8011-490032af69ef.png)

**Comment by sc0ttkclark** [comment] 2015-05-18 17:12
That commit needs backing out, we are late-escaping all esc_url() usage, pods_query_arg should not have an esc_url() on the return value.

**Comment by pglewis** [comment] 2015-05-25 18:34
That broken commit was already reverted: https://github.com/pods-framework/pods/commit/d8f73be13ddf3c2b2a723af52955437976cf1043 so the problem is elsewhere.  This did break around the same time, however.

**Comment by Shelob9** [comment] 2015-05-25 19:04
@pglewis James reverted that, but then @sc0ttkclark made a bunch of other changes in its place: https://github.com/pods-framework/pods/pull/2693/commits

**Comment by Shelob9** [comment] 2015-05-25 19:06
I left a comment on 3a2edf7b660d98b452460d1f0543544633dfb807 where I think this broke, I need to do some testing to confirm that.

**Comment by pglewis** [comment] 2015-05-25 22:52
I think it was re-introduced in the commit before that, c397212251ef6903fdc29de2860b08a810c998e3.

**Comment by pglewis** [comment] 2015-05-25 23:40
https://github.com/pods-framework/pods/commit/c397212251ef6903fdc29de2860b08a810c998e3#commitcomment-11355280

**Comment by pglewis** [comment] 2015-05-26 00:24
Pull request created.

**Comment by pglewis** [comment] 2015-05-29 02:17
Sorry for the inconvenience on this one, Andy.  The fix should be merged into 2.x and will go out with the next release, sometime next week.

**Closed by pglewis** 2015-05-29 02:17 UTC
Labels: Bug: Regression, Fixed / Needs Testing, PR Submitted, Researched, Verified/Reproduced
