### ISSUE TITLE
export_pod_item crashing on taxonomy relationship

### ISSUE THREAD

**Issue by pcfreak30** [pods-framework/pods#3518] opened 2016-05-10 15:23 UTC
```
{"id":0,"name":"taxonomy","label":"Taxonomy","description":"","help":"","default":null,"attributes":[],"class":"","type":"pick","group":0,"grouped":0,"developer_mode":false,"dependency":false,"depends-on":[],"excludes-on":[],"options":[],"alias":[]}
```

It appears that in trying to export a pod item out, its going into a taxonomy relationship and looping over the terms. The crash happens when `pick_object` is not defined.

**Comment by pcfreak30** [comment] 2016-05-10 22:22
Here is a screen shot of it in xdebug. Ir seems to just fail when trying to export the fields of a taxonomy relationship that really aren't pod fields.
![selection_141](https://cloud.githubusercontent.com/assets/10647/15164072/5f042652-16da-11e6-9a9c-924f91732688.png)
![Uploading Selection_142.png…]()

I believe the issue is due to fields data having non pod fields on a taxonomy through a taxonomy relationship.

**Comment by pcfreak30** [comment] 2016-05-10 23:02
After testing on shell, I found `pods('assignment_month', null, false)->pod_data['object_fields']['taxonomy']` returns the data I dumped. assignment_month is a taxonomy.

**Comment by quasel** [comment] 2018-08-31 23:34
Duplicate of #4577

**Closed by quasel** 2018-08-31 23:34 UTC
Labels: Closed: Duplicate
