### ISSUE TITLE
Pods Reordering Broken for ACPTs

### ISSUE THREAD

**Issue by cspicuzza** [pods-framework/pods#2980] opened 2015-05-26 20:32 UTC
This issue happens when you attempt to reorder an advanced custom post type from the manage page.  Clicking the reorder button brings you to the page with the drag and drop functionality but nothing moves.  All the post items are frozen in place.  There are no errors showing up in the inspector log.  I didn't see any errors in the Query Monitor log either.  

Wordpress 4.2.2
Pods 2.5.2

**Comment by quasel** [comment] 2015-05-26 20:40
related to #2843

**Comment by Shelob9** [comment] 2015-05-27 20:23
Closing as duplicate of #2843

**Closed by Shelob9** 2015-05-27 20:23 UTC
Labels: Bug: Regression, Duplicate
