### ISSUE TITLE
Custom Settings Page: Field type "File/image/video" doesn't work

### ISSUE THREAD

**Issue by redpik** [pods-framework/pods#2956] opened 2015-05-21 13:30 UTC
It's impossible to save / edit a field "File / image / video" on a Custom Settings Page.
the field stays empty. no image attached. nothing appens.

test with Pods **2.5.2** & Pods **2.5.3 alpha 1**. Last WP version.

it's the same issue with Syntax Highlighting: https://github.com/pods-framework/pods/issues/2875

**Comment by Shelob9** [comment] 2015-05-21 17:04
Closing as a duplicate of  #2955

**Closed by Shelob9** 2015-05-21 17:04 UTC
Labels: Bug: Regression, Needs Research

**Comment by Shelob9** [comment] 2015-05-21 17:37
In response to @jimtrue concern this is may not be a dupe of #2955 I can confirm this issue happens on Pods 2.5.2 in a settings page, and that PR #2957 fixes it on a settings page. So I think we should keep this closed as a dupe, as that PR will fix it and therefore everyone wins.
