### ISSUE TITLE
@{post_content} strips out all tags in a Template when there are no Fields

### ISSUE THREAD

**Issue by szepeviktor** [pods-framework/pods#2271] opened 2014-06-27 22:12 UTC
`@{post_content}` strips out e.g. `<p style="text-align: center;">`
If I add a Field to the pod it returns the raw content.

**Comment by logoscreative** [comment] 2015-02-28 15:07
I can confirm this.

If there are no custom fields, and I use `{@post_content}` in a template, the HTML in the post content is stripped out. As soon as I add one field, the HTML is outputted properly.

**Comment by jamesgol** [comment] 2015-02-28 21:23
I couldn't reproduce this either.  I tried enabling/disabling anything that should be relevant and couldn't come up with anything.

If you can give more specific steps to reproduce that would go a long way.

**Comment by logoscreative** [comment] 2015-03-02 11:29
Ah! Looks like this happens when listing multiple posts, like `[pods name="test" template="Test"]`.

I was able to reproduce this again. Only Pods and Frontier Auto Template are enabled.
1. Create a new Pods CPT (don't do anything else to it). Add one instance of the CPT, and put some HTML inside of the content area.
1. Add a new template that uses `{@post_content}`.
1. Insert the shortcode that lists the pods with the template into a page/post/whatever.

The shortcode that lists the Pods will strip out the HTML. However, if you add literally any field to the Pod and save it, the HTML will output correctly for the list shortcode.

**Comment by Shelob9** [comment] 2015-03-02 14:58
@logoscreative Did you test pull request #2766 to see if it resolves your issue?

**Comment by jamesgol** [comment] 2015-03-02 16:45
I can confirm that I was able to reproduce the issue with the additional info @logoscreative provided.

Unfortunately when updating to the last version that includes #2766, now no data is passed at all

**Comment by jamesgol** [comment] 2015-03-02 16:58
#2765 broke this

**Comment by sc0ttkclark** [comment] 2015-03-02 17:18
For #2765, just need to ensure if form="1" is set then we require $params to not be empty on that line.

**Comment by Shelob9** [comment] 2015-04-01 17:32
Fixed via #2769

**Closed by Shelob9** 2015-04-01 17:32 UTC
Labels: Bug: Normal, Needs Research, Needs User Feedback

**Comment by szepeviktor** [comment] 2015-04-01 17:36
Thank you!
When do you plan to release 3.0?
Will it be faster?

**Comment by Shelob9** [comment] 2015-04-01 17:37
@szepeviktor We will release 3.0 when it is ready. I know that sounds dismissive, but it's the best answer we can give.

**Comment by szepeviktor** [comment] 2015-04-01 17:39
It is promising that tha wheels are turning. I've never thought it'll be done. But it is! 10 months.

**Comment by szepeviktor** [comment] 2015-04-01 17:43
Thank you again.

**Comment by jamesgol** [comment] 2015-04-01 17:43
Sorry haven't had a chance to figure out the right way to test this. Way too much life stuff going on right now
