### ISSUE TITLE
Save button not behaving normally in “Roles and Capabilities”

### ISSUE THREAD

**Issue by siy34** [pods-framework/pods#4489] opened 2017-10-01 09:55 UTC
In the “Roles and Capabilities” component, when I try to save changes, it never finishes spinning although after refreshing the page it shows that the changes have been saved.

**Comment by pglewis** [comment] 2017-10-07 14:18
Duplicate of #4477, fixed in #4492

**Closed by pglewis** 2017-10-07 14:18 UTC
Labels: Duplicate
