### ISSUE TITLE
Relationship / simple (custom defined list) not displaying on order page in v2.7.9

### ISSUE THREAD

**Issue by RockPeach** [pods-framework/pods#5194] opened 2018-11-12 10:25 UTC
## Issue Overview

Field type: Relationship 
Related to: Simple (custom defined list)
Location of the added field: Order page

Issue: The fields in the list don't display in version 2.7.9. Roll backed to version 2.6.11 and they display fine

## Expected Behavior

The list should also display in version 2.7.9 as per this screenshot:
Pevious version (2.6.11): https://prnt.sc/lhauax

Pod field configuration: https://prnt.sc/lhatz8

 

## Current Behavior

The list is not displaying as per this screenshot:
Latest version (2.7.9): https://prnt.sc/lhauax

 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by jimtrue** [comment] 2018-11-12 13:30
@RockPeach You didn't provide your Pods Admin, Settings, Debug Information above. We pretty much have to have that to determine if you've got a conflict and to determine what versions of everything else you have loaded.

**Comment by RockPeach** [comment] 2018-11-13 00:32
Sorry here it is:

Debug Information
WordPress Version: 4.9.8

PHP Version: 7.0.32

MySQL Version: 5.5.5

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

Session Save Path: /var/cpanel/php/sessions/ea3

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 1024M

Pods Network-Wide Activated: No

Pods Install Location: /home/achatcloud/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Basel Child

Currently Active Plugins:

Activity Log: 2.5.1
Admin Columns: 3.3.1
Admin Menu Editor: 1.8.5
Aelia Foundation Classes for WooCommerce: 2.0.1.180821
ATUM Inventory Management for WooCommerce: 1.4.18.2
Booster Plus for WooCommerce: 4.0.1
Chats: 1.3.9
CMB2: 2.4.2
Code Snippets: 2.12.0
Custom Login Page Templates: 1.0
Custom Product Tabs for WooCommerce: 1.6.6
Duplicator Pro: 3.7.8.1
Easy WP SMTP: 1.3.7
Email Address Encoder: 1.0.9
Envato Market: 2.0.1
Filter WooCommerce Orders by Payment Method: 1.0.0
Fr Multi Bank Transfer Payment Gateways for WooCommerce: 1.0.1
Hide My WP: 5.5.7
Loco Translate: 2.1.5
Members: 2.1.0
Multi-Carrier Shipping Plugin for WooCommerce: 1.4.4
plugin load filter: 3.0.4
Pods - Custom Content Types and Fields: 2.6.11
Polylang for WooCommerce: 1.0.4
Polylang Pro: 2.4
Profile Builder - Custom CSS Classes on fields: 1.0.3
Profile Builder - Customization Toolbox Add-On: 1.0
Profile Builder - Custom Profile Menus Add-On: 1.0.7
Profile Builder - Email Confirmation Field: 1.0.4
Profile Builder - Field Visibility Add-On: 1.1.6
Profile Builder - MailChimp Add-On: 1.1.8
Profile Builder - Maximum Character Length Add-On: 1.0.0
Profile Builder - Multi-Step Forms Add-On: 1.0.5
Profile Builder - Multiple Admin E-mails Add-On: 1.0.2
Profile Builder - WooCommerce Sync Add-on: 1.5.4
Profile Builder Customizations: 1
Profile Builder Pro: 2.9.2
Query Monitor: 3.1.1
Redux Framework: 3.6.14
Regenerate Thumbnails: 3.0.2
Sepa Direct Debit (Edited): 1.6.9
Slider Revolution: 5.4.8
Smush: 2.9.1
Subscriptio: 2.3.8
UpdraftPlus - Backup/Restore: 1.15.3
User Switching: 1.4.0
WooCommerce: 3.5.1
WooCommerce - Store Toolkit: 2.0
WooCommerce Customer Relationship Manager: 3.5.12
WooCommerce EU VAT Assistant: 1.8.4.181009
WooCommerce Invoice Gateway: 1.0.2
WooCommerce js cookie fix: 1.0
WooCommerce Multiple Customer Addresses: 12.7
WooCommerce Order Status Manager: 1.9.3
WooCommerce PDF Catalog: 1.7.1
WooCommerce PDF Invoices & Packing Slips: 2.2.4
WooCommerce PDF Invoices & Packing Slips Premium Templates: 2.5.10
WooCommerce PDF Invoices & Packing Slips Professional: 2.2.9
WooCommerce Product Filter: 6.6.3
Woocommerce Products Per Page: 1.2.6
WooCommerce Shipment Tracking: 1.6.12
WooCommerce Shipping By Rules: 2.0.6
WooCommerce Stripe Gateway: 4.1.12
WooCommerce Warranty Requests: 1.8.13
Wordfence Security: 7.1.17
WP-Optimize: 2.2.6
WPBakery Page Builder: 5.5.5
WP Mail Logging: 1.8.5
WP Overnight Sidekick: 2.0.3
WP Rollback: 1.5.1
WSDesk - Wordpress HelpDesk & Support Ticket System (BASIC): 1.6.9
XTEMOS Post Types plugin: 1.6
YITH Composite Products for WooCommerce Premium: 1.1.9
YITH WooCommerce Request A Quote Premium: 2.0.15
Yoast SEO: 9.1

**Comment by RockPeach** [comment] 2018-11-13 00:33
> @RockPeach You didn't provide your Pods Admin, Settings, Debug Information above. We pretty much have to have that to determine if you've got a conflict and to determine what versions of everything else you have loaded.

Sorry @jimtrue here it is:

Debug Information
WordPress Version: 4.9.8

PHP Version: 7.0.32

MySQL Version: 5.5.5

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

Session Save Path: /var/cpanel/php/sessions/ea3

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 1024M

Pods Network-Wide Activated: No

Pods Install Location: /home/achatcloud/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Basel Child

Currently Active Plugins:

Activity Log: 2.5.1
Admin Columns: 3.3.1
Admin Menu Editor: 1.8.5
Aelia Foundation Classes for WooCommerce: 2.0.1.180821
ATUM Inventory Management for WooCommerce: 1.4.18.2
Booster Plus for WooCommerce: 4.0.1
Chats: 1.3.9
CMB2: 2.4.2
Code Snippets: 2.12.0
Custom Login Page Templates: 1.0
Custom Product Tabs for WooCommerce: 1.6.6
Duplicator Pro: 3.7.8.1
Easy WP SMTP: 1.3.7
Email Address Encoder: 1.0.9
Envato Market: 2.0.1
Filter WooCommerce Orders by Payment Method: 1.0.0
Fr Multi Bank Transfer Payment Gateways for WooCommerce: 1.0.1
Hide My WP: 5.5.7
Loco Translate: 2.1.5
Members: 2.1.0
Multi-Carrier Shipping Plugin for WooCommerce: 1.4.4
plugin load filter: 3.0.4
Pods - Custom Content Types and Fields: 2.6.11
Polylang for WooCommerce: 1.0.4
Polylang Pro: 2.4
Profile Builder - Custom CSS Classes on fields: 1.0.3
Profile Builder - Customization Toolbox Add-On: 1.0
Profile Builder - Custom Profile Menus Add-On: 1.0.7
Profile Builder - Email Confirmation Field: 1.0.4
Profile Builder - Field Visibility Add-On: 1.1.6
Profile Builder - MailChimp Add-On: 1.1.8
Profile Builder - Maximum Character Length Add-On: 1.0.0
Profile Builder - Multi-Step Forms Add-On: 1.0.5
Profile Builder - Multiple Admin E-mails Add-On: 1.0.2
Profile Builder - WooCommerce Sync Add-on: 1.5.4
Profile Builder Customizations: 1
Profile Builder Pro: 2.9.2
Query Monitor: 3.1.1
Redux Framework: 3.6.14
Regenerate Thumbnails: 3.0.2
Sepa Direct Debit (Edited): 1.6.9
Slider Revolution: 5.4.8
Smush: 2.9.1
Subscriptio: 2.3.8
UpdraftPlus - Backup/Restore: 1.15.3
User Switching: 1.4.0
WooCommerce: 3.5.1
WooCommerce - Store Toolkit: 2.0
WooCommerce Customer Relationship Manager: 3.5.12
WooCommerce EU VAT Assistant: 1.8.4.181009
WooCommerce Invoice Gateway: 1.0.2
WooCommerce js cookie fix: 1.0
WooCommerce Multiple Customer Addresses: 12.7
WooCommerce Order Status Manager: 1.9.3
WooCommerce PDF Catalog: 1.7.1
WooCommerce PDF Invoices & Packing Slips: 2.2.4
WooCommerce PDF Invoices & Packing Slips Premium Templates: 2.5.10
WooCommerce PDF Invoices & Packing Slips Professional: 2.2.9
WooCommerce Product Filter: 6.6.3
Woocommerce Products Per Page: 1.2.6
WooCommerce Shipment Tracking: 1.6.12
WooCommerce Shipping By Rules: 2.0.6
WooCommerce Stripe Gateway: 4.1.12
WooCommerce Warranty Requests: 1.8.13
Wordfence Security: 7.1.17
WP-Optimize: 2.2.6
WPBakery Page Builder: 5.5.5
WP Mail Logging: 1.8.5
WP Overnight Sidekick: 2.0.3
WP Rollback: 1.5.1
WSDesk - Wordpress HelpDesk & Support Ticket System (BASIC): 1.6.9
XTEMOS Post Types plugin: 1.6
YITH Composite Products for WooCommerce Premium: 1.1.9
YITH WooCommerce Request A Quote Premium: 2.0.15
Yoast SEO: 9.1

**Comment by jimtrue** [comment] 2018-12-01 21:32
@RockPeach Hey there, you dropped into our Slack Chat today to let us know we've not replied to you, but you didn't hang out to get my responses in our Support Chat. I'll copy them over.

My apologies that we didn't respond to you sooner, but we’re focusing heavily on Gutenberg compatibility so that may be why no one has contacted you on this one. You probably have a conflict in your 2.7.9 setup and something in your installation. 2.6.11 and 2.7 is when we switched to fully jQuery based relationship fields. Do you have a development or staging site? If not, this would be very hard to help you troubleshoot, because you'd need to take some troubleshooting steps in your staging environment.

**Comment by jimtrue** [comment] 2018-12-01 21:36
@RockPeach Also try out the HealthCheck plugin; it allows you to easily turn plugins on and off to determine which ones are conflicting. Easier than doing it in the ‘plugins’ screen, because their Troubleshooting Mode puts you into your own ‘instance’ of the website and lets you easily enable and disable plugins, themes, etc.

My guess, the issue is with Smush.

**Comment by jimtrue** [comment] 2019-02-05 13:44
@RockPeach We've never heard back from you on this one and it's been over a month. Can you check for conflicts as mentioned in our last comment?

If we don't hear back from you, we will consider the issue resolved.

**Comment by RockPeach** [comment] 2019-02-05 14:02
@jimtrue I confirm this bug is now resolved with upgrading to a newer version that was released since. I tried a Pods plugin upgrade about 2-3 weeks ago and the issue disappeared

**Comment by RockPeach** [comment] 2019-02-05 14:02
Thanks for the follow up!

**Comment by jimtrue** [comment] 2019-02-05 14:07
@RockPeach Awesome, glad to hear it! I'll close this one ;)

**Closed by jimtrue** 2019-02-05 14:07 UTC
Labels: Status: Need User Feedback, Type: Support
