### ISSUE TITLE
Datepicker field not pubblishing the data

### ISSUE THREAD

**Issue by brakko-b** [pods-framework/pods#5264] opened 2019-01-08 16:13 UTC
Hi, the data picker filed is not working properly. 

when I insert a value and try to Update a post in the Chrome dev tool console i see those errors.

Uncaught (in promise) ReferenceError: currentURL is not defined
    at then.catch.e (content_script_bundle.js:13)
then.catch.e @ content_script_bundle.js:13
Promise.catch (async)
(anonymous) @ content_script_bundle.js:13
(anonymous) @ content_script_bundle.js:13
f @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:13
f @ content_script_bundle.js:1
a @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:13
(anonymous) @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:13
1111 @ content_script_bundle.js:13
n @ content_script_bundle.js:1
1110 @ content_script_bundle.js:1
n @ content_script_bundle.js:1
1110 @ content_script_bundle.js:1
(anonymous) @ content_script_bundle.js:1

index.js?ver=1546864911:1 POST https://www.abacatanzaro.it/wp-admin/post.php?post=1812&action=edit&classic-editor=1&meta_box=1&_locale=user 500 (Internal Server Error)
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
tryCatch @ wp-polyfill.min.2ae96136.js:3
invoke @ wp-polyfill.min.2ae96136.js:3
t.(anonymous function) @ wp-polyfill.min.2ae96136.js:3
n @ index.js?ver=1546864911:1
c @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
g @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
i @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
w @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
i @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
_ @ index.js?ver=1546864911:1
REQUEST_META_BOX_UPDATES @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:12
dispatch @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:1
n @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
v @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ lodash.min.59550321.js:49
(anonymous) @ index.js?ver=1546864911:50
(anonymous) @ index.js?ver=1546864911:12
dispatch @ index.js?ver=1546864911:50
(anonymous) @ index.js?ver=1546864911:50
tryCatch @ wp-polyfill.min.2ae96136.js:3
invoke @ wp-polyfill.min.2ae96136.js:3
t.(anonymous function) @ wp-polyfill.min.2ae96136.js:3
r @ index.js?ver=1546864911:12
a @ index.js?ver=1546864911:12
Promise.then (async)
r @ index.js?ver=1546864911:12
a @ index.js?ver=1546864911:12
Promise.then (async)
r @ index.js?ver=1546864911:12
a @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:50
REQUEST_POST_UPDATE @ index.js?ver=1546864911:50
(anonymous) @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:1
value @ index.js?ver=1546864911:1
onClick @ index.js?ver=1546864911:50
Fg @ react-dom.min.713f0afa.js:154
Eg @ react-dom.min.713f0afa.js:13
Hg @ react-dom.min.713f0afa.js:13
ae @ react-dom.min.713f0afa.js:15
Ig @ react-dom.min.713f0afa.js:155
Hc @ react-dom.min.713f0afa.js:15
Jc @ react-dom.min.713f0afa.js:16
gh @ react-dom.min.713f0afa.js:39
lg @ react-dom.min.713f0afa.js:148
re @ react-dom.min.713f0afa.js:23
Xb @ react-dom.min.713f0afa.js:40
ng @ react-dom.min.713f0afa.js:149
Se @ react-dom.min.713f0afa.js:40

post.php?post=1812&action=edit:1 Uncaught (in promise) Response {type: "basic", url: "https://www.abacatanzaro.it/wp-admin/post.php?post…ion=edit&classic-editor=1&meta_box=1&_locale=user", redirected: false, status: 500, ok: false, …}body: (...)bodyUsed: falseheaders: Headers {}ok: falseredirected: falsestatus: 500statusText: "Internal Server Error"type: "basic"url: "https://www.abacatanzaro.it/wp-admin/post.php?post=1812&action=edit&classic-editor=1&meta_box=1&_locale=user"__proto__: Response
Promise.then (async)
REQUEST_META_BOX_UPDATES @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:12
dispatch @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:1
n @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
v @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ index.js?ver=1546864911:1
(anonymous) @ lodash.min.59550321.js:49
(anonymous) @ index.js?ver=1546864911:50
(anonymous) @ index.js?ver=1546864911:12
dispatch @ index.js?ver=1546864911:50
(anonymous) @ index.js?ver=1546864911:50
tryCatch @ wp-polyfill.min.2ae96136.js:3
invoke @ wp-polyfill.min.2ae96136.js:3
t.(anonymous function) @ wp-polyfill.min.2ae96136.js:3
r @ index.js?ver=1546864911:12
a @ index.js?ver=1546864911:12
Promise.then (async)
r @ index.js?ver=1546864911:12
a @ index.js?ver=1546864911:12
Promise.then (async)
r @ index.js?ver=1546864911:12
a @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:50
REQUEST_POST_UPDATE @ index.js?ver=1546864911:50
(anonymous) @ index.js?ver=1546864911:12
(anonymous) @ index.js?ver=1546864911:1
value @ index.js?ver=1546864911:1
onClick @ index.js?ver=1546864911:50
Fg @ react-dom.min.713f0afa.js:154
Eg @ react-dom.min.713f0afa.js:13
Hg @ react-dom.min.713f0afa.js:13
ae @ react-dom.min.713f0afa.js:15
Ig @ react-dom.min.713f0afa.js:155
Hc @ react-dom.min.713f0afa.js:15
Jc @ react-dom.min.713f0afa.js:16
gh @ react-dom.min.713f0afa.js:39
lg @ react-dom.min.713f0afa.js:148
re @ react-dom.min.713f0afa.js:23
Xb @ react-dom.min.713f0afa.js:40
ng @ react-dom.min.713f0afa.js:149
Se @ react-dom.min.713f0afa.js:40

i really don't know what to do.

**Comment by jimtrue** [comment] 2019-01-08 17:19
@brakko-b Can you please provide the Debug details from your installation. We need to make sure what your environment is (or if you have any conflicting plugins) to help you troubleshoot.

That's available under Pods Admin, Settings. Just add it to this ticket.

**Comment by jimtrue** [comment] 2019-01-09 19:01
@brakko-b It looks like from the error thread that something is choking the input and looks like you might be dealing with a plugin conflict.

I'd like to suggest you attempt disabling some plugins; I prefer the HealthCheck plugin for this since it seems to do the best job of "being on the page with the problem" while activating and deactivating plugins without impacting the public.  Just drop it into troubleshooting mode and go to the page with the issue and activate and deactivate plugins from the admin toolbar. It's also especially nice for production websites because you can troubleshoot live without impacting your regular users.

**Comment by jimtrue** [comment] 2019-01-09 19:02
It will also let you see if disabling one will fix the issue immediately.

**Comment by JoryHogeveen** [comment] 2019-11-18 18:56
@brakko-b We made a few bugfixes for the date field in the latest releases. Can you confirm this bug is fixed? I cannot reproduce anymore.

**Comment by JoryHogeveen** [comment] 2020-03-23 20:33
@brakko-b 
Closing this issue since we didn't receive a reply. Feel free to reopen if needed.

**Closed by JoryHogeveen** 2020-03-23 20:33 UTC
Labels: Status: Need User Feedback
