### ISSUE TITLE
No warning if required pod field is empty

### ISSUE THREAD

**Issue by vgstef** [pods-framework/pods#6442] opened 2022-02-10 05:22 UTC
### Description

We have a custom post type with a required fields pod field (relationship with multiple select). If we forget to fill the required field and we click on Publish, Wordpress save the post, but there is a new page saying the required field is empty and with a link the go back.

If we click that go back link, we end up on a new empty custom post. 

If I go in the post listing, I see the post has been saved. The standard wordpress fields have been saved (i.e. title, content, date), but all pods fields are empty.

### Version

2.8.10

### Testing Instructions

1. Have custom post with a few pods fields and one that is a required field
2. Create new post and fill out the fields leaving the required field empty.
3. Publish the post

### Screenshots / Screencast

This is the whole page that appears after click "publish". 

Sorry, it's in french, but "Lien entreprise" is the required pods field, and the "Retour" means to go back.

![image](https://user-images.githubusercontent.com/5083355/153342394-22ee5bf9-5d8d-4922-af9d-3c526a3e1bb2.png)

### Possible Workaround

Pods should disable the "Publish" or "Update" button until the required fields a filled.

Or Pods should save the data even if the required fields are empty, because Wordpress saved it anyway. 

And the go back link should bring back to the post being edited.

**Comment by JoryHogeveen** [comment] 2022-02-14 08:30
Duplicate of #5464

**Closed by JoryHogeveen** 2022-02-14 08:30 UTC
Labels: Type: Bug
