### ISSUE TITLE
[Pods 2.8 Bug] moving fields drag and drop between groups not possible

### ISSUE THREAD

**Issue by vitmarks** [pods-framework/pods#6114] opened 2021-09-02 12:17 UTC
## Pods 2.8 version

2.8.0-b-5

## Description

sorry if it is already discussed, but could not find it, but moving fields drag and drop between groups not possible? or i cannot find where i can change the group of a field. should i delete it and create it again on the other group?

## Testing instructions

create new CPT and create few groups and within all groups some fields. Now try to move a filed from group 1 to group 2

## Expected behavior

should be possible also move fields between groups like it is within a group already solved by change the position with drag and drop

## Possible workaround

delete a field from group 1 and recreate it on group 2

## Other super helpful information

fresh WP 5.8

**Comment by sc0ttkclark** [comment] 2021-09-03 18:52
@zrothauser can you remind me the historical issue that we faced initially trying to do this? What kind of effort is involved in solving it post-Repeatable Fields DFV work?

**Comment by zrothauser** [comment] 2021-09-03 21:25
@sc0ttkclark This is a duplicate of https://github.com/pods-framework/pods/issues/5937. I believe it was just the complexity of restructuring the drag-and-drop to work between groups and not just inside of them.

**Comment by sc0ttkclark** [comment] 2021-09-03 21:27
@zrothauser thanks! I'll close this one as a duplicate and we can continue looking into it over in 2.9 after repeatable fields

**Closed** 2021-09-03 21:41 UTC
Labels: Closed: Duplicate
