### ISSUE TITLE
Missing Styles of dfv form field using $pods->form(...)

### ISSUE THREAD

**Issue by creabrain** [pods-framework/pods#5056] opened 2018-07-09 14:25 UTC
**Describe the bug**
Styles of pods form DFV fields not working correctly in plain wordpress installation with pod.
JavaScript to upload and delete file works but the styles of pods 2.6.x do not work anymore.

**To Reproduce**
1. Create Custom Post Type with DFV Field
2. Add a form for Custom Post Type in theme like a page template over $pods->form( ..

**Expected behavior**
Working styles of frontend form in Pods 2.7.x like in previous version Pods 2.6.x.

**Screenshots**
![dfv-field-missing-styles](https://user-images.githubusercontent.com/3832618/42456221-87977c76-8394-11e8-9df0-2ac85186bf8a.png)

**Comment by jimtrue** [comment] 2018-08-15 21:04
@creabrain I'm very sorry no one has responded to this ticket; you have just dropped into our Slack Chat and dropped a note trying to bring attention to this:

> Hi pods staff. I have an open ticket unanswered since july. Is thttps://github.com/pods-framework/pods/issues/5056 . I know there where holidays over july and august but problem exist since version 2.7x. Will $pods-form(... be support in future?

This is just a note, but responding in your actual Ticket report is the best place to bring attention to them, because it broadcasts that notice to every single developer on the project. 

We also have a template for the Bug Reports that asks for information from you, which it looks like you removed most of that template, specifically the section requesting the Pods Admin, Settings, Debug Details.

It may seem inconsequential to you, but we really do require the Debug Details at a minimum to be included for a new Bug report. Knowing exactly what versions of plugins you're using, which theme, etc. all plays a part in troubleshooting any problems you're having or recreating the issue ourselves.

**Comment by pglewis** [comment] 2018-08-16 22:34
The delay is entirely my fault.   We're in a deep dive to bring a bunch of new features in 2.8 and with a team this small that means issues are on a longer turn-around cycle than they have been.  

I'll try to reproduce this locally, it's probably as simple as a missing container somewhere after the big CSS refactor.  Very sorry for the trouble.

**Comment by pglewis** [comment] 2018-08-21 17:25
Alright, I'm finally able to dig my way down to this one.  Any other details I might need to know about the field and the `pods_form()` call in order to reproduce it, @creabrain?

**Comment by pglewis** [comment] 2018-08-21 19:12
**To Reproduce**
Steps to reproduce the behavior:
1. Package: 
<details>
{"meta":{"version":"2.6.11","build":1534878733},"pods":{"358":{"id":358,"name":"_a_file_upload","label":"____A file upload","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"file_upload":{"id":359,"name":"file_upload","label":"File Upload","description":"","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"multi","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""}},"show_in_menu":"1","label_singular":"____A file upload","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"_a_file_upload","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_test_tax":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_single":"Test Detail","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","rest_base":"_a_file_upload","read_all":"0","write_all":"0"}}}
</details>

2. Add a post on the post type with the slug `test-record`

3. Add a form shortcode to the post `[pods-form name="_a_file_upload" slug="test-record" fields="file_upload"]`

4. Go to the post's page in the front end and add some files

**Comment by pglewis** [comment] 2018-08-22 00:00
PR started: #5127

**Comment by creabrain** [comment] 2018-08-23 12:56
I think that is not the solution. What i mean with frontend is to add pods form over function without shortcode in frontend. Like in that way https://pods.io/docs/code/pods/form/.

Problem is that registered style pods-form scripts pods are not available in html source.
`
wp_enqueue_script( 'pods' );
wp_enqueue_style( 'pods-form')
`

**Comment by pglewis** [comment] 2018-08-23 17:02
> Problem is that registered style pods-form scripts pods are not available in html source.
> wp_enqueue_script( 'pods' ); wp_enqueue_style( 'pods-form')

We are moving towards only needing the `pods-form` styles for the front end and the full `pods` styles will be reserved for admin only.  There are some shared styles that still need to be moved around so that this will work for file upload and relationship/list view, thus the PR is still "In Progress" and not "Ready for Review".

**Comment by pglewis** [comment] 2018-08-23 21:52
@creabrain: #5127 looks ready to test.  I've checked it on a front end page via shortcode and using `form()` with both file upload and a relationship using List View and both share the list style.  Everything looks presentable to me so take a look at that branch and see if it resolves it for you.

**Comment by quasel** [comment] 2018-09-03 07:01
any feedback at the PR @creabrain

**Closed** 2018-10-27 16:16 UTC
Labels: Component: CSS, Keywords: Regression, Status: Fixed / Needs Testing, Type: Bug
