### ISSUE TITLE
ACT orderby not working

### ISSUE THREAD

**Issue by Dooza** [pods-framework/pods#3013] opened 2015-06-08 16:42 UTC
I am sure this was working before, but an ACT on my site is now not displaying in the correct order. This is my code:

    $params = array(
          'search' => false,
          'pagination' => false,
          'limit' => -1,
          'orderby' => 't.slide_order ASC'
    );
    $slides = pods( 'slide',$params );

Any ideas what is going on?

Oddly enough, I can no longer order these in the back-end either, there is no drag and drop capability any more.

Cheers,

Steve

**Comment by sc0ttkclark** [comment] 2015-06-08 16:46
What field type is `slide_order`? And to confirm, `slide` is an Advanced Content Type, not a Custom Post Type, right?

**Comment by Dooza** [comment] 2015-06-08 16:51
Hi Scott, its a Plain Number field type, and is an Advanced Content Type.

**Comment by quasel** [comment] 2015-06-08 16:56
pls try pods.io/latest  should be fixed with 2.5.3 
#2843

**Comment by pglewis** [comment] 2015-06-08 20:34
I wasn't able to recreate this locally with 2.x, 2.5.2, or 2.5.  There could be something different environmentally but before we check deeper into that: are you able to test against the current 2.x branch to see if it is resolved there?

**Comment by pglewis** [comment] 2015-06-08 21:52
A quick note here: the part I couldn't reproduce is the `'orderby'` in the params.  

The drag/drop reordering probably should have it's own issue as it very well could be a separate cause.

**Comment by pglewis** [comment] 2015-06-09 00:03
#3015 address the drag/drop reordering and has a patch ready to go out with 2.5.3

**Comment by Dooza** [comment] 2015-06-09 08:59
Using the 2.5.3 Alpha 1 has fixed the drag and drop but the orderby is still causing confusion.

This is the pod setup:
![slide](https://cloud.githubusercontent.com/assets/9673250/8054060/9733f382-0e8d-11e5-919b-4c7188a562f6.jpg)

This is the data:
![slides](https://cloud.githubusercontent.com/assets/9673250/8054066/a0c12618-0e8d-11e5-9e42-be4c5aa8f1f8.jpg)

Without orderby I get this order:

Prolyte
ArKaos
Chroma-Q
Jands
LumenRadio

With modified, created, permalink or slide_order ASC I get this order:

LumenRadio
Chroma-Q
Jands
ArKaos
Prolyte

With modified, created, permalink or slide_order DESC I get this order:

Chroma-Q
LumenRadio
Prolyte
ArKaos
Jands

With name or link ASC I get this order:

Prolyte
ArKaos
Chroma-Q
Jands
LumenRadio

With name or link DESC I get this order:

ArKaos
Prolyte
LumenRadio
Jands
Chroma-Q

Oddly I get an error if I try to use image in the orderby. Same message as if I put a random name in.

Not sure if this will help but I wanted to try to figure it out and give you plenty of detail.

Cheers,

Steve

**Comment by quasel** [comment] 2015-06-09 12:16
Strange - can you try and add `pods_debug_sql=1`to the query string ? maybe this gives a better hint what is happening. 

Did you try to deactivate all other plugins (just to be sure) and clear Pods Cache (Pods Admin -> Settings) ?

**Comment by Dooza** [comment] 2015-06-09 12:19
Not tried deactivating everything yet, will have a go in a moment.

This is the debug sql

`SELECT
                
                DISTINCT
                `t`.*
                FROM `vc7ah6tzfk_pods_slide` AS `t`
                
                
                
                
                ORDER BY `t`.`slide_order` ASC, `t`.`name`, `t`.`id``

**Comment by Dooza** [comment] 2015-06-09 12:21
I just ran this SQL directly using phpMyAdmin and it displays as I expect.

**Comment by quasel** [comment] 2015-06-09 12:23
well then this might be a strange caching issue ...

**Comment by Dooza** [comment] 2015-06-09 12:25
I cleared the pods cache and its not changed, I will deactivate everything apart from pods and see what happens.

**Comment by Dooza** [comment] 2015-06-09 12:27
Now have a blank white screen!

**Comment by Dooza** [comment] 2015-06-09 12:45
Managed to get back in by changing the template in phpMyAdmin, and deleting 2 blank lines at the bottom of wp_config.php. When changing back to my template all my widgets had been made inactive so I restored from this mornings backup. Phew, almost panicked then!

**Comment by quasel** [comment] 2015-06-09 12:48
wierd things happening on your side - but this shouldn't be related to pods ^^ glad you could fix it.
Is it now roking for you or still issues left?

**Comment by Dooza** [comment] 2015-06-09 12:51
Still got the ACT not ordering correctly. I am going to try to deactivate more plugins, but not all of them this time, I think there are some needed to prevent it from going tits up on me.

**Comment by Dooza** [comment] 2015-06-09 13:49
Looks like Contact Form 7 didn't like being turned off due to my functions.php file calling it. I have now tested with as minimal plugins as possible and it made no difference to the ordering.

**Comment by Dooza** [comment] 2015-06-09 14:00
Sorry all, having checked the html source not the dom source, it appears that is ordering it correctly, it's  flexslider that is doing some odd manipulation and cloning the slides and making up some strange order. This will be why my test results don't make any sense at all.

**Comment by quasel** [comment] 2015-06-09 14:04
thx for your feedback - so it seems it's not pods related - hope you find a fix for the slider!

**Closed by quasel** 2015-06-09 14:04 UTC
Labels: Bug: Normal, Bug: Regression, Needs Contributor, Needs Research, Needs User Feedback

**Comment by Dooza** [comment] 2015-06-09 14:26
I have upgraded to the latest Flexslider and all is well now. Thanks again for the help!
