### ISSUE TITLE
Relationship drop down (simple custom defined list) breaks when Yoast SEO 7 installed

### ISSUE THREAD

**Issue by nf0l** [pods-framework/pods#4784] opened 2018-03-07 13:01 UTC
Relationship drop down (simple custom defined list) breaks when 'Advanced Options' --> 'supports' --> 'editor' is unticked and Yoast SEO plugin installed.

**Comment by jimtrue** [comment] 2018-03-07 13:04
Duplicate of #4783

**Closed** 2018-03-07 13:05 UTC
Labels: Duplicate
