### ISSUE TITLE
[feature request] "built in" image resizing

### ISSUE THREAD

**Issue by martinstark** [pods-framework/pods#795] opened 2012-11-27 12:50 UTC
Maybe something like this is already available, or maybe the request for a function like this is too specific, since it's relatively easy to achieve already for someone familiar with both Pods and WP functions.

(feel free to remove this suggestion if you think it's not something that fits, or if it's redundant)

Rather than having to define custom image sizes in functions.php (which is easy enough now that I'm used to it), it'd be nice to have image sizes relating to Pods centralized in the Pods setup page.

When you add a file upload field and set it to image, the advanced tab could have the following option:
- Resize this/these image(s) to width x height 
- Crop? true/false. 
- Size name:
- Add another image size (button that adds another size)

And then maybe replace:

$imgInfo = wp_get_attachment_image_src( $pod->field( 'images.ID' ), 'small_image' );
$imgInfo = array(
    'url'     => $imgInfo[0],
    'width'   => $imgInfo[1],
    'height'  => $imgInfo[2],
    ....
);

With a custom pods function.

Also, if a Pods function could replace what I'm doing here in a cleaner manner that'd be amazing:

<?php
    // Get all IDs from images field for this pod
    $image_ids = $pod->field( 'images.ID' );
    $i = 1;

```
// Create an array with all large and small images
foreach ( $image_ids as $image_id ){

    // Use a pre-defined, named image size (created in functions.php)
    $imgLarge = wp_get_attachment_image_src( $image_id , 'img-large' );
    $imgSmall = wp_get_attachment_image_src( $image_id , 'img-thumb' );

    $images[ $i ] = array(
        'large' => $imgLarge[ 0 ],
        'small' => $imgSmall[ 0 ]
    );
    $i++;
}
```

?>

**Comment by pglewis** [comment] 2016-01-24 05:22
Is this potentially a dupe of or solved by #615?

**Closed** 2018-05-03 20:08 UTC
Labels: Feature, Help Wanted, Needs Tasklist, Needs Votes
