### ISSUE TITLE
Field Groups - allow fields to be moved to different field groups

### ISSUE THREAD

**Issue by millionleaves** [pods-framework/pods#6123] opened 2021-09-07 04:19 UTC
## Problem

I suspect this may be coming later, but it would be useful to rearrange existing fields into new field groups in Pods 2.8. Field Groups is a big deal for me, 

## Proposed Solution

1. Provide the ability to drag fields between field group.
2. Provide a selection option on each field to choose a different field group

## Workaround

I've managed so far by manually editing the wp_postmeta for each field and changing the group ID, which works but obviously isn't an ideal solution.

**Comment by sc0ttkclark** [comment] 2021-09-09 03:56
Duplicate of #5937

**Closed by sc0ttkclark** 2021-09-09 03:56 UTC
Labels: Type: Enhancement
