### ISSUE TITLE
Error saving CPT on Gutenberg

### ISSUE THREAD

**Issue by fabiomsnunes** [pods-framework/pods#5484] opened 2019-09-25 13:56 UTC
**Describe the bug**
If we try to save a custom post type, with required fields, that are not yet filled, it throws a error 500 on console.
We only get this behavior on Gutenberg. Also, for Gutenberg to be enabled for CPT we needed to enable REST API since Gutenberg uses REST

**To Reproduce**
1. Enable REST API on a pod
2. Be sure to have at least one required field
3. Add a new CPT entry
4. Give it same random name and try to save as draft (with the pods fields empty)
5. See the console for the error 500

**Expected behavior**
Not to throw a error (duh!), but also to have REST enabled by default since Gutenberg is the default editor.

## Pods Version
2.7.15

## WordPress Environment

<details>

`
### wp-core ###

version: 5.2.2
site_language: pt_PT
user_language: en_US
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/wplus/docs.wplus.pt
wordpress_size: 72.82 MB (76358655 bytes)
uploads_path: /home/wplus/docs.wplus.pt/wp-content/uploads
uploads_size: 4.07 MB (4265682 bytes)
themes_path: /home/wplus/docs.wplus.pt/wp-content/themes
themes_size: 2.67 MB (2796237 bytes)
plugins_path: /home/wplus/docs.wplus.pt/wp-content/plugins
plugins_size: 28.15 MB (29519747 bytes)
database_size: 4.08 MB (4283093 bytes)
total_size: 111.79 MB (117223414 bytes)

### wp-dropins (2) ###

advanced-cache.php: true
db.php: true

### wp-active-theme ###

name: wedocs-child
version: undefined
author: Anonymous
author_website: (undefined)
parent_theme: weDocs
theme_features: root-relative-urls, bootstrap-top-navbar, bootstrap-gallery, nice-search, automatic-feed-links, menus, post-thumbnails, editor-style, widgets
theme_path: /home/wplus/docs.wplus.pt/wp-content/themes/wedocs

### wp-themes (2) ###

Twenty Nineteen: version: 1.4, author: the WordPress team
weDocs: version: 0.1, author: Tareq hasan

### wp-plugins-active (12) ###

Gravity Forms: version: 2.4.12, author: rocketgenius
Gravity Forms Gutenberg Add-On: version: 1.0-rc-1.4, author: rocketgenius
Gravity Forms Partial Entries Add-On: version: 1.3, author: rocketgenius
Gravity Forms Webhooks Add-On: version: 1.1.5, author: rocketgenius
Pods - Custom Content Types and Fields: version: 2.7.15, author: Pods Framework Team
Pods Gravity Forms Add-On: version: 1.4.1, author: Pods Framework Team
Query Monitor: version: 3.3.7, author: John Blackbourn
User Switching: version: 1.5.2, author: John Blackbourn & contributors
weDocs: version: 1.5, author: Tareq Hasan
WPlus - core: version: 1.0.23.1, author: WPlus - Soluções web à medida
WPlus - docs: version: 1.0.13, author: WPlus - Soluções web à medida
WP Rocket: version: 3.3.2, author: WP Media

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1656
imagemagick_version: ImageMagick 6.7.8-9 2019-08-08 Q16 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 8 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 12288
	imagick::RESOURCETYPE_MAP: 8 GB
	imagick::RESOURCETYPE_MEMORY: 4 GB
	imagick::RESOURCETYPE_THREAD: not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 3.10.0 x86_64
httpd_software: Apache
php_version: 7.2.22 64bit
php_sapi: cgi-fcgi
max_input_variables: 10000
time_limit: 90
memory_limit: 512M
max_input_time: 90
upload_max_size: 64M
php_post_max_size: 64M
curl_version: 7.66.0 OpenSSL/1.0.2t
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.27
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/wplus/docs.wplus.pt/wp-content
WP_PLUGIN_DIR: /home/wplus/docs.wplus.pt/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
pods-session-save-path: /var/cpanel/php/sessions/ea-php72
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: Yes
pods-object-cache-redis: No
pods-memory-current-usage: 13.774M
pods-memory-current-usage-real: 16.000M
pods-network-wide: No
pods-install-location: /home/wplus/docs.wplus.pt/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes

`

</details>

**Comment by JoryHogeveen** [comment] 2019-11-05 20:24
Can confirm this.
Pods returns a WP_Error with the validation error as it's message.
@sc0ttkclark Do you know why this is? And what should it actually return?

**Comment by sc0ttkclark** [comment] 2021-08-17 17:02
Needs retesting on 2.8

**Comment by pdclark** [comment] 2021-08-20 05:16
In testing on `2.8.0b5`, the required field correctly showed in red, "___ field is required" message.
It's worth noting that the post also displayed a success message and saved even though the required field wasn't filled out.

<img width="521" alt="required-field" src="https://user-images.githubusercontent.com/126889/130183021-2baca4f8-68db-4490-b574-e467413c3496.png">

**Comment by sc0ttkclark** [comment] 2021-08-20 18:43
Adding Gutenberg form validation integration in another release, we can punt this issue forward since we want that here but at least we can verify that the error validation is showing inline for now.

**Comment by smarques** [comment] 2022-01-07 13:28
I can confirm this bug. If I disable Gutenberg things seem to work again.

**Comment by sc0ttkclark** [comment] 2022-05-14 01:08
Closing in favor of #2424

**Closed by sc0ttkclark** 2022-05-14 01:08 UTC
Labels: Type: Bug, Status: Reproduced, Component: Block Editor
