### ISSUE TITLE
Improper prefixing used for "Display Field" for relationship

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods#2652] opened 2015-01-26 18:58 UTC
As [reported in the forums](http://pods.io/forums/topic/relationships-no-longer-working/) a user has a relationship between meta storage custom post types, and is setting a custom display field. In this case `{@company_name}`. Then when they got to the post editor, they see this error:

`WordPress database error: [Unknown column ‘t.company_name’ in ‘field list’]
SELECT DISTINCT t.ID, t.company_name, t.post_type FROM wp_posts AS t WHERE ( ( t.post_status IN ( “publish” ) ) AND ( t.post_type = “company” ) ) ORDER BY t.menu_order, t.post_title, t.post_date /* From [www.devkitmagazine.com/wp-admin/post-new.php?post_type=product] in [/nas/wp/www/cluster-2214/devkit/wp-content/plugins/pods/classes/PodsData.php:2055] */
Database Error; SQL: SELECT DISTINCT t.ID, t.company_name, t.post_type FROM wp_posts AS t WHERE ( ( t.post_status IN ( “publish” ) ) AND ( t.post_type = “company” ) ) ORDER BY t.menu_order, t.post_title, t.post_date; Response: Unknown column ‘t.company_name’ in ‘field list’
`

Looks to me like a prefixing problem as the unknown column `t.company_name` wouldn't exist. The relationship is from a field called "company_name" to a Pods that has a field called "company_name". So the query should be for "company_name.company_name" right?

And yes, maybe the issue is that this is an edge case where same.same traversal causes a problem.

**Comment by Shelob9** [comment] 2015-01-26 23:42
My theory on the edge case seems to be invalid: http://pods.io/forums/topic/relationships-no-longer-working/#post-188880

**Comment by Shelob9** [comment] 2015-01-27 02:27
Debug information form reporting user:

Debug Information

WordPress Version: 4.1

PHP Version: 5.3.2-1

MySQL Version: 5.5.40

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36

Session Save Path: /var/lib/php5

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /nas/wp/www/cluster-2214/devkit/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Devkit Magazine

Currently Active Plugins:

AdPress | Ads Manager: 1.0.0
Go Go Gordon 2: 0.2
Gravity Forms: 1.8.22
Gravity Forms Styler: 1.2
Gravity Forms Tooltips: 1.0.1
JSON Basic Authentication: 0.1
JSON REST API: 1.1.1
LayerSlider WP: 5.2.1
Pods – Custom Content Types and Fields: 2.5.1.1
Pods Frontier Auto Template: 1.1.2
Pods Gravity Forms Add-On: 1.0 Alpha 8
Pods JSON API: 0.1
TinyMCE Advanced: 4.1.7
VaultPress: 1.7.0
WP CSV: 1.6.5
wpDataTables: 1.5.3

**Comment by jamesgol** [comment] 2015-01-27 04:16
I was just able to reproduce this on my test setup.

**Comment by sc0ttkclark** [comment] 2015-01-27 04:43
This never worked for relationships and isn't a bug, just something that would be an enhancement. I'm pretty sure this is a duplicate of another issue with that said.

**Comment by sc0ttkclark** [comment] 2015-01-27 04:47
Duplicate of #1240

**Closed by sc0ttkclark** 2015-01-27 04:47 UTC
Labels: Enhancement, Needs Contributor, Needs Research

**Comment by JonBarrett** [comment] 2015-01-27 22:05
1) Tried disabling all the plugins. No change

2) Just to prove I’m not going mad, here is a video of the same function working with two pods with related fields that I created a couple of months ago: http://screencast.com/t/1W8e2Rsgn

**Comment by jamesgol** [comment] 2015-01-27 22:09
@JonBarrett In your screencast the title field and company are both the same "Vishay".  So that doesn't prove that it is working.  Can you change the company field to something unique and try again?

I tried to make it work on several old versions and I had no luck making it work at all.

**Comment by JonBarrett** [comment] 2015-01-27 22:56
You are correct, I've changed the title to 'One' and it is showing as 'One' in the drop-down. Thus, it never was working. Shows I don't know what I'm doing!

That's plan A down the drain.

**Comment by Shelob9** [comment] 2015-04-01 17:30
Fixed via #2654
