### ISSUE TITLE
Custom Settings Page: Syntax Highlighting doesn't work

### ISSUE THREAD

**Issue by redpik** [pods-framework/pods#2875] opened 2015-04-30 07:28 UTC
It's impossible to save / edit a code field on a Custom Settings Page.
the field stays blank.

**Comment by jimtrue** [comment] 2015-04-30 08:38
You have another plugin competing with CodeMirror, the JS library driving the code editor. Have you tried with other plugins deactivated. I specifically ran into this issue with debug console running.

**Comment by redpik** [comment] 2015-04-30 13:42
no plugins, except pods.
last WP version.
last pods version.
just created a custom settings page.
add a code field type, default options.

go in your settings page, put some HTML items (or just lorem ipsum text), save.
ho no! it's empty.

**Comment by jimtrue** [comment] 2015-04-30 13:56
My apologies, @redpik I was testing this on my patched version of Pods running the latest from GitHub (http://pods.io/latest/) the 2.5.2. This was apparently fixed in 2.5.2. I did a test on another site running 2.5.1.2 and I saw the exact same issue.

**Comment by redpik** [comment] 2015-04-30 13:57
Good news. Thanx Jim!

**Comment by Shelob9** [comment] 2015-05-02 01:11
@jimtrue Why is this assigned to me and what needs done, sounds like a duplicate of a fixed issue...

**Comment by jimtrue** [comment] 2015-05-02 01:31
Could not find your existing issue. It is fixed in the patch that hasn't been released yet. That's what I noted above.

**Comment by redpik** [comment] 2015-05-21 13:08
Hi,
same bug with file field type.
test with Pods **2.5.2** & Pods **2.5.3 alpha 1**.

why this terrible regression?

**Comment by jimtrue** [comment] 2015-05-21 13:20
@redpik What is the issue with the file field type? There is no syntax highlighting with a file field and it sounds like a separate issue. I just checked and the Code Syntax Highlighting is working perfectly with 2.5.2. This issue is CLOSED as patched in 2.5.2. If you have another issue, you need to open it separately for that item and give us examples of what the problem is.

**Closed** 2015-05-21 13:31 UTC
Labels: Bug: Data Loss, Bug: Regression, Verified/Reproduced
