### ISSUE TITLE
Recent Pods Update: Edit Pods Screen Empty

### ISSUE THREAD

**Issue by yabdali** [pods-framework/pods#7326] opened 2024-07-16 22:11 UTC
### Description

Repost from WP forums where it was already confirmed by another two users. After update WordPress and Pods Framework, facing issues with Pods Frame.
The screenshots is provided below and the environment info listed as well. Appreciate your help and support, thanks.
[https://wordpress.org/support/topic/recent-pods-update-edit-pods-screen-empty/#post-17893937
](https://wordpress.org/support/topic/recent-pods-update-edit-pods-screen-empty/#post-17893937
)
[https://imgur.com/a/VPaT9WO](https://imgur.com/a/VPaT9WO)

### Version

3.2.4

### Testing Instructions

After update WordPress and Pods Framework, whenever I go to the Pods Admin>Edit Pods>Pod X I get a blank screen. for the pods section! I restarted the server and cleared the transients as well as the Pods cache (Admin> Settings>Clear Pods Cache. Even when I access the Admin settings I see the screen elements in the loading state. 

### Screenshots / Screencast

![pod_edit](https://github.com/user-attachments/assets/62ba3c93-8f9b-423c-b749-1061e30d28ad)
![pods_admin](https://github.com/user-attachments/assets/095bb8fc-fd4b-4ca7-bbee-fe54e44a2b04)
![wp_log](https://github.com/user-attachments/assets/ef08d98e-b8e1-4e97-b7d4-48d05ba5d9e0)

### Site Health Information

```text
WordPress Version 6.6
Server architecture Linux 6.1.0-21-amd64 x86_64
Web server nginx/1.27.0
PHP version 8.2.20 (Supports 64bit values)
PHP SAPI fpm-fcgi
PODs Infos

Pods Version 3.2.4
Pods Version (First installed) 3.2.1.1
Pods Version (Last updated from) 3.2.2
Server Software nginx/1.27.0
Your User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Session Save Path
Session Save Path Exists No
Session Save Path Writeable No
Session Max Lifetime 1440
Opcode Cache: Apc No
Opcode Cache: Memcached No
Opcode Cache: OPcache Yes
Opcode Cache: Redis No
Object Cache: APC No
Object Cache: APCu No
Object Cache: Memcache No
Object Cache: Memcached No
Object Cache: Redis No
Current Memory Usage 15.978M / 350M
Current Memory Usage (real) 18.000M
Pods Network-Wide Activated No
Pods Install Location /wp-content/plugins/pods/
Pods Developer Activated No
Pods Tableless Mode Activated No
Pods Relationship Table Enabled Yes
Pods Relationship Table Count 10
Pods Light Mode Activated No
Pods Strict Activated No
Pods Allow Deprecated Yes
Pods API Cache Activated Yes
Pods Shortcode Allow Evaluate Tags No
Pods Can Use Sessions No
Allow Pods to create and manage custom fields on any content type created/extended through Pods Enable [types_only=0]
Watch changed fields for use in hooks Enable [watch_changed_fields=1]
Watch WP Metadata calls Enable [metadata_integration=1]
Override WP Metadata values Enable [metadata_override_get=1]
Register meta fields Enable [register_meta_integration=1]
Show Pods fields in Media Library modals Disable [media_modal_fields=1]
Secure anonymous public form submissions using PHP sessions (potential performance impacts) Disable [session_auto_start=0]
Dynamic Features Enable [dynamic_features_allow=1]
Dynamic Features to Enable Display, Form, and View [dynamic_features_enabled=display,form,view]
Access-related Restricted Messages Disable [show_access_restricted_messages=0]
Access-related Admin Notices Enable [show_access_admin_notices=1]
Allow SQL clauses to be used in Dynamic Features Disable [dynamic_features_allow_sql_clauses=0]
Display callbacks Customized [display_callbacks=customized]
Display callbacks allowed esc_attr,esc_html
```

**Comment by Hassan1ahmad** [comment] 2024-07-16 22:20
I am also facing same issue after update of WordPress 6.6 the edit pod page goes blank and setting just loading all the time. 
if rollback to  WordPress 6.5.5 everything works.

 In console getting this...
Uncaught TypeError: Cannot read properties of undefined (reading ‘mark’)
at pods-dfv.min.js?ver=a8de38fe9fd9869753b1:1:1089180
at pods-dfv.min.js?ver=a8de38fe9fd9869753b1:1:1089824
at pods-dfv.min.js?ver=a8de38fe9fd9869753b1:1:2001719
at pods-dfv.min.js?ver=a8de38fe9fd9869753b1:1:2001723

![scrnli_7_17_2024_3-19-38 AM](https://github.com/user-attachments/assets/5c71ebb1-ff26-49cd-b85b-ad300995c383)
![scrnli_7_17_2024_3-19-14 AM](https://github.com/user-attachments/assets/8588e069-e552-4185-8f26-b77495554f87)

**Comment by gusreiber-nsd** [comment] 2024-07-17 00:14
Same issue.
https://test.bhsptsa.com/podserrors/
![Screenshot 2024-07-16 165727](https://github.com/user-attachments/assets/cb9dba32-1a8a-42e0-841d-92cab1c5612b)

**Comment by RobinOehler** [comment] 2024-07-17 00:43
Same here! :(

![image](https://github.com/user-attachments/assets/75d6cb30-fef5-4c4f-8c6b-685346d8ad1e)

**Comment by mrmatteastwood** [comment] 2024-07-17 09:20
I'm affected by the exact same issue.

**Video:**

https://youtu.be/0a-1kGxDBLA

**Full site info from Tools > Site Health:**

```
`
### wp-core ###

version: 6.6
site_language: de_DE_formal
user_language: en_US
timezone: Europe/Berlin
permalink: /%category%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: undefined
environment_type: production
user_count: 3
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/vhosts/hosting189158.ae8d9.netcup.net/00prod/asbregio
wordpress_size: 1,32 GB (1416079635 bytes)
uploads_path: /var/www/vhosts/hosting189158.ae8d9.netcup.net/00prod/asbregio/wp-content/uploads
uploads_size: 123,90 MB (129921967 bytes)
themes_path: /var/www/vhosts/hosting189158.ae8d9.netcup.net/00prod/asbregio/wp-content/themes
themes_size: 35,26 MB (36971070 bytes)
plugins_path: /var/www/vhosts/hosting189158.ae8d9.netcup.net/00prod/asbregio/wp-content/plugins
plugins_size: 184,26 MB (193215118 bytes)
fonts_path: /var/www/vhosts/hosting189158.ae8d9.netcup.net/00prod/asbregio/wp-content/uploads/fonts
fonts_size: 2,54 MB (2663200 bytes)
database_size: 23,64 MB (24788992 bytes)
total_size: 1,68 GB (1803639982 bytes)

### wp-active-theme ###

name: Bricks Child Theme (bricks-child)
version: 1.1
author: Bricks
author_website: https://bricksbuilder.io/
parent_theme: Bricks (bricks)
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, title-tag, html5, menus, post-thumbnails, align-wide, widgets
theme_path: /var/www/vhosts/hosting189158.ae8d9.netcup.net/00prod/asbregio/wp-content/themes/bricks-child
auto_update: Disabled

### wp-parent-theme ###

name: Bricks (bricks)
version: 1.9.9
author: Bricks
author_website: https://bricksbuilder.io/
theme_path: /var/www/vhosts/hosting189158.ae8d9.netcup.net/00prod/asbregio/wp-content/themes/bricks
auto_update: Disabled

### wp-mu-plugins (1) ###

aios-firewall-loader.php: author: (undefined), version: (undefined)

### wp-plugins-active (14) ###

Advanced Themer for Bricks: version: 2.7.3, author: Maxime Beguin, Auto-updates disabled
All-in-One WP Migration: version: 7.84, author: ServMask, Auto-updates disabled
All-in-One WP Migration FTP Extension: version: 2.84, author: ServMask, Auto-updates disabled
All In One WP Security: version: 5.3.1, author: All In One WP Security & Firewall Team, Auto-updates disabled
Bricksforge: version: 2.2.5, author: Bricksforge, Auto-updates disabled
Complianz | GDPR/CCPA Cookie Consent: version: 7.1.0, author: Really Simple Plugins, Auto-updates disabled
HappyFiles Pro: version: 1.8.3, author: Codeer, Auto-updates disabled
MA Custom Fonts: version: 3.3.1, author: <a href="https://www.altmann.de/">Matthias Altmann</a>, Auto-updates disabled
Matomo Analytics - Ethical Stats. Powerful Insights.: version: 5.1.1, author: Matomo, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 3.2.4, author: Pods Framework Team, Auto-updates disabled
Rank Math SEO: version: 1.0.223, author: Rank Math, Auto-updates disabled
WP-Optimize - Clean, Compress, Cache: version: 3.4.2, author: David Anderson, Ruhani Rabin, Team Updraft, Auto-updates disabled
WPCodeBox 2: version: 1.1.1, author: WPCodeBox, Auto-updates disabled
WP Mail SMTP: version: 4.0.1, author: WP Mail SMTP, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1691
imagemagick_version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: 1
post_max_size: 256M
upload_max_filesize: 256M
max_effective_size: 256 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 393216
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 9.2233720368548E+18
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVIF, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HEIC, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.53.3

### wp-server ###

server_architecture: Linux 5.10.0-23-amd64 x86_64
httpd_software: Apache
php_version: 8.2.20 64bit
php_sapi: cgi-fcgi
max_input_variables: 4000
time_limit: 180
memory_limit: 1024M
max_input_time: 60
upload_max_filesize: 256M
php_post_max_size: 256M
curl_version: 7.74.0 OpenSSL/1.1.1w
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true
current: 2024-07-17T09:17:19+00:00
utc-time: Wednesday, 17-Jul-24 09:17:19 UTC
server-time: 2024-07-17T11:17:15+02:00

### wp-database ###

extension: mysqli
server_version: 8.0.35
client_version: mysqlnd 8.2.20
max_allowed_packet: 16777216
max_connections: 300

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/vhosts/hosting189158.ae8d9.netcup.net/00prod/asbregio/wp-content
WP_PLUGIN_DIR: /var/www/vhosts/hosting189158.ae8d9.netcup.net/00prod/asbregio/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
fonts: writable
mu-plugins: writable

### acf ###

version: 6.3.2.1
plugin_type: PRO
activated: false
activated_url: undefined
license_type: undefined
license_status: undefined
subscription_expires: undefined
ui_field_groups: 0
php_field_groups: 0
json_field_groups: 0
rest_field_groups: 0
post_types_enabled: true
ui_post_types: 10
json_post_types: 0
ui_taxonomies: 13
json_taxonomies: 0
ui_options_pages_enabled: true
ui_options_pages: 0
json_options_pages: 0
php_options_pages: 1
rest_api_format: light
registered_acf_blocks: 0
blocks_per_api_version: 
blocks_per_acf_block_version: 
blocks_using_post_meta: 0
preload_blocks: true
admin_ui_enabled: false
field_type-modal_enabled: true
field_settings_tabs_enabled: false
shortcode_enabled: true
registered_acf_forms: 0
json_save_paths: 1
json_load_paths: 1

### wp_mail_smtp ###

version: 4.0.1
license_key_type: lite
debug: No debug notices found.
lite_install_date: Feb 27, 2024 @ 1:34pm

### pods ###

pods-version: 3.2.4
pods-first-version: 2.9.13
pods-last-version: 3.2.2
pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
pods-session-save-path: /var/lib/php/sessions
pods-session-save-path-exists: No
pods-session-save-path-writable: No
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: Yes
pods-memory-current-usage: 20.577M / 40M
pods-memory-current-usage-real: 24.000M
pods-network-wide: No
pods-install-location: /wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Yes
pods-relationship-table-status: 14
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No
pods-can-use-sessions: No
pods-settings-types_only: Enable [types_only=0]
pods-settings-watch_changed_fields: Disable [watch_changed_fields=0]
pods-settings-metadata_integration: Enable [metadata_integration=1]
pods-settings-metadata_override_get: Disable [metadata_override_get=0]
pods-settings-register_meta_integration: Disable [register_meta_integration=0]
pods-settings-media_modal_fields: Disable [media_modal_fields=1]
pods-settings-session_auto_start: Disable [session_auto_start=0]
pods-settings-dynamic_features_allow: Enable [dynamic_features_allow=1]
pods-settings-dynamic_features_enabled: Display and Form [dynamic_features_enabled=display,form]
pods-settings-show_access_restricted_messages: Disable [show_access_restricted_messages=0]
pods-settings-show_access_admin_notices: Enable [show_access_admin_notices=1]
pods-settings-dynamic_features_allow_sql_clauses: Restricted [dynamic_features_allow_sql_clauses=simple]
pods-settings-display_callbacks: Restricted [display_callbacks=restricted]
pods-settings-display_callbacks_allowed: esc_attr,esc_html

`
```

**Comment by yarob-adtrak** [comment] 2024-07-17 12:38
Same issue! fields are not loading due to an error on Pods JS

![Screenshot 2024-07-17 at 13 37 41](https://github.com/user-attachments/assets/bfcd9e69-1ae4-40e4-a5d8-4e87a3373b89)

**Comment by gaswirth** [comment] 2024-07-17 14:17
+1

**Comment by BxDev** [comment] 2024-07-17 14:50
I guess, it's happens after updating WordPress to 6.6.

**Comment by gaswirth** [comment] 2024-07-17 14:58
> I guess, it's happens after updating WordPress to 6.6.

Confirmed! I rolled back to 6.5.5 and I was able to use all Pods screens as normal.

**Comment by alex-icstech** [comment] 2024-07-17 15:39
Confirmed that rolling back to 6.5.5 solved the problem. I notice that when I rolled back, a it removed a bunch of react.js files from 6.6:

File removed: wp-includes/js/dist/vendor/react-jsx-runtime.min.js
File removed: wp-includes/js/dist/vendor/react-jsx-runtime.js
File removed: wp-includes/js/dist/vendor/react-dom.min.js.LICENSE.txt
File removed: wp-includes/js/dist/vendor/react-jsx-runtime.min.js.LICENSE.txt
File removed: wp-includes/js/dist/vendor/react.min.js.LICENSE.txt

Probably not a coincidence that including introducing a javascript framework in WP 6.6 caused a javascript problem.

**Comment by sc0ttkclark** [comment] 2024-07-17 15:42
I was able to reproduce the issue here, still working out what the real cause is and how to resolve it with WordPress 6.6

In the meantime, I recommend everyone downgrade to WordPress 6.5.5: https://wordpress.org/download/releases/

**Comment by BxDev** [comment] 2024-07-18 07:30
Maybe temporary solution: in file wp-content/plugins/pods/ui/js/dfv/pods-dfv.min.js insert three checks:
`if (Lr()) {`
 before
` var n = Tr(Lr().mark((function n(r) {`

`if (Lr()) {`
 before
`var e = Tr(Lr().mark((function e(t) {`

`if (Lr()) {`
 before
`var e = Tr(Lr().mark((function e() {`

After that error in console gone and all fields and pages pods shows correct.

I don't know if broken some functionality, so use this on own risks.

**Comment by Ferannor** [comment] 2024-07-18 07:53
Thanks for your temporary fix. On my side, the only thing still broken is the photo fields. 
But still, it's a really nice temp fix for me!

**Comment by favy87** [comment] 2024-07-18 12:44
We have the same problem with version 6.6 of Wordpress.
We have changed what you say and I understand that it will be necessary to put some } after each change.

Could you upload the modified file somewhere, please?

**Comment by BxDev** [comment] 2024-07-18 13:06
> Could you upload the modified file somewhere, please?

Here is, just rename extension from json to js:
[pods-dfv.min.json](https://github.com/user-attachments/files/16283596/pods-dfv.min.json)
In this version, fields type file not work. Maybe other stuff to. So use this on own risks.

**Comment by favy87** [comment] 2024-07-19 07:04
Thank you very much for the contribution, but now it seems that the fields remain in "read-only" mode, I cannot modify the existing information.
Do we know when the next version of the plugin is released?

**Comment by sc0ttkclark** [comment] 2024-07-19 12:41
Fixed in Pods 3.2.5 -- thanks for your patience! This issue was complicated by having to update one NPM package causing many dependencies to also have to be updated and Node/NPM itself having to be updated. As a result, I spent a whole day off and on dealing with issues relating to that including NPM v22 getting hung up on macOS.

**Closed by sc0ttkclark** 2024-07-19 12:41 UTC
Labels: Type: Bug

**Comment by yarob-adtrak** [comment] 2024-07-19 12:46
I confirm the glory is back, thank you Scott 👍

**Comment by favy87** [comment] 2024-07-19 12:49
Thank you so much. We have tested it and it works correctly!

**Comment by gaswirth** [comment] 2024-07-19 13:36
Thank you!!

--
*Nick Gaswirth* | *Roundhouse Designs*
***@***.*** ***@***.***>* |
roundhouse-designs.com
