### ISSUE TITLE
Pods field text editor using TInyMCE height setting

### ISSUE THREAD

**Issue by siteprowizard** [pods-framework/pods#5671] opened 2020-04-09 20:18 UTC
## Issue Overview

When using Pods editor - the WYSIWYG Visual text editor that utilizes TinyMCE does not use the default for height. Instead it is more or less hard coded for iframe inline style height of 400px
This is too high and takes up a lot of page space especially if you have multiple fields using text editor.

## Expected Behavior

The height for the WYSIWYG Visual text editor iframe should be the default. 

Hardcoding of the WYSIWYG Visual text editor with the style tag for iframe height style setting should be removed.
 

## Current Behavior
The WYSIWYG Visual text editor for Pods backend iframe inline style height is set to height:400px
It is not possible to override with any CSS external code

Setting the inline height style for iframe for the WYSIWYG Visual text editor to default - as in removing it - will let it be the default height which is set by wordpress or plugins - such as TinyMCE Advanced - or can be set via CSS external styles
 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
Debug Information
WordPress Version: 5.4

PHP Version: 7.0.33

MySQL Version: 5.6.47

Server Software: Apache/2.4.43 (cPanel) OpenSSL/1.1.1f mod_bwlimited/1.4

Your User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

Session Save Path: /var/cpanel/php/sessions/ea-php70

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wpnut_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 17.519M

Current Memory Usage (real): 20.000M

Pods Network-Wide Activated: No

Pods Install Location: /home/nutridex/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Astra

Currently Active Plugins:

All In One SEO Pack: 3.4.2
Classic Editor: 1.5
Elementor: 2.9.7
Insert PHP Code Snippet: 1.3.1
Pods - Custom Content Types and Fields: 2.7.20
TinyMCE Advanced: 5.4.0
Wordfence Security: 7.4.6
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Comment by JoryHogeveen** [comment] 2020-04-10 15:05
Hi @siteprowizard 

Pods does not set a default height anywhere so the behavior you are experiencing is WordPress core.
However, I think setting a height might be a nice feature to add to the WYSIWYG field.

**Comment by JoryHogeveen** [comment] 2020-04-10 15:06
This would then actually be a duplicate of #3716

**Closed** 2020-06-25 16:05 UTC
Labels: Closed: Duplicate, Type: Enhancement
