### ISSUE TITLE
bug by returning post_name with specials characters like öäüß

### ISSUE THREAD

**Issue by robpie-de** [pods-framework/pods#5709] opened 2020-05-08 18:55 UTC
**Describe the bug**

i have a page e.g. "Köln", so `$post->post_name` return "koeln" but when i want to access it via the related field with `$mypod->field('abw_ort.post_name')` it returns "köln" instead of "koeln", the lower characters are correct, but i think it returns only the post_title in lowercase and not the "native" slug.

not tested, but i think the same bug for chars like "öäüß"

**To Reproduce**

**Expected behavior**

**Screenshots**

## Pods Version
Please provide the version of Pods you are running: 

## WordPress Environment

<details>

Copy and paste your Tools > Site Health > Info. Use the 'Copy Site Info to Clipboard' and paste the results over this line.

</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

**Additional context**

**Possible Workaround**
If you have discovered a workaround, please include it below.

**Comment by JoryHogeveen** [comment] 2020-05-14 16:12
Hello @robpie-de 
I cannot reproduce your issue. Please provide a full bug report for us to test with.
I'll update your original comment with the required info fields. You can then edit your post.

**Comment by JoryHogeveen** [comment] 2020-06-30 17:23
Closing due to no reply.

**Closed by JoryHogeveen** 2020-06-30 17:23 UTC
Labels: Status: Need Reproduction, Status: Need User Feedback
