### ISSUE TITLE
Currency Field Causing Warning

### ISSUE THREAD

**Issue by TeamSDA** [pods-framework/pods#4074] opened 2017-03-20 21:19 UTC
**Hello Pods Team…** I saw that the currency number field type issue was brought up before but it appears to still be present in Pods version 2.6.8.

When using the Currency type custom pods field there are warnings that appear when updating a post or page, see below.

Kind Regards,
Dave

WARNINGS
Warning: html_entity_decode() expects parameter 1 to be string, array given in /…/wp-content/plugins/pods/classes/fields/currency.php on line 475

Warning: html_entity_decode() expects parameter 1 to be string, array given in /…/wp-content/plugins/pods/classes/fields/currency.php on line 548

Warning: Cannot modify header information – headers already sent by (output started at /…/wp-content/plugins/pods/classes/fields/currency.php:475) in /…/wp-admin/post.php on line 197

Warning: Cannot modify header information – headers already sent by (output started at /…/wp-content/plugins/pods/classes/fields/currency.php:475) in /…/wp-includes/pluggable.php on line 1179

**Comment by pglewis** [comment] 2017-03-20 21:38
I think this may be a duplicate of #3975, fixed in #3954.  

The 2.x branch already has that fix if you have a test environment to check it on.

**Comment by jimtrue** [comment] 2017-03-20 21:40
I also responded to your Forum post: http://pods.io/forums/topic/currency-field-causing-warning/#post-196666

This is in the 2.x branch, or http://pods.io/latest/ and will be included in our next Production Release.

**Closed** 2017-03-20 21:40 UTC
Labels: Duplicate, Support

**Comment by TeamSDA** [comment] 2017-03-20 21:55
**Thank you...** Apologies for the duplicate issue post, new to submitting here on GitHub.

**Comment by jimtrue** [comment] 2017-03-20 21:56
No worries! We'd rather get a bug report and close it for being a duplicate than miss a bug! ;)
