### ISSUE TITLE
no JS Validation for relationship Fields (required)(can't resubmit after php error)

### ISSUE THREAD

**Issue by SimpleKjell** [pods-framework/pods#4739] opened 2018-01-31 14:12 UTC
By setting any field required, there is a JS validation before submitting the form, except for relationship fields.
There is "only" a php validation. This is fine, until i want to create new post of my post type.

While publishing a new post a post is created, but validated with an error, which is causing a simple output "back (to last page)", which is pointing to "post-new.php" and not to my freshly created post.

**Comment by quasel** [comment] 2018-08-31 14:31
Steps:
- create a new CPT entry 
- omit a relationship field set to required 
- hit save
- get redirected via php - xyz is empty, a new complete empt Draft! is created 
- klick back, see your data 
- can't publish again! (spinner and publish grey out!)

**Comment by quasel** [comment] 2018-08-31 14:36
Duplicate of #5031

**Closed by quasel** 2018-08-31 14:36 UTC
Labels: Closed: Duplicate, Status: Reproduced, Type: Bug
