### ISSUE TITLE
Reverse sorting using default Pods Admin when clicking on column heading stopped working in 2.5.2

### ISSUE THREAD

**Issue by clampdesign** [pods-framework/pods#2937] opened 2015-05-14 21:47 UTC
I just upgraded from Version 2.5.1.2  to 2.5.2 and noticed that I am no longer able to reverse the sort order by clicking on any column heading. I am using the "Normal" Admin UI Style.

**Comment by quasel** [comment] 2015-05-14 21:54
related to #2843

**Comment by Shelob9** [comment] 2015-05-14 22:38
I'm closing this as a dupe of #2843 The over escaping of URLs in 2.5.2 was too extreme in some cases and we need to round up everything that is broken.

**Closed by Shelob9** 2015-05-14 22:38 UTC
