### ISSUE TITLE
The Native WP Field Values Aren't Populated in $pieces[ ‘object_fields’ ]

### ISSUE THREAD

**Issue by TEKFused** [pods-framework/pods#5262] opened 2019-01-03 14:48 UTC
## Issue Overview
The Native WP field values aren't populated in $pieces[ ‘object_fields’ ] when using the pods_api_pre_save_pod_item or the pods_api_post_save_pod_item hooks.

## Expected Behavior
The WP native fields appear, but none of them have the value property set. For example, if I wanted to get the post title, I would have to use a native WP function such as get_the_title(). The value property of the WP fields in [ ‘object_fields’ ] should be set so we don't have to use other functions to get the values of the native WP fields.

 

## Current Behavior

output of $pieces[ ‘object_fields’ ] when using the pods_api_pre_save_pod_item:

![pods_api_pre_save_pod_item](https://user-images.githubusercontent.com/21973174/50642851-7a8b9a80-0f3a-11e9-9fbb-6c74b41b2f27.PNG)

output of $pieces[ ‘object_fields’ ] when using the pods_api_post_save_pod_item:

![pods_api_post_save_pod_item](https://user-images.githubusercontent.com/21973174/50642852-7a8b9a80-0f3a-11e9-8058-695392d29b5e.PNG)

## Steps to Reproduce (for bugs)

1. Create a CPT pod and add any field.
2. Add the pods_api_pre_save_pod_item() function to your functions.php file with a console.log command so you can view the output, and verify that the "value" property is not set in any of the WP native fields under $pieces[ ‘object_fields’ ] when saving an item in the CPT.
3. Replace the the pods_api_pre_save_pod_item() function in your functions.php file with pods_api_post_save_pod_item(), and verify that the "value" property is not set in any of the WP native fields under $pieces[ ‘object_fields’ ] when saving an item in the CPT.

## Possible Solution
Set the value property for the WP native fields in $pieces[ ‘object_fields’ ].

## WordPress Environment
<details>
WordPress Version: 5.0.2

PHP Version: 7.2.13

MySQL Version: 5.5.5

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

Session Save Path: /var/cpanel/php/sessions/ea-php72

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: %%%%%%_

WP Multisite Mode: No

WP Memory Limit: 128M

Current Memory Usage: 79.381M

Current Memory Usage (real): 38.000M

Pods Network-Wide Activated: No

Pods Install Location: /home/%%%%%/%%%%%%%/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Beaver Builder Child Theme

Currently Active Plugins:

Admin Columns Pro: 4.4.1
Admin Columns Pro - Pods: 1.3
Advanced Custom Fields: 5.7.9
Beaver Builder Plugin (Pro Version): 2.2.0.2
Beaver Themer: 1.2.1.1
Better Search Replace: 1.3.2
Classic Editor: 1.3
Colorlib Login Customizer: 1.2.6
Customizer Export/Import: 0.9
Email Templates: 1.2.2.3
Event Tickets: 4.9.3
FacetWP: 3.2.12
FacetWP - Beaver Builder: 1.2.1
FacetWP - Pods integration: 1.0
Google XML Sitemaps: 4.1.0
Gravity Forms: 2.4.4
Gravity Forms MailChimp Add-On: 4.5
Gravity Forms TEKFused Customizations: 1.0.0.1
Gravity Forms User Registration Add-On: 4.0
Jobs & Applications (TEKFused): 1.0.0.9
ManageWP - Worker: 4.6.3
NinjaFirewall (WP Edition): 3.8.1
Pods - Custom Content Types and Fields: 2.7.12
Pods Beaver Themer Add-On: 1.3.1
Pods Gravity Forms Add-On: 1.4.1
Schema Pro: 1.1.11
Sticky Menu (or Anything!) on Scroll: 2.1.1
Stream: 3.2.3
The Events Calendar: 4.7.3
Ultimate Addons for Beaver Builder: 1.13.2
User Role Editor Pro: 4.49.1
WordPress Importer: 0.6.4
WP Crontrol: 1.6.2
WP Rocket: 3.2.3.1
</details>

## Workaround or Alternate Solution Until Bug is Addressed
Use native WordPress functions to obtain the WP native field values.

**Comment by jimothyr** [comment] 2020-09-14 11:18
Is there any update on this issue? This is unexpected behaviour has caused my a few hours of grief.

**Comment by JoryHogeveen** [comment] 2020-09-14 12:30
Probably related: #5532

**Comment by JoryHogeveen** [comment] 2020-12-18 08:26
Hi @jimothyr 

The object fields value's are only set if these are changed through the Pods form.
So in an edit post screen this would never be the case since saving post related fields is handled by WP itself, not Pods.
Object fields would only be passed with a value when (for example) using the PodsForm class on the frontend with all fields enabled.

After explaining this, can this issue be closed or did I misread your report?

**Comment by JoryHogeveen** [comment] 2021-04-19 16:02
Closing issue due to no reply! Feel free to reopen if needed!

**Closed by JoryHogeveen** 2021-04-19 16:02 UTC
Labels: Status: Need Research
