### ISSUE TITLE
(Beta 2.7) Caldera Forms causes issue with template editor

### ISSUE THREAD

**Issue by neilgilmour** [pods-framework/pods#4287] opened 2017-06-05 19:29 UTC
Environment:
Chrome (Version 58.0.3029.110) for Mac,
WP 4.7.5
Pods 2.7.0-b-1
Caldera Forms 1.5.1-b-1
All other plugins deactivated

Issue:
When Caldera Forms is activated the template editor in Pods appears in a resizable text box rather than filling the container. Also the magic tags don't automatically fill in as I start typing. Screenshot attached.
![pods template editor resize fail](https://cloud.githubusercontent.com/assets/3442006/26799458/afee697e-4a2d-11e7-8e1a-3e300a5c8775.jpeg)

Link is to a pastebin of the Javascript error log from Chrome dev console. Sorry it's messy.
[https://pastebin.com/Edgpg924](url)

**Comment by jimtrue** [comment] 2017-06-05 19:32
@neilgilmour Your pastebin didn't come through it looks like.

**Comment by neilgilmour** [comment] 2017-06-05 19:41
Hmm, the github link doesn't work but copy/paste the url and it does work.

https://pastebin.com/Edgpg924

**Comment by neilgilmour** [comment] 2017-06-05 19:44
Now that's interesting - the first link I used the 'link' button on the github editor. The second link I just pasted plain text and it automatically made it into a link which does work. Is GitHub set to make a custom pods link or something? Anyway...

**Comment by neilgilmour** [comment] 2017-08-05 10:52
Relates to https://github.com/CalderaWP/Caldera-Forms/issues/1752

**Comment by jimtrue** [comment] 2018-02-09 17:31
Confirmed this was fixed by the update to Caldera Forms 1.5.8

**Closed by jimtrue** 2018-02-09 17:31 UTC
Labels: Bug, Compatibility, Needs Research, Needs Verification/Reproduction
