### ISSUE TITLE
User extended media upload field not saving correctly

### ISSUE THREAD

**Issue by cspicuzza** [pods-framework/pods#6977] opened 2022-12-16 20:47 UTC
### Description

After upgrading a few versions of Pods I noticed my extended User field for `avatar` is not displaying correctly. This affects both the back and front end.

### Version

2.9.10.2

### Testing Instructions

1. Create a user extend pod with a media upload field
2. Upload an image

### Screenshots / Screencast

![Screen Shot 2022-12-16 at 12 43 30 PM](https://user-images.githubusercontent.com/4442172/208186000-42da6577-47af-4d70-b1c8-ab14e793fb7a.png)

### Site Health Information

```text
`
### wp-core ###

version: 6.1.1
site_language: en_US
user_language: en_US
timezone: -05:00
permalink: /blog/%category%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 92768
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /srv/www/biolayne.com/releases/20221216181007/web/wp
wordpress_size: loading...
uploads_path: /srv/www/biolayne.com/releases/20221216181007/web/app/uploads
uploads_size: loading...
themes_path: /srv/www/biolayne.com/releases/20221216181007/web/app/themes
themes_size: loading...
plugins_path: /srv/www/biolayne.com/releases/20221216181007/web/app/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

object-cache.php: true

### wp-active-theme ###

name: Biolayne 3.0 - Sage 10 with Bud (biolayne3-sage10)
version: 3.0.0
author: Spicuzza
author_website: https://www.biolayne.com
parent_theme: none
theme_features: sage, widgets-block-editor, post-thumbnails, soil, menus, title-tag, align-wide, responsive-embeds, html5, customize-selective-refresh-widgets, widgets
theme_path: /srv/www/biolayne.com/releases/20221216181007/web/app/themes/biolayne3-sage10

### wp-mu-plugins (2) ###

Bedrock Autoloader: version: 1.0.3, author: Roots
Register Theme Directory: version: 1.0.0, author: Roots

### wp-plugins-active (38) ###

Biolayne API: version: 1.1.0, author: Biolayne Team
Biolayne Email Templates: version: 2.0.1, author: Biolayne Technologies LLC
Biolayne Gutenberg Blocks: version: 1.0.0, author: Kelly Mears
Debug Bar: version: 1.1.4, author: wordpressdotorg
Disable Comments: version: 2.4.2, author: WPDeveloper
Download Monitor: version: 4.7.70, author: WPChill
Download Monitor - Gravity Forms Extension: version: 4.0.4, author: WPChill (latest version: 4.0.5)
Edit Author Slug: version: 1.8.4, author: Brandon Allen
Getwid: version: 1.8.2, author: MotoPress
Gravity Forms: version: 2.6.8.1, author: Gravity Forms
Gravity Forms Help Scout Add-On: version: 2.1, author: Gravity Forms
Gravity Forms Mailchimp Add-On: version: 5.1, author: Gravity Forms
Mailgun: version: 1.8.9, author: Mailgun
Pods - Custom Content Types and Fields: version: 2.9.10.2, author: Pods Framework Team
Pods Pro - Advanced Relationship Storage Add-On: version: 1.1.3, author: SKC Development, LLC
Post Thumbnail Editor: version: 2.4.8, author: sewpafly
Radio Buttons for Taxonomies: version: 2.4.4, author: helgatheviking
RCP - Download Monitor Bridge: version: 1.0.5, author: iThemes, LLC
Reorder Posts: version: 2.5.3, author: Ryan Hellyer, Ronald Huereca, Scott Basgaard
Restrict Content Pro: version: 3.5.24.1, author: Restrict Content Pro
Restrict Content Pro - Custom Renew: version: 1.0.5, author: iThemes
Restrict Content Pro - Help Scout: version: 1.0.4, author: Sandhills Development, LLC
Restrict Content Pro - Limited Quantity Available: version: 1.0.2, author: Sandhills Development, LLC
Restrict Content Pro - MailChimp Pro: version: 1.5.3, author: iThemes
Restrict Content Pro - Per-Level Emails: version: 1.0.1, author: Sandhills Development, LLC
Schema Pro: version: 2.7.4, author: Brainstorm Force
SearchWP: version: 4.2.8, author: SearchWP
SearchWP Metrics: version: 1.4.2, author: SearchWP
SearchWP Related: version: 1.4.7, author: SearchWP
SeedProd Pro: version: 6.14.1, author: SeedProd
SVG Support: version: 2.5.5, author: Benbodhi
TinyPNG - JPEG, PNG & WebP image compression: version: 3.4.1, author: TinyPNG
Username Changer: version: 3.2.2, author: Widgit Team
User Switching: version: 1.7.0, author: John Blackbourn & contributors
Wordfence Security: version: 7.8.2, author: Wordfence
WPFront Notification Bar: version: 3.2.0, author: Syam Mohan
Yoast SEO: version: 19.12, author: Team Yoast
Yoast SEO Premium: version: 18.3, author: Team Yoast (latest version: 19.6)

### wp-plugins-inactive (6) ###

Advanced Database Cleaner: version: 3.1.1, author: Younes JFR.
Disable Admin-AJAX: version: 1.0.0, author: LittleBizzy
Disable Emails: version: 1.8.1, author: WebAware
Pods Alternative Cache: version: 2.1.5, author: Pods Framework Team
REST API Tester: version: 0.1.3, author: Modern Tribe, Inc.
WP All Import Pro: version: 4.7.2, author: Soflyy

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.6.0
file_uploads: File uploads is turned off
post_max_size: 25M
upload_max_filesize: 25M
max_effective_size: 25 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: not available
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.4.0-100-generic x86_64
httpd_software: nginx/1.21.6
php_version: 8.0.15 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 120
memory_limit: 512M
max_input_time: 300
upload_max_filesize: 25M
php_post_max_size: 25M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 8.0.28
client_version: mysqlnd 8.0.15
max_allowed_packet: 67108864
max_connections: 2801

### wp-constants ###

WP_HOME: https://biolayne.com
WP_SITEURL: https://biolayne.com/wp
WP_CONTENT_DIR: /srv/www/biolayne.com/releases/20221216181007/web/app
WP_PLUGIN_DIR: /srv/www/biolayne.com/releases/20221216181007/web/app/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### pods ###

pods-server-software: nginx/1.21.6
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
pods-session-save-path: /tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: Yes
pods-object-cache-redis: No
pods-memory-current-usage: 29.716M
pods-memory-current-usage-real: 32.000M
pods-network-wide: No
pods-install-location: /srv/www/biolayne.com/releases/20221216181007/web/app/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-relationship-table-enabled: Yes
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No
pods-sessions: Disable sessions
pods-can-use-sessions: Yes
pods-relationship-table-status: 110,411,528

`
```

### Pods Package

```json
{
    "@meta": {
        "version": "2.9.10.2",
        "build": 1671223573
    },
    "pods": [
        {
            "name": "user",
            "id": 37,
            "label": "User",
            "description": "",
            "type": "user",
            "storage": "meta",
            "object": "user",
            "_migrated_28": "0",
            "groups": [
                {
                    "name": "more_fields",
                    "id": 153708,
                    "label": "More Fields",
                    "description": "",
                    "weight": 0,
                    "fields": [
                        {
                            "name": "avatar",
                            "id": 39,
                            "label": "Avatar",
                            "description": "Your profile image",
                            "weight": 0,
                            "type": "avatar",
                            "required": "0",
                            "avatar_uploader": "attachment",
                            "avatar_attachment_tab": "upload",
                            "avatar_restrict_filesize": "10MB",
                            "avatar_add_button": "Add File",
                            "avatar_modal_title": "Attach a file",
                            "avatar_modal_add_button": "Add File",
                            "admin_only": "0",
                            "restrict_role": "1",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator",
                                "editor",
                                "author"
                            ],
                            "sister_id": "-- Select One --",
                            "avatar_format_type": "single",
                            "avatar_upload_dir": "wp",
                            "avatar_edit_title": "1",
                            "avatar_show_edit_link": "0",
                            "avatar_linked": "0",
                            "avatar_limit": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by sc0ttkclark** [comment] 2023-02-18 06:09
Duplicate of #7001 (that's newer but it was worked on there)

**Closed by sc0ttkclark** 2023-02-18 06:09 UTC
Labels: Type: Bug
