### ISSUE TITLE
2.8: Migration to Group fields didn't go well in all installations

### ISSUE THREAD

**Issue by JoryHogeveen** [pods-framework/pods#6292] opened 2021-11-08 08:17 UTC
## Description

This issue is a collection of reported issues on GitHub, WP forums and Slack.

A lot of users are having issues with the image/file fields. After the update it won't save anymore. From what I understand from various reports is that re-saving the Pod fixes any issues but this means we're not backwards compatible.

## Related Issues:

**Main issue:**
https://wordpress.org/support/topic/version-2-8-3-no-longer-saving-images-in-pods/
https://wordpress.org/support/topic/php-warning-illegal-string-offiset-id/

https://github.com/pods-framework/pods/issues/6263
https://github.com/pods-framework/pods/issues/6280
https://github.com/pods-framework/pods/issues/6281
https://github.com/pods-framework/pods/issues/6282
https://github.com/pods-framework/pods/issues/6294

https://podswp.slack.com/archives/C02SVLHQF/p1635938622303200

**Maybe related:**
https://wordpress.org/support/topic/save-attachment-to-pods-required-field-does-not-work-since-2-8/
https://wordpress.org/support/topic/error-editing-existing-podsother-language/
https://wordpress.org/support/topic/document-upload-not-working-since-last-update/
https://wordpress.org/support/topic/chosen-relationships-arent-saving/

https://github.com/pods-framework/pods/issues/6280
https://github.com/pods-framework/pods/issues/6279

## Reproduce issue:

- I use the main  branch and 1.8.4
- Save an image field with an image on the main branch.
- Switch to 1.8.4 : Image gone
- Do the same on the 1.8.4  branch and you'll see it's gone on the main  branch.

## Possible workaround

Some users report that re-saving the Pod fixes some issues though I cannot fully confirm this.

## Pods version

2.8+

**Comment by pdclark** [comment] 2021-11-08 20:34
Confirmed in testing.

- Creating a file field from scratch in `2.8.4` works fine.
- If you create a `file` field in `2.7.31`, then upgrade to `2.8.4`, the value of the file field gets "stuck". (I can't remove a file uploaded when it was `2.7.31`. No errors.)
- Re-saving the Pod in `2.8.4` resolves the issue.

@sc0ttkclark

**Comment by sc0ttkclark** [comment] 2021-11-08 21:25
Any notable differences in the pod config from a package export?

**Comment by sc0ttkclark** [comment] 2021-11-09 02:50
I didn't see anything of importance in the package itself when comparing 2.7.31 to 2.8.4.

I'll keep digging into this to see if there's anything I can find here.

**Comment by JoryHogeveen** [comment] 2021-11-09 08:19
@sc0ttkclark Note this topic: https://wordpress.org/support/topic/chosen-relationships-arent-saving/

The original post is similar to this issue but he could resolve it with alternative cache? Maybe this is a cache issue of some sort?

**Comment by pdclark** [comment] 2021-11-09 19:42
These are the package exports.

The exports look different between versions, and again is different in `2.8.3` before saving the pod and after saving the pod. Saving the pod resolves the issue.

`2.7.31`
```json
{"meta":{"version":"2.7.31","build":1636486513},"pods":{"13":{"id":13,"name":"post","label":"Post","description":"","type":"post_type","storage":"meta","object":"post","alias":"","fields":{"some_file":{"id":14,"name":"some_file","label":"Some File","description":"","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_upload_dir":"wp","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"1","file_upload_dir_custom":"","file_allowed_extensions":""}},"show_in_menu":1,"pfat_enable":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_excerpt","pfat_run_outside_loop":"0","rest_enable":"0","read_all":"0","write_all":"0"}}}
```

`2.8.3 — Before Save`
```json
{
    "meta": {
        "version": "2.8.3",
        "build": 1636486626
    },
    "pods": [
        {
            "name": "post",
            "id": 13,
            "label": "Post",
            "description": "",
            "type": "post_type",
            "storage": "meta",
            "object": "post",
            "pfat_enable": "0",
            "pfat_append_single": "append",
            "pfat_filter_single": "the_content",
            "pfat_append_archive": "append",
            "pfat_filter_archive": "the_excerpt",
            "pfat_run_outside_loop": "0",
            "rest_enable": "0",
            "read_all": "0",
            "write_all": "0",
            "groups": [
                {
                    "name": "more_fields",
                    "label": "More Fields",
                    "fields": [
                        {
                            "name": "some_file",
                            "id": 14,
                            "label": "Some File",
                            "description": "",
                            "weight": 0,
                            "type": "file",
                            "pick_object": "custom-simple",
                            "required": "0",
                            "text_allow_shortcode": "0",
                            "text_allow_html": "0",
                            "phone_enable_phone_extension": "1",
                            "paragraph_allow_html": "1",
                            "paragraph_oembed": "0",
                            "paragraph_wptexturize": "1",
                            "paragraph_convert_chars": "1",
                            "paragraph_wpautop": "1",
                            "paragraph_allow_shortcode": "0",
                            "wysiwyg_media_buttons": "1",
                            "wysiwyg_oembed": "0",
                            "wysiwyg_wptexturize": "1",
                            "wysiwyg_convert_chars": "1",
                            "wysiwyg_wpautop": "1",
                            "wysiwyg_allow_shortcode": "0",
                            "code_allow_shortcode": "0",
                            "file_format_type": "single",
                            "file_uploader": "attachment",
                            "file_attachment_tab": "upload",
                            "file_upload_dir": "wp",
                            "file_edit_title": "1",
                            "file_show_edit_link": "0",
                            "file_linked": "0",
                            "file_limit": "0",
                            "file_restrict_filesize": "10MB",
                            "file_type": "images",
                            "file_field_template": "rows",
                            "file_add_button": "Add File",
                            "file_modal_title": "Attach a file",
                            "file_modal_add_button": "Add File",
                            "file_wp_gallery_output": "0",
                            "file_wp_gallery_link": "post",
                            "file_wp_gallery_columns": "1",
                            "file_wp_gallery_random_sort": "0",
                            "file_wp_gallery_size": "thumbnail",
                            "oembed_enabled_providers_amazoncn": "0",
                            "oembed_enabled_providers_amazoncouk": "0",
                            "oembed_enabled_providers_amazoncom": "0",
                            "oembed_enabled_providers_amazoncomau": "0",
                            "oembed_enabled_providers_amazonin": "0",
                            "oembed_enabled_providers_animotocom": "0",
                            "oembed_enabled_providers_cloudupcom": "0",
                            "oembed_enabled_providers_crowdsignalcom": "0",
                            "oembed_enabled_providers_dailymotioncom": "0",
                            "oembed_enabled_providers_flickrcom": "0",
                            "oembed_enabled_providers_imgurcom": "0",
                            "oembed_enabled_providers_issuucom": "0",
                            "oembed_enabled_providers_kickstartercom": "0",
                            "oembed_enabled_providers_meetupcom": "0",
                            "oembed_enabled_providers_mixcloudcom": "0",
                            "oembed_enabled_providers_redditcom": "0",
                            "oembed_enabled_providers_reverbnationcom": "0",
                            "oembed_enabled_providers_screencastcom": "0",
                            "oembed_enabled_providers_scribdcom": "0",
                            "oembed_enabled_providers_slidesharenet": "0",
                            "oembed_enabled_providers_smugmugcom": "0",
                            "oembed_enabled_providers_someecardscom": "0",
                            "oembed_enabled_providers_soundcloudcom": "0",
                            "oembed_enabled_providers_speakerdeckcom": "0",
                            "oembed_enabled_providers_spotifycom": "0",
                            "oembed_enabled_providers_tedcom": "0",
                            "oembed_enabled_providers_tiktokcom": "0",
                            "oembed_enabled_providers_tumblrcom": "0",
                            "oembed_enabled_providers_twittercom": "0",
                            "oembed_enabled_providers_vimeocom": "0",
                            "oembed_enabled_providers_wordpresscom": "0",
                            "oembed_enabled_providers_wordpresstv": "0",
                            "oembed_enabled_providers_youtubecom": "0",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1"
                        }
                    ]
                }
            ]
        }
    ]
}
```

`2.8.3 — After Save`
```json
{
    "meta": {
        "version": "2.8.3",
        "build": 1636486797
    },
    "pods": [
        {
            "name": "post",
            "id": 13,
            "label": "Post",
            "description": "",
            "type": "post_type",
            "storage": "meta",
            "object": "post",
            "pfat_enable": "0",
            "pfat_append_single": "append",
            "pfat_filter_single": "the_content",
            "pfat_append_archive": "append",
            "pfat_filter_archive": "the_excerpt",
            "pfat_run_outside_loop": "0",
            "rest_enable": "0",
            "read_all": "0",
            "write_all": "0",
            "_migrated_28": "1",
            "groups": [
                {
                    "name": "more_fields",
                    "id": 18,
                    "label": "More Fields",
                    "description": "",
                    "weight": 0,
                    "fields": [
                        {
                            "name": "some_file",
                            "id": 14,
                            "label": "Some File",
                            "description": "",
                            "weight": 0,
                            "type": "file",
                            "required": "0",
                            "file_format_type": "single",
                            "file_uploader": "attachment",
                            "file_attachment_tab": "upload",
                            "file_upload_dir": "wp",
                            "file_edit_title": "1",
                            "file_show_edit_link": "0",
                            "file_linked": "0",
                            "file_limit": "0",
                            "file_restrict_filesize": "10MB",
                            "file_type": "images",
                            "file_field_template": "rows",
                            "file_add_button": "Add File",
                            "file_modal_title": "Attach a file",
                            "file_modal_add_button": "Add File",
                            "file_wp_gallery_output": "0",
                            "file_wp_gallery_link": "post",
                            "file_wp_gallery_columns": "1",
                            "file_wp_gallery_random_sort": "0",
                            "file_wp_gallery_size": "thumbnail",
                            "pick_post_status": [
                                "publish"
                            ],
                            "admin_only": "0",
                            "restrict_role": "0",
                            "restrict_capability": "0",
                            "hidden": "0",
                            "read_only": "0",
                            "roles_allowed": [
                                "administrator"
                            ],
                            "rest_read": "0",
                            "rest_write": "0",
                            "rest_pick_response": "array",
                            "rest_pick_depth": "1"
                        }
                    ]
                }
            ]
        }
    ]
}
```

@sc0ttkclark

**Comment by JoryHogeveen** [comment] 2021-11-10 09:12
@sc0ttkclark @pdclark 

I noticed in your package exports that after saving there are some changes:

- Unrelated items are removed
- The post has a new option `_migrated_28`
- The group has an `id` option that didn't exist before (besides `description` and `weight`.

I think the latter (`id` option) is the issue here.

**Comment by sc0ttkclark** [comment] 2021-11-10 14:17
The export gives it a temporary group, it's not a real group until they open the pod edit screen. The group isn't used anywhere during saving pod item data at the moment.

It must be something else we are missing or it's not as simple of a solution like we thought. Do we know it doesn't recur even after saving the pod?

**Comment by sc0ttkclark** [comment] 2021-11-12 20:47
Fixed via https://github.com/pods-framework/pods/commit/b9fdc5484ddcb71080141f7458ede0b1154fca1f

The problem was that some Relationship field logic (object/val) and associated checks were running for File fields when they shouldn't have. Normally not a problem but some of the 2.7.x configurations were saving with pick_object and other non-file field type options that were tricking the logic. Now it checks by field type itself.

**Closed by sc0ttkclark** 2021-11-12 20:47 UTC
Labels: Type: Bug, Priority: Blocker, Keywords: Regression
