### ISSUE TITLE
Can't add more than 32 fields to a pod

### ISSUE THREAD

**Issue by Cyberwolfer** [pods-framework/pods#3403] opened 2016-02-18 14:28 UTC
When trying to save a pod with more than 32 fields I get the pop-up dialog: "Error: Unable to process request, please try again." and it wont let me save the added fields.
- Tried solving problem by changing the storage type of the Pod from Meta to Table, however this did not solve the problem. Instead in a Table based pod I could only save 31 fields before getting the Error message.
- Tried increasing the WP MEMORY ALLOCATION from 40M, first to 96M and then 256M but did not make any difference, still getting Error message.

Screenshot:
[http://janosterlund.com/tmp/pods_saving_error.jpg](http://janosterlund.com/tmp/pods_saving_error.jpg)

**Comment by jimtrue** [comment] 2016-02-18 14:32
We might need a migration snapshot to help troubleshoot this one. If you can, go into Pods Admin, Components and Activate Migrate: Packages. Then from Pods Admin, Migrate Packages, select Export and take the resulting json file (it'll be cut and paste) and copy it into a text document and upload here as your migrate-3403.json. Thanks!

**Comment by Cyberwolfer** [comment] 2016-02-18 14:53
Here you go:
[http://janosterlund.com/tmp/migrate-3403.json](http://janosterlund.com/tmp/migrate-3403.json)

**Comment by jimtrue** [comment] 2016-02-18 15:15
Thanks @Cyberwolfer !!

**Comment by Cyberwolfer** [comment] 2016-02-18 15:17
@jimtrue , thanks to the migration of the json I came up with a temporary workaround this problem... I export all the fields I have -> cut and paste them to an editor, and manually add new lines with the fields I need added. -> Then I cut and paste this and import the updated package... and it just adds everything added to the pod I have. I can save fine the custom Property post type. For anyone looking for a way to get around that ;)

**Comment by sc0ttkclark** [comment] 2016-02-18 15:39
Could be max post size: http://stackoverflow.com/a/6135485/423330

**Comment by sc0ttkclark** [comment] 2016-02-18 15:40
Also go into your Pods Admin > Settings and let us know what you see for Memory limit, I think we have it listed there. It's possible PHP won't let you override the memory limit, some shared hosts have that restricted so it won't actually set properly.

**Comment by sc0ttkclark** [comment] 2016-02-18 15:41
Could potentially be max execution time: http://stackoverflow.com/a/16171228/423330

**Comment by Cyberwolfer** [comment] 2016-02-18 16:12
Pods Admin > Settings 
[http://janosterlund.com/tmp/pods_settings.jpg](http://janosterlund.com/tmp/pods_settings.jpg)

**Comment by sc0ttkclark** [comment] 2016-02-18 16:50
Removed your screenshot since it had some info in there you probably don't want completely public :)

**Comment by Cyberwolfer** [comment] 2016-02-18 17:15
Thanks

**Comment by Megamack** [comment] 2017-02-18 19:53
Is this resolved I have this annoying bug too?

**Comment by pglewis** [comment] 2017-02-18 20:21
Historically this problem has been due to various environmental issues that we haven't been able to reproduce locally, #2104, #2019

It hasn't always been the same cause.  I would start by setting up a local development installation and seeing if the issue reproduces there as well.  If so, we need the details on the setup in order to reproduce it.  If it doesn't reproduce locally for you then you should look closely at the differences between the two installations.

**Comment by jamesgol** [comment] 2017-02-18 20:24
I also was not able to reproduce these issues on any of my test setups.

**Comment by Megamack** [comment] 2017-02-18 20:58
phpinfo shows that I dont have any session.save_path what should this be set to and how?

**Comment by jimtrue** [comment] 2017-02-19 18:00
Looks like you were working this on our forums, too, @Megamack 
http://pods.io/forums/topic/max-32-fields-in-pod/

According to the notes over there, you found the conflict in the if-menu plugin. BTW, that's our first troubleshooting step; deactivate everything but Pods and switch to a default theme. If you're working in that situation, reactivate one plugin at a time until you find the issue.

**Comment by quasel** [comment] 2018-09-01 22:15
Hi, we didn't hear back from you - so I'm closing the issue!

**Closed by quasel** 2018-09-01 22:15 UTC
Labels: Type: Support
