### ISSUE TITLE
IF doesn't work with Date Field in PODS Templates

### ISSUE THREAD

**Issue by jennafarr** [pods-framework/pods#4145] opened 2017-05-02 15:46 UTC
I had this issue and found Issue #3552 to be closed, however I don't think testing was thorough enough. It works if you never put a date in that field. As soon as you put a date in the field and then remove it and save the post again, it returns blank but keeps the heading (Last Contact). It thinks there is data there when in fact there is not. This is happening on a site where we imported the date fields and some are in fact empty.

I used the template from issue #3552:
[if test_date_field]
	<tr class="last-communication">
		<td>Last Contact</td><td>{@test_date_field}</td>
	</tr>
	[/if]

The test_date_field field was setup with the default configuration.

**Comment by JoryHogeveen** [comment] 2017-05-11 11:11
Needs to be fixed in https://github.com/pods-framework/pods/pull/4106

**Comment by JoryHogeveen** [comment] 2017-05-15 23:59
@jimtrue 
Can you confirm that the latest commits to #4106 fixed this issue?

**Comment by sc0ttkclark** [comment] 2017-05-17 05:24
Closing as a duplicate of #3829

**Closed by sc0ttkclark** 2017-05-17 05:24 UTC
Labels: Bug, in progress

**Comment by jimtrue** [comment] 2017-05-17 12:11
@JoryHogeveen Yes, i can confirm this fixes that issue. Brand new record, all blank, doesn't show. Add fields, shows, Deleted entries (returning to blank), doesn't show.
