### ISSUE TITLE
localization/translation of month names in dates does not work 

### ISSUE THREAD

**Issue by guidobras** [pods-framework/pods#4925] opened 2018-05-10 21:26 UTC
## Issue Overview
Trying to display a “day monthname year” date using italian monthname (which would be the default for my wordpress installation) but PODS keeps outputting monthname in english, even if I choose in field options a custom php-style date format “j F Y”.

## Expected Behavior
what should happen: month name is displayed in local wordpress language

## Current Behavior
current behavior: month name is displayed in english

## Steps to Reproduce (for bugs)
On a non english wordpress system create a Pods with a date field and set it to "custom format" with “j F Y”. 

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
WordPress Version: 4.9.5

PHP Version: 7.0.27-0+deb9u1

MySQL Version: 5.5.5

Server Software: Apache/2.4.25

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Session Save Path: /home/***/tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home/***/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: ***

Currently Active Plugins:

Beaver Builder Plugin (Pro Version): 2.1.1.2
Beaver Themer: 1.1.1
Duplicate Post: 3.2.2
Pods - Custom Content Types and Fields: 2.7.3
Pods Beaver Themer Add-On: 1.2.1
Post Types Order: 1.9.3.6
Radio Buttons for Taxonomies: 1.8.1
UpdraftPlus - Backup/Restore: 1.14.7
```
</details>

**Comment by quasel** [comment] 2018-08-31 11:26
sorry for the late reply this is being worked on! 

Duplicate of #5038

**Closed by quasel** 2018-08-31 11:26 UTC
Labels: Closed: Duplicate
