### ISSUE TITLE
Screen Freezes when Adding New Fields to a Pod

### ISSUE THREAD

**Issue by amlange** [pods-framework/pods#5751] opened 2020-06-18 22:36 UTC
**Describe the bug**

**To Reproduce**
1. Go to the Pods Admin section on the WP dashboard.
2. Click on Add New or Edit
3. After entering information on Basic tab, go to the Additional Field Options tab.
4. Click in any of the fields, ie. maximum length or selection type.
5. The screen freezes and the mouse doesn't work.

**Expected behavior**
I cannot create the fields with the proper characteristics. The only way to get off of the Additional Tabs screen is to use the back browser button.

**Screenshots**
Not applicable. There is nothing to see, just a frozen screen.

## Pods Version
Please provide the version of Pods you are running: Version 2.7.20.1 (I just installed the plugin this afternoon and I am using this for the first time. I watched a few videos to learn the basics.)

## WordPress Environment

<details>

`
### wp-core ###

version: 5.4.2
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /Users/AnnetteMLange/Local Sites/lange-art-design/app/public
wordpress_size: 39.45 MB (41366248 bytes)
uploads_path: /Users/AnnetteMLange/Local Sites/lange-art-design/app/public/wp-content/uploads
uploads_size: 12.25 MB (12842468 bytes)
themes_path: /Users/AnnetteMLange/Local Sites/lange-art-design/app/public/wp-content/themes
themes_size: 443.19 KB (453830 bytes)
plugins_path: /Users/AnnetteMLange/Local Sites/lange-art-design/app/public/wp-content/plugins
plugins_size: 29.62 MB (31060593 bytes)
database_size: 5.56 MB (5832704 bytes)
total_size: 87.31 MB (91555843 bytes)

### wp-active-theme ###

name: Hello Elementor (hello-elementor)
version: 2.3.0
author: Elementor Team
author_website: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
parent_theme: none
theme_features: menus, post-thumbnails, automatic-feed-links, title-tag, html5, custom-logo, editor-style, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider
theme_path: /Users/AnnetteMLange/Local Sites/lange-art-design/app/public/wp-content/themes/hello-elementor

### wp-plugins-active (3) ###

Elementor: version: 2.9.12, author: Elementor.com
Elementor Pro: version: 2.10.2, author: Elementor.com
Pods - Custom Content Types and Fields: version: 2.7.20.1, author: Pods Framework Team

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Darwin 19.5.0 x86_64
httpd_software: nginx/1.16.0
php_version: 7.3.5 64bit
php_sapi: fpm-fcgi
max_input_variables: 4000
time_limit: 1200
memory_limit: 256M
max_input_time: 600
upload_max_size: 300M
php_post_max_size: 1000M
curl_version: 7.54.0 LibreSSL/2.6.5
suhosin: false
imagick_availability: false
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 8.0.16
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /Users/AnnetteMLange/Local Sites/lange-art-design/app/public/wp-content
WP_PLUGIN_DIR: /Users/AnnetteMLange/Local Sites/lange-art-design/app/public/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: nginx/1.16.0
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15
pods-session-save-path: undefined
pods-session-save-path-exists: No
pods-session-save-path-writable: No
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 6.678M
pods-memory-current-usage-real: 2.000M
pods-network-wide: No
pods-install-location: /Users/AnnetteMLange/Local Sites/lange-art-design/app/public/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
{"meta":{"version":"2.7.20.1","build":1592519716},"pods":{"167":{"id":167,"name":"project","label":"Projects","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":[],"show_in_menu":1,"label_singular":"Project","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1"}}}

**Additional context**
I saw these warnings on the Site Health screen.


( ! ) Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server&#8217;s configuration. If you continue to have problems, please try the <a href="https://wordpress.org/support/forums/">support forums</a>. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /Users/AnnetteMLange/Local Sites/lange-art-design/app/public/wp-includes/update.php on line 162
--


1 | 0.0001 | 410440 | {main}( ) | .../site-health.php:0
2 | 0.0061 | 412584 | require_once( '/Users/AnnetteMLange/Local Sites/lange-art-design/app/public/wp-admin/site-health-info.php' ) | .../site-health.php:10
3 | 0.1079 | 6411304 | WP_Debug_Data::check_for_updates( ) | .../site-health-info.php:77
4 | 0.1079 | 6411304 | wp_version_check( ) | .../class-wp-debug-data.php:17
5 | 3.1136 | 6520200 | trigger_error ( ) | .../update.php:162


**Possible Workaround**
If you have discovered a workaround, please include it below.

I am very disappointed with this plugin. Thank you for any assistance you can give me.

**Comment by JoryHogeveen** [comment] 2020-06-22 10:59
Hello @amlange 

I cannot reproduce your issue.
Could you please share any debug info you have? Like server error logs.

Thanks! Jory

**Comment by amlange** [comment] 2020-06-22 15:00
Hello Jory,

 

I sent you as much information as I could find. Where would I look for server error logs? 

 

I tried using Pods on another website after I posted my issue and still had the same problem.

 

Annette Lange

**Comment by JoryHogeveen** [comment] 2020-06-23 10:12
Hello @amlange 

Please see: https://wordpress.org/support/article/debugging-in-wordpress/
And for browser console errors: https://documentation.concrete5.org/tutorials/how-open-browser-console-view-errors

Cheers, Jory

**Comment by JoryHogeveen** [comment] 2020-06-30 17:14
Closing issue due to no reply.

**Closed by JoryHogeveen** 2020-06-30 17:14 UTC
Labels: Type: Bug

**Comment by amlange** [comment] 2020-06-30 18:11
Hi Jory,

 

I had the same problem using the CPU UI plugin as I did with PODS. I decided to try a different browser. I always use Safari. When I tried to use the PODS plugin on the Google Chrome browser, everything worked fine. I don’t know why it did not work on Safari, but at least I have a work-around. I am sharing this in case someone else has the same problem.

 

Thank you for your help.

 

Annette

**Comment by sc0ttkclark** [comment] 2020-07-01 00:44
@amlange Can you try it with Safari again and check for the browser console errors as per https://documentation.concrete5.org/tutorials/how-open-browser-console-view-errors so that we can find out what the cause might be?

**Comment by amlange** [comment] 2020-07-01 17:32
Hello Scott,

 

I really don’t know what all of this means, but hopefully it can help you.

 

Annette Lange

**Comment by sc0ttkclark** [comment] 2020-07-02 16:22
I'm not sure if you replied with an attachment but it did not come through. If you did, can you try posting the attachment directly through GitHub instead of e-mail reply? https://github.com/pods-framework/pods/issues/5751

**Comment by amlange** [comment] 2020-07-03 02:06
Here is the attachment as requested.

<img width="928" alt="Screen Shot 2020-07-01 at 1 28 42 PM" src="https://user-images.githubusercontent.com/11442994/86424270-17560200-bcb0-11ea-94d9-7384bd977576.png">

**Comment by sc0ttkclark** [comment] 2020-07-03 02:57
That's definitely not from Pods, I wonder if you can provide a list of active plugins / theme you have as well as if your Safari has any extensions enabled for it (Safari > Preferences > Extensions and list which ones are active). Is that doable for you?

**Comment by amlange** [comment] 2020-07-03 12:23
Here is the list you requested.

 

Active Plugins:

Classic Editor (version 1.5)

Elementor (version 2.9.13)

Elementor Pro (version 2.10.2)

Pods version (2.7.20.1)

Updraft Plus (1.16.25)

Yoast SEO (14.4.1)

 

Safari Extensions:

Grammarly (version 9.17)

Honey version (11.11.2)

Norton Password Manager (version 1.1.212)

Norton Safe Web (version 1.1.4)

**Comment by JoryHogeveen** [comment] 2020-07-06 12:35
Might be related: https://forum.qnap.com/viewtopic.php?p=741646&sid=62df7c83238163010dcee643fce234fa

**Comment by amlange** [comment] 2020-07-06 16:04
I am not sure about this. The screen froze when I used the Safari browser and I was using Flywheel Local and also when I moved my site up to the Flywheel servers and used the Safari browser. I did not do anything different from the normal process when installing and activating the PODS plugin in Flywheel Local. It works fine if I use the Google Chrome browser.
