### ISSUE TITLE
Latest update appears to have broken pods_api_pre_save_pod_item_

### ISSUE THREAD

**Issue by Pezzab** [pods-framework/pods#5532] opened 2019-11-14 10:38 UTC
**Describe the bug**
`pods_api_pre_save_pod_item_` no longer allows me to populate for e.g. the post title with a pods field

**To Reproduce**
[I used the Pods docs own example to reproduce](https://docs.pods.io/code-snippets/create-post-title-from-fields-in-the-post-using-pods_api_pre_save/)

**Expected behavior**
I'm using a pods pre save function to populate a custom post title based on the above code example. Yesterday it worked, this morning after the latest Pods update it stopped working.

I reproduced the Pods docs example on my set up to make sure and this fails too - title comes up with placeholder "(no title)".

## Pods Version
Pods 2.7.16 Maintenance Update

## WordPress Environment
WordPress Version: 5.3

PHP Version: 5.6.30-12~ubuntu16.04.1+deb.sury.org+1

MySQL Version: 5.5.5

Server Software: nginx/1.14.0

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

Session Save Path: /var/lib/php/sessions

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    OPcache: Yes
    Redis: No

Object Cache:

    APC: No
    APCu: No
    Memcache: Yes
    Memcached: Yes
    Redis: Yes

WPDB Prefix: wp_3_

WP Multisite Mode: Yes

WP Memory Limit: 64M

Current Memory Usage: 35.492M

Current Memory Usage (real): 36.500M

Pods Network-Wide Activated: Yes

Pods Install Location: /var/www/testsite.co.uk/htdocs/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: BLAMSMALB

Currently Active Plugins:

    Add From Server: 3.3.3
    Admin Columns: 3.4.6
    Nginx Helper: 2.1.0
    Pods - Custom Content Types and Fields: 2.7.16.1
    Query Monitor: 3.4.0
    Radio Buttons for Taxonomies: 2.0.0
    Regenerate Thumbnails: 3.1.2
    Subpages Extended: 1.6.4
    W3 Total Cache: 0.10.2
    Widget Logic: 5.10.4
    WP All Import Pro: 4.5.6
    WP Bulk Delete: 1.1.3
    Yoast SEO: 12.5

**Comment by Pezzab** [comment] 2019-11-14 11:00
Just to confirm: I rolled back Pods to the prior version and the above code worked

**Comment by jimtrue** [comment] 2019-11-14 12:37
@Pezzab  you need to provide your actual code, please

**Comment by Pezzab** [comment] 2019-11-14 12:48
Hi Jim,

The example code (linked under To Reproduce) in the Pods docs does the trick, my own code merely swaps out the variables and post type name.

**Comment by jimtrue** [comment] 2019-11-14 12:50
@Pezzab  we have to attempt to replicate your issue. That’s why we request the package export and the code you’re using. You may think it’s no big deal, but it’s helpful

**Comment by Pezzab** [comment] 2019-11-14 12:57
```
add_filter( 'pods_api_pre_save_pod_item_meal', 'slug_set_title', 10, 2);
function slug_set_title($pieces, $is_new_item) {
	//check if is new item, if not return $pieces without making any changes
	if ( ! $is_new_item ) {
		return $pieces;
	}
	//make sure that all three fields are active
	$fields = array( 'post_title', 'sandwich', 'beverage' );
	foreach( $fields as $field ) {
		if ( ! isset( $pieces[ 'fields_active' ][ $field ] ) ) {
			array_push ($pieces[ 'fields_active' ], $field );
		}
	}
	//set variables for fields empty first for saftey's sake
	$sandwich = $beverage = '';
	//get value of "sandwich" if possible
	if ( isset( $pieces[ 'fields' ][ 'sandwich' ] ) && isset( $pieces[ 'fields'][ 'sandwich' ][ 'value' ] ) && is_string( $pieces[ 'fields' ][ 'sandwich' ][ 'value' ] ) ) {
		$sandwich = $pieces[ 'fields' ][ 'sandwich' ][ 'value' ];
	}
	//get value of "beverage" if possible
	if ( isset( $pieces[ 'fields' ][ 'beverage' ] ) && isset( $pieces[ 'fields'][ 'beverage' ][ 'value' ] ) && is_string( $pieces[ 'fields' ][ 'beverage' ][ 'value' ] ) ) {
		$beverage = $pieces[ 'fields' ][ 'beverage' ][ 'value' ];
	}
	//set post title using $sandwich and $beverage
	$pieces[ 'object_fields' ][ 'post_title' ][ 'value' ] = $sandwich . ' and ' . $beverage;
	//return $pieces to save
	return $pieces;
}


```

Pods name `meal`, pods fields `sandwich` and `beverage`, both in plain text
```

**Comment by a2guy** [comment] 2020-02-13 18:09
I will second that I have exactly the same problem here.  the pods_api_pre_save functionality is not working for myself either. 

Using the following as a guide:
[https://docs.pods.io/code-snippets/create-post-title-from-fields-in-the-post-using-pods_api_pre_save/]

I then created the POD "meal" with custom fields "beverage" and "sandwich" (exported below):

`{"meta":{"version":"2.7.16.2","build":1581616967},"pods":{"4831":{"id":4831,"name":"meal","label":"meals","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"sandwich":{"id":4832,"name":"sandwich","label":"sandwich","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"1","rest_pick_response":"array","rest_pick_depth":"2","text_repeatable":0,"text_placeholder":""},"beverage":{"id":4833,"name":"beverage","label":"beverage","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"1","rest_write":"1","rest_pick_response":"array","rest_pick_depth":"2","text_repeatable":0,"text_placeholder":""}},"show_in_menu":"1","label_singular":"meal","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"meal","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_activity":"0","built_in_taxonomies_bp-email-type":"0","built_in_taxonomies_bp_group_type":"0","built_in_taxonomies_bp_member_type":"0","built_in_taxonomies_category":"0","built_in_taxonomies_itinerary_types":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_travel_keywords":"0","built_in_taxonomies_travel_locations":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_single":"Trip Posts Intermediate Template","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0"}}}`

Finally I used the following code from the PODS documentation at the link above (and reprinted below).  I placed the code in my theme's plugin folders as bill.php and activated the plugin.

`
if( ! defined( 'ABSPATH') ) {
    exit;
}

add_filter( 'pods_api_pre_save_pod_item_meal', 'slug_set_title', 10, 2);

function slug_set_title($pieces, $is_new_item) {
echo '<script>alert("Welcome to Your New Title Function")</script>';
        //check if is new item, if not return $pieces without making any changes
        if ( ! $is_new_item ) {
                return $pieces;
        }
        //make sure that all three fields are active
        $fields = array( 'post_title', 'sandwich', 'beverage' );
        foreach( $fields as $field ) {
                if ( ! isset( $pieces[ 'fields_active' ][ $field ] ) ) {
                        array_push ($pieces[ 'fields_active' ], $field );
                }
        }
        //set variables for fields empty first for saftey's sake
        $sandwich = $beverage = '';
        //get value of "sandwich" if possible
        if ( isset( $pieces[ 'fields' ][ 'sandwich' ] ) && isset( $pieces[ 'fields'][ 'sandwich' ][ 'value' ] ) && is_string( $pieces[ 'fields' ][ 'sandwich' ][ 'value' ] ) ) {
                $sandwich = $pieces[ 'fields' ][ 'sandwich' ][ 'value' ];
        }
        //get value of "beverage" if possible
        if ( isset( $pieces[ 'fields' ][ 'beverage' ] ) && isset( $pieces[ 'fields'][ 'beverage' ][ 'value' ] ) && is_string( $pieces[ 'fields' ][ 'beverage' ][ 'value' ] ) ) {
                $beverage = $pieces[ 'fields' ][ 'beverage' ][ 'value' ];
        }
        //set post title using $sandwich and $beverage
        $pieces[ 'object_fields' ][ 'post_title' ][ 'value' ] = $sandwich . ' and ' . $beverage;
        //return $pieces to save
        return $pieces;
}
`

**Comment by jimothyr** [comment] 2020-09-14 11:02
same problem here. cant get pods_api_pre_save_pod_item_ to see any content in the object_fields array... So cant grab or update any WP object data.  

Any news on this?

**Comment by HmCody** [comment] 2021-05-21 20:22
I am also running into a problem with pods_api_pre_save_pod_item_{podname}, but only when I try to edit a field through Admin Columns Pro. If I use the pods form everything works perfectly. If I edit a field using Admin Columns pro, my function pods_api_pre_save_pod_item_field_event fires, but it looks as if $pieces isn't being fully populated. It has all the right fields, but the fields don't seem to have values.

Let me know if there is anything I can send you to help sort this out.

WordPress Version: 5.7.2
PHP Version: 7.4.13
MySQL Version: 8.0.22
Admin Columns Pro: 5.5.1
Admin Columns Pro - Pods: 1.5.1
Pods - Custom Content Types and Fields: 2.7.27

**Comment by HmCody** [comment] 2021-06-10 15:05
I went back and set up a local test site with just Pods and my code as activated plugins. Admin Columns Pro was deactivated.

I created a Pod called "Events" with two fields, event_date and event_text, leaving Post Title enabled to start. I also created a page with a shortcode which could trigger an add for an event from code.

My code was as follows (I added line numbers for reference):

```
1		function pods_add_test() {
2			$data = array(
3				'post_title' => 'A test title',
4				'event_date' => '2021-07-01 00:00',
5				'display_date' => '2021-07-01 00:00',
6				'event_text' => 'Some event text.'
7				);
8			$newEvent = pods('event');
9			$newId = $newEvent->add($data);
10			echo '<h1>New Id: ' . $newId;
11		}
12		add_shortcode('mypodsadd','pods_add_test');
13
14		add_filter('pods_api_pre_save_pod_item_event', 'pre_save_event_function', 10, 3);
15		function pre_save_event_function($pieces, $is_new_item, $id) {
16		if ($is_new_item) {
17			$pieces[ 'object_fields' ][ 'post_title' ][ 'value' ] = 'New event';
18			$pieces['fields']['event_text']['value'] = 'New event text';
19		} else {
20			$pieces[ 'object_fields' ][ 'post_title' ][ 'value' ] = 'Changed event';
21			$pieces['fields']['event_text']['value'] = 'Changed event text';
22		}
23	return $pieces;
24	}
```

I then set break points at lines 16 and 23 so I could check the values as they were being processed. I ran three test cases, adding a new item with the "Add new" button, adding a new item by running the shortcode, and editing an existing item. I then disabled the Post Title for the Event pod and ran those three tests again. You can see the full results at https://docs.google.com/spreadsheets/d/1jflYELV7T3t9i6azA73AUlVE7U4vxKkdl24MdmHBilY/edit?usp=sharing

Quick summary, it looks as if $is_new_item in pods_api_pre_save_pod_item_ is only TRUE if the filter is processed when an add is made via code. I think this may be because using the "Add new" button creates a "dummy post" before the filter is run, while using pods->add does not. If you look at $id, it is 0 when using pods->add, but >0 when using "Add new." Also, Post Title is only updated when $is_new_item = TRUE. The actual pods fields seem to update regardless of the value of $is_new_item, though with the wrong values if the "Add new" button is used.

I also ran some tests with Admin Columns Pro activated, editing the values for Post Title, event_text, and event_date through the Admin Columns column editing feature. pods_api_pre_save_pod_item_ only runs when the Event pod fields are edited (which makes sense), though the Post Title is not changed by the code (which is consistent with what happened with the earlier tests). Also of note is that Admin Columns only appears to pass the value of the field being edited, not all of the fields in the pod. I'm guessing that this is by design, but thought I would mention it.

I hope this helps in sorting out this issue. Let me know if I can provide any additional information.

**Comment by petersjoo** [comment] 2023-10-16 14:55
Broken again in v. 3.

**Comment by olivierguerriat** [comment] 2023-10-19 08:56
I believe this is due to [this line](https://github.com/pods-framework/pods/blob/52daa18318f376e98fca57569a7ddb78bbe4ac06/classes/PodsAPI.php#L5141), because `$pieces` only contains valid keys as values while `$hooked` contains sub-arrays. Hence, `array_intersect_key` always return an empty array and nothing is extracted.
```php
$hooked = $this->do_hook( "pre_save_pod_item_{$params->pod}", compact( $pieces ), $is_new_item, $params->id );
if ( is_array( $hooked ) && ! empty( $hooked ) ) {
   $hooked = array_intersect_key( $pieces, $hooked );
   extract( $hooked );
}
```
As a workaround, I commented the `array_intersect_key` line, but I would love to get a proper fix.

**Comment by sc0ttkclark** [comment] 2023-10-19 21:58
Fixed via https://github.com/pods-framework/pods/commit/848954021a0fb07efc186f98a8a0039bc23db228

**Closed by sc0ttkclark** 2023-10-19 21:58 UTC
Labels: Type: Bug

**Comment by nymets1104** [comment] 2023-10-20 09:41
Thank you @sc0ttkclark any idea when this will be pushed out to WP? I ended up here as I was having same exact issue today. Thanks

**Comment by sc0ttkclark** [comment] 2023-10-20 12:03
This morning I'll be releasing it unless I find anything else that needs to go in.
