### ISSUE TITLE
Featured Image of a Related Pod Not Working

### ISSUE THREAD

**Issue by theRiesgo** [pods-framework/pods#4821] opened 2018-04-03 15:16 UTC
## Issue Overview
I am trying to pull in a featured image {@related_field.post_thumbnail_url} and it only returns as unknown.

## Expected Behavior
{@related_field.post_thumbnail_url} should return the featured image url of the post in a loop. What it is doing is just returning unknown. 
{@related_field.post_thumbnail} also returns nothing.

## Current Behavior
Currently, I have a pod `Location` & `Awards`

`Location` has the following fields
post_title ( title )
post_thumbnail ( featured image )
related_awards ( bi-directional relationship field )

`Awards` has the following fields
post_title ( title )
post_thumbnail ( featured image )
award_location ( bi-directional relationship field )

Using pods templates, I have this is my code: 
```
[if related_awards]
[before]
	<div class="box-title">
		Company Awards
	</div>
	<div class="box-body">
[/before]
[each related_awards]
		<div class="location-awards">
			<a href="{@permalink}"><img class="img-responsive award-img" src="{@post_thumbnail}" alt="{@post_title}"></a>
			<p class="award-title"><strong>{@post_title}</strong></p>
			<a class="award-link" href="{@permalink}">View Award</a>
		</div>
[/each]
[after]
	</div>
	<div class="box-footer">
		<a href="/about-us/awards">See All Awards</a>
	</div>
[/after]
[/if]
```

## Workaround
I have also tried using the workaround {@id,get_post_thumbnail_id} found here: https://github.com/pods-framework/pods/issues/4719 inside of my pods template and it only returns the id of the post, not of the featured image.

**Comment by jimtrue** [comment] 2018-04-03 15:25
Your Workaround is what you're having the issue with. Other than that this is the issue that is demonstrated in #4719.

Some problems in your notes above, it's not `{@related_field.post_thumbnail}` that isn't working correctly. I can attest that works fine. The problem is with:
```
[each related_field]
   {@post_thumbnail}
[/each]
```
Which #4719 designates is broken; the workaround of `{@ID,get_the_post_thumbnail_url}` works in every template I've tested.

@theRiesgo Please add any commentary on the workaround not working for you in #4719 I'm closing this as a duplicate issue.

**Closed by jimtrue** 2018-04-03 15:25 UTC
Labels: Duplicate
